global: #全局配置
  namespace: Production            #环境类型，分正式production和非正式development两种类型
  env_name: dev                    #环境名称，非正式环境下多环境的名称

server:
  timeout: 5000
  service:
    - name: trpc.moox.collector.scf_observability.timer
      port: 8005
      network: "*/30 * * * * *?scheduler=scfObservability&startAtOnce=1"
      protocol: timer
      timeout: 20000

plugins:
  log:
    default:
      - writer: console
        level: info
