global: #全局配置
  namespace: Production            #环境类型，分正式production和非正式development两种类型
  env_name: dev                    #环境名称，非正式环境下多环境的名称

server:
  timeout: 5000
  admin:
    ip: 127.0.0.1
    port: 11943
    read_timeout: 3000
    write_timeout: 60000
  service:
      ######## 定时任务 ########
    - name: trpc.heartbeat.timer
      port: 8001
      network: "*/9 * * * * *?scheduler=heartbeatSchedule&startAtOnce=1"
      protocol: timer
      timeout: 5000  #请求最长处理时间 单位 毫秒

    - name: trpc.dnsresolve.timer
      port: 8003
      network: "30 * * * * *?scheduler=dnsResolveSchedule&startAtOnce=1"
      protocol: timer
      timeout: 5000  #请求最长处理时间 单位 毫秒

plugins:
  log:
    default:
      - writer: console
        level: info
