// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: cloudnode.proto

package cloudnodepb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// CloudNodeMgrService defines service.
type CloudNodeMgrService interface {
	GetNodeList(ctx context.Context, req *GetNodeListReq) (*GetNodeListRsp, error)

	UpdateNode(ctx context.Context, req *UpdateNodeReq) (*UpdateNodeRsp, error)

	InvokeFunction(ctx context.Context, req *InvokeFunctionReq) (*InvokeFunctionRsp, error)

	SubmitCreateNodes(ctx context.Context, req *BatchCreateNodesReq) (*SubmitNodeBatchRsp, error)

	SubmitDeployNodes(ctx context.Context, req *BatchDeployNodesReq) (*SubmitNodeBatchRsp, error)

	SubmitDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq) (*SubmitNodeBatchRsp, error)

	GetNodeBatchChange(ctx context.Context, req *GetNodeBatchChangeReq) (*GetNodeBatchChangeRsp, error)

	BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq) (*BatchDeleteNodesRsp, error)

	SubmitUpdateNodeRuntimeConfigs(ctx context.Context, req *BatchUpdateNodeRuntimeConfigsReq) (*SubmitNodeBatchRsp, error)

	ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq) (*ListCloudAccountsRsp, error)

	CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq) (*CreateCloudAccountRsp, error)

	UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq) (*UpdateCloudAccountRsp, error)

	DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq) (*DeleteCloudAccountRsp, error)

	ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq) (*ListCloudRegionsRsp, error)

	PreviewSCFFunctions(ctx context.Context, req *PreviewSCFFunctionsReq) (*PreviewSCFFunctionsRsp, error)

	ImportSCFFunctions(ctx context.Context, req *ImportSCFFunctionsReq) (*ImportSCFFunctionsRsp, error)

	GetPackageList(ctx context.Context, req *GetPackageListReq) (*GetPackageListRsp, error)

	GetPackageDetail(ctx context.Context, req *GetPackageDetailReq) (*GetPackageDetailRsp, error)

	DeletePackage(ctx context.Context, req *DeletePackageReq) (*DeletePackageRsp, error)

	GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq) (*GetPackageDownloadURLRsp, error)

	InitPackageUpload(ctx context.Context, req *InitPackageUploadReq) (*InitPackageUploadRsp, error)

	CompletePackageUpload(ctx context.Context, req *CompletePackageUploadReq) (*CompletePackageUploadRsp, error)

	SubmitJobItems(ctx context.Context, req *SubmitJobItemsReq) (*SubmitJobItemsRsp, error)

	ReportJobItemStatus(ctx context.Context, req *ReportJobItemStatusReq) (*ReportJobItemStatusRsp, error)

	GetJobItem(ctx context.Context, req *GetJobItemReq) (*GetJobItemRsp, error)

	ListJobItems(ctx context.Context, req *ListJobItemsReq) (*ListJobItemsRsp, error)

	InvokeSync(ctx context.Context, req *InvokeSyncReq) (*InvokeSyncRsp, error)
}

func CloudNodeMgrService_GetNodeList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetNodeListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetNodeList(ctx, reqbody.(*GetNodeListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_UpdateNode_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateNodeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).UpdateNode(ctx, reqbody.(*UpdateNodeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_InvokeFunction_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &InvokeFunctionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).InvokeFunction(ctx, reqbody.(*InvokeFunctionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_SubmitCreateNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchCreateNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).SubmitCreateNodes(ctx, reqbody.(*BatchCreateNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_SubmitDeployNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchDeployNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).SubmitDeployNodes(ctx, reqbody.(*BatchDeployNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_SubmitDeleteNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchDeleteNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).SubmitDeleteNodes(ctx, reqbody.(*BatchDeleteNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetNodeBatchChange_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetNodeBatchChangeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetNodeBatchChange(ctx, reqbody.(*GetNodeBatchChangeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_BatchDeleteNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchDeleteNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).BatchDeleteNodes(ctx, reqbody.(*BatchDeleteNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_SubmitUpdateNodeRuntimeConfigs_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchUpdateNodeRuntimeConfigsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).SubmitUpdateNodeRuntimeConfigs(ctx, reqbody.(*BatchUpdateNodeRuntimeConfigsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ListCloudAccounts_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListCloudAccountsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ListCloudAccounts(ctx, reqbody.(*ListCloudAccountsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_CreateCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).CreateCloudAccount(ctx, reqbody.(*CreateCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_UpdateCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).UpdateCloudAccount(ctx, reqbody.(*UpdateCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_DeleteCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).DeleteCloudAccount(ctx, reqbody.(*DeleteCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ListCloudRegions_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListCloudRegionsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ListCloudRegions(ctx, reqbody.(*ListCloudRegionsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_PreviewSCFFunctions_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PreviewSCFFunctionsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).PreviewSCFFunctions(ctx, reqbody.(*PreviewSCFFunctionsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ImportSCFFunctions_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ImportSCFFunctionsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ImportSCFFunctions(ctx, reqbody.(*ImportSCFFunctionsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageList(ctx, reqbody.(*GetPackageListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageDetail(ctx, reqbody.(*GetPackageDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_DeletePackage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeletePackageReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).DeletePackage(ctx, reqbody.(*DeletePackageReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageDownloadURL_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageDownloadURLReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageDownloadURL(ctx, reqbody.(*GetPackageDownloadURLReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_InitPackageUpload_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &InitPackageUploadReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).InitPackageUpload(ctx, reqbody.(*InitPackageUploadReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_CompletePackageUpload_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CompletePackageUploadReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).CompletePackageUpload(ctx, reqbody.(*CompletePackageUploadReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_SubmitJobItems_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SubmitJobItemsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).SubmitJobItems(ctx, reqbody.(*SubmitJobItemsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ReportJobItemStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReportJobItemStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ReportJobItemStatus(ctx, reqbody.(*ReportJobItemStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetJobItem_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetJobItemReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetJobItem(ctx, reqbody.(*GetJobItemReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ListJobItems_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListJobItemsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ListJobItems(ctx, reqbody.(*ListJobItemsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_InvokeSync_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &InvokeSyncReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).InvokeSync(ctx, reqbody.(*InvokeSyncReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CloudNodeMgrServer_ServiceDesc descriptor for server.RegisterService.
var CloudNodeMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.cloudnode.CloudNodeMgr",
	HandlerType: ((*CloudNodeMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/GetNodeList",
			Func: CloudNodeMgrService_GetNodeList_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/UpdateNode",
			Func: CloudNodeMgrService_UpdateNode_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/InvokeFunction",
			Func: CloudNodeMgrService_InvokeFunction_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/SubmitCreateNodes",
			Func: CloudNodeMgrService_SubmitCreateNodes_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/SubmitDeployNodes",
			Func: CloudNodeMgrService_SubmitDeployNodes_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/SubmitDeleteNodes",
			Func: CloudNodeMgrService_SubmitDeleteNodes_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/GetNodeBatchChange",
			Func: CloudNodeMgrService_GetNodeBatchChange_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/BatchDeleteNodes",
			Func: CloudNodeMgrService_BatchDeleteNodes_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/SubmitUpdateNodeRuntimeConfigs",
			Func: CloudNodeMgrService_SubmitUpdateNodeRuntimeConfigs_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/ListCloudAccounts",
			Func: CloudNodeMgrService_ListCloudAccounts_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/CreateCloudAccount",
			Func: CloudNodeMgrService_CreateCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/UpdateCloudAccount",
			Func: CloudNodeMgrService_UpdateCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/DeleteCloudAccount",
			Func: CloudNodeMgrService_DeleteCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/ListCloudRegions",
			Func: CloudNodeMgrService_ListCloudRegions_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/PreviewSCFFunctions",
			Func: CloudNodeMgrService_PreviewSCFFunctions_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/ImportSCFFunctions",
			Func: CloudNodeMgrService_ImportSCFFunctions_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/GetPackageList",
			Func: CloudNodeMgrService_GetPackageList_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/GetPackageDetail",
			Func: CloudNodeMgrService_GetPackageDetail_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/DeletePackage",
			Func: CloudNodeMgrService_DeletePackage_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/GetPackageDownloadURL",
			Func: CloudNodeMgrService_GetPackageDownloadURL_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/InitPackageUpload",
			Func: CloudNodeMgrService_InitPackageUpload_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/CompletePackageUpload",
			Func: CloudNodeMgrService_CompletePackageUpload_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/SubmitJobItems",
			Func: CloudNodeMgrService_SubmitJobItems_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/ReportJobItemStatus",
			Func: CloudNodeMgrService_ReportJobItemStatus_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/GetJobItem",
			Func: CloudNodeMgrService_GetJobItem_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/ListJobItems",
			Func: CloudNodeMgrService_ListJobItems_Handler,
		},
		{
			Name: "/trpc.moox.cloudnode.CloudNodeMgr/InvokeSync",
			Func: CloudNodeMgrService_InvokeSync_Handler,
		},
	},
}

// RegisterCloudNodeMgrService registers service.
func RegisterCloudNodeMgrService(s server.Service, svr CloudNodeMgrService) {
	if err := s.Register(&CloudNodeMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("CloudNodeMgr register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedCloudNodeMgr struct{}

func (s *UnimplementedCloudNodeMgr) GetNodeList(ctx context.Context, req *GetNodeListReq) (*GetNodeListRsp, error) {
	return nil, errors.New("rpc GetNodeList of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) UpdateNode(ctx context.Context, req *UpdateNodeReq) (*UpdateNodeRsp, error) {
	return nil, errors.New("rpc UpdateNode of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) InvokeFunction(ctx context.Context, req *InvokeFunctionReq) (*InvokeFunctionRsp, error) {
	return nil, errors.New("rpc InvokeFunction of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) SubmitCreateNodes(ctx context.Context, req *BatchCreateNodesReq) (*SubmitNodeBatchRsp, error) {
	return nil, errors.New("rpc SubmitCreateNodes of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) SubmitDeployNodes(ctx context.Context, req *BatchDeployNodesReq) (*SubmitNodeBatchRsp, error) {
	return nil, errors.New("rpc SubmitDeployNodes of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) SubmitDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq) (*SubmitNodeBatchRsp, error) {
	return nil, errors.New("rpc SubmitDeleteNodes of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetNodeBatchChange(ctx context.Context, req *GetNodeBatchChangeReq) (*GetNodeBatchChangeRsp, error) {
	return nil, errors.New("rpc GetNodeBatchChange of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq) (*BatchDeleteNodesRsp, error) {
	return nil, errors.New("rpc BatchDeleteNodes of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) SubmitUpdateNodeRuntimeConfigs(ctx context.Context, req *BatchUpdateNodeRuntimeConfigsReq) (*SubmitNodeBatchRsp, error) {
	return nil, errors.New("rpc SubmitUpdateNodeRuntimeConfigs of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq) (*ListCloudAccountsRsp, error) {
	return nil, errors.New("rpc ListCloudAccounts of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq) (*CreateCloudAccountRsp, error) {
	return nil, errors.New("rpc CreateCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq) (*UpdateCloudAccountRsp, error) {
	return nil, errors.New("rpc UpdateCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq) (*DeleteCloudAccountRsp, error) {
	return nil, errors.New("rpc DeleteCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq) (*ListCloudRegionsRsp, error) {
	return nil, errors.New("rpc ListCloudRegions of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) PreviewSCFFunctions(ctx context.Context, req *PreviewSCFFunctionsReq) (*PreviewSCFFunctionsRsp, error) {
	return nil, errors.New("rpc PreviewSCFFunctions of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) ImportSCFFunctions(ctx context.Context, req *ImportSCFFunctionsReq) (*ImportSCFFunctionsRsp, error) {
	return nil, errors.New("rpc ImportSCFFunctions of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetPackageList(ctx context.Context, req *GetPackageListReq) (*GetPackageListRsp, error) {
	return nil, errors.New("rpc GetPackageList of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetPackageDetail(ctx context.Context, req *GetPackageDetailReq) (*GetPackageDetailRsp, error) {
	return nil, errors.New("rpc GetPackageDetail of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) DeletePackage(ctx context.Context, req *DeletePackageReq) (*DeletePackageRsp, error) {
	return nil, errors.New("rpc DeletePackage of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq) (*GetPackageDownloadURLRsp, error) {
	return nil, errors.New("rpc GetPackageDownloadURL of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) InitPackageUpload(ctx context.Context, req *InitPackageUploadReq) (*InitPackageUploadRsp, error) {
	return nil, errors.New("rpc InitPackageUpload of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) CompletePackageUpload(ctx context.Context, req *CompletePackageUploadReq) (*CompletePackageUploadRsp, error) {
	return nil, errors.New("rpc CompletePackageUpload of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) SubmitJobItems(ctx context.Context, req *SubmitJobItemsReq) (*SubmitJobItemsRsp, error) {
	return nil, errors.New("rpc SubmitJobItems of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) ReportJobItemStatus(ctx context.Context, req *ReportJobItemStatusReq) (*ReportJobItemStatusRsp, error) {
	return nil, errors.New("rpc ReportJobItemStatus of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetJobItem(ctx context.Context, req *GetJobItemReq) (*GetJobItemRsp, error) {
	return nil, errors.New("rpc GetJobItem of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) ListJobItems(ctx context.Context, req *ListJobItemsReq) (*ListJobItemsRsp, error) {
	return nil, errors.New("rpc ListJobItems of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) InvokeSync(ctx context.Context, req *InvokeSyncReq) (*InvokeSyncRsp, error) {
	return nil, errors.New("rpc InvokeSync of service CloudNodeMgr is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// CloudNodeMgrClientProxy defines service client proxy
type CloudNodeMgrClientProxy interface {
	GetNodeList(ctx context.Context, req *GetNodeListReq, opts ...client.Option) (rsp *GetNodeListRsp, err error)

	UpdateNode(ctx context.Context, req *UpdateNodeReq, opts ...client.Option) (rsp *UpdateNodeRsp, err error)

	InvokeFunction(ctx context.Context, req *InvokeFunctionReq, opts ...client.Option) (rsp *InvokeFunctionRsp, err error)

	SubmitCreateNodes(ctx context.Context, req *BatchCreateNodesReq, opts ...client.Option) (rsp *SubmitNodeBatchRsp, err error)

	SubmitDeployNodes(ctx context.Context, req *BatchDeployNodesReq, opts ...client.Option) (rsp *SubmitNodeBatchRsp, err error)

	SubmitDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq, opts ...client.Option) (rsp *SubmitNodeBatchRsp, err error)

	GetNodeBatchChange(ctx context.Context, req *GetNodeBatchChangeReq, opts ...client.Option) (rsp *GetNodeBatchChangeRsp, err error)

	BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq, opts ...client.Option) (rsp *BatchDeleteNodesRsp, err error)

	SubmitUpdateNodeRuntimeConfigs(ctx context.Context, req *BatchUpdateNodeRuntimeConfigsReq, opts ...client.Option) (rsp *SubmitNodeBatchRsp, err error)

	ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq, opts ...client.Option) (rsp *ListCloudAccountsRsp, err error)

	CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq, opts ...client.Option) (rsp *CreateCloudAccountRsp, err error)

	UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq, opts ...client.Option) (rsp *UpdateCloudAccountRsp, err error)

	DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq, opts ...client.Option) (rsp *DeleteCloudAccountRsp, err error)

	ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq, opts ...client.Option) (rsp *ListCloudRegionsRsp, err error)

	PreviewSCFFunctions(ctx context.Context, req *PreviewSCFFunctionsReq, opts ...client.Option) (rsp *PreviewSCFFunctionsRsp, err error)

	ImportSCFFunctions(ctx context.Context, req *ImportSCFFunctionsReq, opts ...client.Option) (rsp *ImportSCFFunctionsRsp, err error)

	GetPackageList(ctx context.Context, req *GetPackageListReq, opts ...client.Option) (rsp *GetPackageListRsp, err error)

	GetPackageDetail(ctx context.Context, req *GetPackageDetailReq, opts ...client.Option) (rsp *GetPackageDetailRsp, err error)

	DeletePackage(ctx context.Context, req *DeletePackageReq, opts ...client.Option) (rsp *DeletePackageRsp, err error)

	GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq, opts ...client.Option) (rsp *GetPackageDownloadURLRsp, err error)

	InitPackageUpload(ctx context.Context, req *InitPackageUploadReq, opts ...client.Option) (rsp *InitPackageUploadRsp, err error)

	CompletePackageUpload(ctx context.Context, req *CompletePackageUploadReq, opts ...client.Option) (rsp *CompletePackageUploadRsp, err error)

	SubmitJobItems(ctx context.Context, req *SubmitJobItemsReq, opts ...client.Option) (rsp *SubmitJobItemsRsp, err error)

	ReportJobItemStatus(ctx context.Context, req *ReportJobItemStatusReq, opts ...client.Option) (rsp *ReportJobItemStatusRsp, err error)

	GetJobItem(ctx context.Context, req *GetJobItemReq, opts ...client.Option) (rsp *GetJobItemRsp, err error)

	ListJobItems(ctx context.Context, req *ListJobItemsReq, opts ...client.Option) (rsp *ListJobItemsRsp, err error)

	InvokeSync(ctx context.Context, req *InvokeSyncReq, opts ...client.Option) (rsp *InvokeSyncRsp, err error)
}

type CloudNodeMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCloudNodeMgrClientProxy = func(opts ...client.Option) CloudNodeMgrClientProxy {
	return &CloudNodeMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CloudNodeMgrClientProxyImpl) GetNodeList(ctx context.Context, req *GetNodeListReq, opts ...client.Option) (*GetNodeListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/GetNodeList")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetNodeList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetNodeListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) UpdateNode(ctx context.Context, req *UpdateNodeReq, opts ...client.Option) (*UpdateNodeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/UpdateNode")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("UpdateNode")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateNodeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) InvokeFunction(ctx context.Context, req *InvokeFunctionReq, opts ...client.Option) (*InvokeFunctionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/InvokeFunction")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("InvokeFunction")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &InvokeFunctionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) SubmitCreateNodes(ctx context.Context, req *BatchCreateNodesReq, opts ...client.Option) (*SubmitNodeBatchRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/SubmitCreateNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("SubmitCreateNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SubmitNodeBatchRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) SubmitDeployNodes(ctx context.Context, req *BatchDeployNodesReq, opts ...client.Option) (*SubmitNodeBatchRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/SubmitDeployNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("SubmitDeployNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SubmitNodeBatchRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) SubmitDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq, opts ...client.Option) (*SubmitNodeBatchRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/SubmitDeleteNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("SubmitDeleteNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SubmitNodeBatchRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetNodeBatchChange(ctx context.Context, req *GetNodeBatchChangeReq, opts ...client.Option) (*GetNodeBatchChangeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/GetNodeBatchChange")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetNodeBatchChange")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetNodeBatchChangeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq, opts ...client.Option) (*BatchDeleteNodesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/BatchDeleteNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("BatchDeleteNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &BatchDeleteNodesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) SubmitUpdateNodeRuntimeConfigs(ctx context.Context, req *BatchUpdateNodeRuntimeConfigsReq, opts ...client.Option) (*SubmitNodeBatchRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/SubmitUpdateNodeRuntimeConfigs")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("SubmitUpdateNodeRuntimeConfigs")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SubmitNodeBatchRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq, opts ...client.Option) (*ListCloudAccountsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/ListCloudAccounts")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ListCloudAccounts")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListCloudAccountsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq, opts ...client.Option) (*CreateCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/CreateCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("CreateCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq, opts ...client.Option) (*UpdateCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/UpdateCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("UpdateCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq, opts ...client.Option) (*DeleteCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/DeleteCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("DeleteCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq, opts ...client.Option) (*ListCloudRegionsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/ListCloudRegions")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ListCloudRegions")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListCloudRegionsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) PreviewSCFFunctions(ctx context.Context, req *PreviewSCFFunctionsReq, opts ...client.Option) (*PreviewSCFFunctionsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/PreviewSCFFunctions")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("PreviewSCFFunctions")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PreviewSCFFunctionsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ImportSCFFunctions(ctx context.Context, req *ImportSCFFunctionsReq, opts ...client.Option) (*ImportSCFFunctionsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/ImportSCFFunctions")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ImportSCFFunctions")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ImportSCFFunctionsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageList(ctx context.Context, req *GetPackageListReq, opts ...client.Option) (*GetPackageListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/GetPackageList")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageDetail(ctx context.Context, req *GetPackageDetailReq, opts ...client.Option) (*GetPackageDetailRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/GetPackageDetail")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageDetailRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) DeletePackage(ctx context.Context, req *DeletePackageReq, opts ...client.Option) (*DeletePackageRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/DeletePackage")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("DeletePackage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeletePackageRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq, opts ...client.Option) (*GetPackageDownloadURLRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/GetPackageDownloadURL")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageDownloadURL")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageDownloadURLRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) InitPackageUpload(ctx context.Context, req *InitPackageUploadReq, opts ...client.Option) (*InitPackageUploadRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/InitPackageUpload")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("InitPackageUpload")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &InitPackageUploadRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) CompletePackageUpload(ctx context.Context, req *CompletePackageUploadReq, opts ...client.Option) (*CompletePackageUploadRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/CompletePackageUpload")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("CompletePackageUpload")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CompletePackageUploadRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) SubmitJobItems(ctx context.Context, req *SubmitJobItemsReq, opts ...client.Option) (*SubmitJobItemsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/SubmitJobItems")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("SubmitJobItems")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SubmitJobItemsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ReportJobItemStatus(ctx context.Context, req *ReportJobItemStatusReq, opts ...client.Option) (*ReportJobItemStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/ReportJobItemStatus")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ReportJobItemStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReportJobItemStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetJobItem(ctx context.Context, req *GetJobItemReq, opts ...client.Option) (*GetJobItemRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/GetJobItem")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetJobItem")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetJobItemRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ListJobItems(ctx context.Context, req *ListJobItemsReq, opts ...client.Option) (*ListJobItemsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/ListJobItems")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ListJobItems")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListJobItemsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) InvokeSync(ctx context.Context, req *InvokeSyncReq, opts ...client.Option) (*InvokeSyncRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.cloudnode.CloudNodeMgr/InvokeSync")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("cloudnode")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("InvokeSync")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &InvokeSyncRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
