// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: trade_service.proto

package mooxpb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AccountSvcService defines service.
type AccountSvcService interface {
	CreateAccount(ctx context.Context, req *CreateAccountReq) (*CreateAccountRsp, error)

	UpdateAccount(ctx context.Context, req *UpdateAccountReq) (*UpdateAccountRsp, error)

	DeleteAccount(ctx context.Context, req *DeleteAccountReq) (*DeleteAccountRsp, error)

	GetAccount(ctx context.Context, req *GetAccountReq) (*GetAccountRsp, error)

	ListAccounts(ctx context.Context, req *ListAccountsReq) (*ListAccountsRsp, error)
}

func AccountSvcService_CreateAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AccountSvcService).CreateAccount(ctx, reqbody.(*CreateAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AccountSvcService_UpdateAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AccountSvcService).UpdateAccount(ctx, reqbody.(*UpdateAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AccountSvcService_DeleteAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AccountSvcService).DeleteAccount(ctx, reqbody.(*DeleteAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AccountSvcService_GetAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AccountSvcService).GetAccount(ctx, reqbody.(*GetAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AccountSvcService_ListAccounts_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListAccountsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AccountSvcService).ListAccounts(ctx, reqbody.(*ListAccountsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AccountSvcServer_ServiceDesc descriptor for server.RegisterService.
var AccountSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.AccountSvc",
	HandlerType: ((*AccountSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.AccountSvc/CreateAccount",
			Func: AccountSvcService_CreateAccount_Handler,
		},
		{
			Name: "/trpc.moox.trade.AccountSvc/UpdateAccount",
			Func: AccountSvcService_UpdateAccount_Handler,
		},
		{
			Name: "/trpc.moox.trade.AccountSvc/DeleteAccount",
			Func: AccountSvcService_DeleteAccount_Handler,
		},
		{
			Name: "/trpc.moox.trade.AccountSvc/GetAccount",
			Func: AccountSvcService_GetAccount_Handler,
		},
		{
			Name: "/trpc.moox.trade.AccountSvc/ListAccounts",
			Func: AccountSvcService_ListAccounts_Handler,
		},
	},
}

// RegisterAccountSvcService registers service.
func RegisterAccountSvcService(s server.Service, svr AccountSvcService) {
	if err := s.Register(&AccountSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AccountSvc register error:%v", err))
	}
}

// BalanceSvcService defines service.
type BalanceSvcService interface {
	GetBalances(ctx context.Context, req *GetBalancesReq) (*GetBalancesRsp, error)

	SyncBalances(ctx context.Context, req *SyncBalancesReq) (*SyncBalancesRsp, error)
}

func BalanceSvcService_GetBalances_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetBalancesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BalanceSvcService).GetBalances(ctx, reqbody.(*GetBalancesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func BalanceSvcService_SyncBalances_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SyncBalancesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(BalanceSvcService).SyncBalances(ctx, reqbody.(*SyncBalancesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// BalanceSvcServer_ServiceDesc descriptor for server.RegisterService.
var BalanceSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.BalanceSvc",
	HandlerType: ((*BalanceSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.BalanceSvc/GetBalances",
			Func: BalanceSvcService_GetBalances_Handler,
		},
		{
			Name: "/trpc.moox.trade.BalanceSvc/SyncBalances",
			Func: BalanceSvcService_SyncBalances_Handler,
		},
	},
}

// RegisterBalanceSvcService registers service.
func RegisterBalanceSvcService(s server.Service, svr BalanceSvcService) {
	if err := s.Register(&BalanceSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("BalanceSvc register error:%v", err))
	}
}

// FundSvcService defines service.
type FundSvcService interface {
	ListFundFlows(ctx context.Context, req *ListFundFlowsReq) (*ListFundFlowsRsp, error)

	Transfer(ctx context.Context, req *TransferReq) (*TransferRsp, error)
}

func FundSvcService_ListFundFlows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListFundFlowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FundSvcService).ListFundFlows(ctx, reqbody.(*ListFundFlowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FundSvcService_Transfer_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TransferReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FundSvcService).Transfer(ctx, reqbody.(*TransferReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// FundSvcServer_ServiceDesc descriptor for server.RegisterService.
var FundSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.FundSvc",
	HandlerType: ((*FundSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.FundSvc/ListFundFlows",
			Func: FundSvcService_ListFundFlows_Handler,
		},
		{
			Name: "/trpc.moox.trade.FundSvc/Transfer",
			Func: FundSvcService_Transfer_Handler,
		},
	},
}

// RegisterFundSvcService registers service.
func RegisterFundSvcService(s server.Service, svr FundSvcService) {
	if err := s.Register(&FundSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("FundSvc register error:%v", err))
	}
}

// ApiKeySvcService defines service.
type ApiKeySvcService interface {
	CreateApiKey(ctx context.Context, req *CreateApiKeyReq) (*CreateApiKeyRsp, error)

	DeleteApiKey(ctx context.Context, req *DeleteApiKeyReq) (*DeleteApiKeyRsp, error)

	ListApiKeys(ctx context.Context, req *ListApiKeysReq) (*ListApiKeysRsp, error)
}

func ApiKeySvcService_CreateApiKey_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateApiKeyReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ApiKeySvcService).CreateApiKey(ctx, reqbody.(*CreateApiKeyReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ApiKeySvcService_DeleteApiKey_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteApiKeyReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ApiKeySvcService).DeleteApiKey(ctx, reqbody.(*DeleteApiKeyReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ApiKeySvcService_ListApiKeys_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListApiKeysReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ApiKeySvcService).ListApiKeys(ctx, reqbody.(*ListApiKeysReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ApiKeySvcServer_ServiceDesc descriptor for server.RegisterService.
var ApiKeySvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.ApiKeySvc",
	HandlerType: ((*ApiKeySvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.ApiKeySvc/CreateApiKey",
			Func: ApiKeySvcService_CreateApiKey_Handler,
		},
		{
			Name: "/trpc.moox.trade.ApiKeySvc/DeleteApiKey",
			Func: ApiKeySvcService_DeleteApiKey_Handler,
		},
		{
			Name: "/trpc.moox.trade.ApiKeySvc/ListApiKeys",
			Func: ApiKeySvcService_ListApiKeys_Handler,
		},
	},
}

// RegisterApiKeySvcService registers service.
func RegisterApiKeySvcService(s server.Service, svr ApiKeySvcService) {
	if err := s.Register(&ApiKeySvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ApiKeySvc register error:%v", err))
	}
}

// ChannelSvcService defines service.
type ChannelSvcService interface {
	CreateChannel(ctx context.Context, req *CreateChannelReq) (*CreateChannelRsp, error)

	UpdateChannel(ctx context.Context, req *UpdateChannelReq) (*UpdateChannelRsp, error)

	DeleteChannel(ctx context.Context, req *DeleteChannelReq) (*DeleteChannelRsp, error)

	ListChannels(ctx context.Context, req *ListChannelsReq) (*ListChannelsRsp, error)

	TestChannel(ctx context.Context, req *TestChannelReq) (*TestChannelRsp, error)
}

func ChannelSvcService_CreateChannel_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateChannelReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ChannelSvcService).CreateChannel(ctx, reqbody.(*CreateChannelReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ChannelSvcService_UpdateChannel_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateChannelReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ChannelSvcService).UpdateChannel(ctx, reqbody.(*UpdateChannelReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ChannelSvcService_DeleteChannel_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteChannelReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ChannelSvcService).DeleteChannel(ctx, reqbody.(*DeleteChannelReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ChannelSvcService_ListChannels_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListChannelsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ChannelSvcService).ListChannels(ctx, reqbody.(*ListChannelsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ChannelSvcService_TestChannel_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TestChannelReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ChannelSvcService).TestChannel(ctx, reqbody.(*TestChannelReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ChannelSvcServer_ServiceDesc descriptor for server.RegisterService.
var ChannelSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.ChannelSvc",
	HandlerType: ((*ChannelSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.ChannelSvc/CreateChannel",
			Func: ChannelSvcService_CreateChannel_Handler,
		},
		{
			Name: "/trpc.moox.trade.ChannelSvc/UpdateChannel",
			Func: ChannelSvcService_UpdateChannel_Handler,
		},
		{
			Name: "/trpc.moox.trade.ChannelSvc/DeleteChannel",
			Func: ChannelSvcService_DeleteChannel_Handler,
		},
		{
			Name: "/trpc.moox.trade.ChannelSvc/ListChannels",
			Func: ChannelSvcService_ListChannels_Handler,
		},
		{
			Name: "/trpc.moox.trade.ChannelSvc/TestChannel",
			Func: ChannelSvcService_TestChannel_Handler,
		},
	},
}

// RegisterChannelSvcService registers service.
func RegisterChannelSvcService(s server.Service, svr ChannelSvcService) {
	if err := s.Register(&ChannelSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ChannelSvc register error:%v", err))
	}
}

// TradeOpSvcService defines service.
type TradeOpSvcService interface {
	PlaceOrder(ctx context.Context, req *PlaceOrderReq) (*PlaceOrderRsp, error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (*CancelOrderRsp, error)

	CancelAllOrders(ctx context.Context, req *CancelAllOrdersReq) (*CancelAllOrdersRsp, error)

	AmendOrder(ctx context.Context, req *AmendOrderReq) (*AmendOrderRsp, error)

	SetLeverage(ctx context.Context, req *SetLeverageReq) (*SetLeverageRsp, error)
}

func TradeOpSvcService_PlaceOrder_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PlaceOrderReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TradeOpSvcService).PlaceOrder(ctx, reqbody.(*PlaceOrderReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func TradeOpSvcService_CancelOrder_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CancelOrderReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TradeOpSvcService).CancelOrder(ctx, reqbody.(*CancelOrderReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func TradeOpSvcService_CancelAllOrders_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CancelAllOrdersReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TradeOpSvcService).CancelAllOrders(ctx, reqbody.(*CancelAllOrdersReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func TradeOpSvcService_AmendOrder_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AmendOrderReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TradeOpSvcService).AmendOrder(ctx, reqbody.(*AmendOrderReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func TradeOpSvcService_SetLeverage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SetLeverageReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TradeOpSvcService).SetLeverage(ctx, reqbody.(*SetLeverageReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// TradeOpSvcServer_ServiceDesc descriptor for server.RegisterService.
var TradeOpSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.TradeOpSvc",
	HandlerType: ((*TradeOpSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.TradeOpSvc/PlaceOrder",
			Func: TradeOpSvcService_PlaceOrder_Handler,
		},
		{
			Name: "/trpc.moox.trade.TradeOpSvc/CancelOrder",
			Func: TradeOpSvcService_CancelOrder_Handler,
		},
		{
			Name: "/trpc.moox.trade.TradeOpSvc/CancelAllOrders",
			Func: TradeOpSvcService_CancelAllOrders_Handler,
		},
		{
			Name: "/trpc.moox.trade.TradeOpSvc/AmendOrder",
			Func: TradeOpSvcService_AmendOrder_Handler,
		},
		{
			Name: "/trpc.moox.trade.TradeOpSvc/SetLeverage",
			Func: TradeOpSvcService_SetLeverage_Handler,
		},
	},
}

// RegisterTradeOpSvcService registers service.
func RegisterTradeOpSvcService(s server.Service, svr TradeOpSvcService) {
	if err := s.Register(&TradeOpSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("TradeOpSvc register error:%v", err))
	}
}

// OrderSvcService defines service.
type OrderSvcService interface {
	GetOrder(ctx context.Context, req *GetOrderReq) (*GetOrderRsp, error)

	ListOrders(ctx context.Context, req *ListOrdersReq) (*ListOrdersRsp, error)
}

func OrderSvcService_GetOrder_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetOrderReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(OrderSvcService).GetOrder(ctx, reqbody.(*GetOrderReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func OrderSvcService_ListOrders_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListOrdersReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(OrderSvcService).ListOrders(ctx, reqbody.(*ListOrdersReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// OrderSvcServer_ServiceDesc descriptor for server.RegisterService.
var OrderSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.OrderSvc",
	HandlerType: ((*OrderSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.OrderSvc/GetOrder",
			Func: OrderSvcService_GetOrder_Handler,
		},
		{
			Name: "/trpc.moox.trade.OrderSvc/ListOrders",
			Func: OrderSvcService_ListOrders_Handler,
		},
	},
}

// RegisterOrderSvcService registers service.
func RegisterOrderSvcService(s server.Service, svr OrderSvcService) {
	if err := s.Register(&OrderSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("OrderSvc register error:%v", err))
	}
}

// TradeQuerySvcService defines service.
type TradeQuerySvcService interface {
	ListTrades(ctx context.Context, req *ListTradesReq) (*ListTradesRsp, error)
}

func TradeQuerySvcService_ListTrades_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListTradesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TradeQuerySvcService).ListTrades(ctx, reqbody.(*ListTradesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// TradeQuerySvcServer_ServiceDesc descriptor for server.RegisterService.
var TradeQuerySvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.TradeQuerySvc",
	HandlerType: ((*TradeQuerySvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.TradeQuerySvc/ListTrades",
			Func: TradeQuerySvcService_ListTrades_Handler,
		},
	},
}

// RegisterTradeQuerySvcService registers service.
func RegisterTradeQuerySvcService(s server.Service, svr TradeQuerySvcService) {
	if err := s.Register(&TradeQuerySvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("TradeQuerySvc register error:%v", err))
	}
}

// PositionSvcService defines service.
type PositionSvcService interface {
	ListPositions(ctx context.Context, req *ListPositionsReq) (*ListPositionsRsp, error)
}

func PositionSvcService_ListPositions_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListPositionsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PositionSvcService).ListPositions(ctx, reqbody.(*ListPositionsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// PositionSvcServer_ServiceDesc descriptor for server.RegisterService.
var PositionSvcServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.trade.PositionSvc",
	HandlerType: ((*PositionSvcService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.trade.PositionSvc/ListPositions",
			Func: PositionSvcService_ListPositions_Handler,
		},
	},
}

// RegisterPositionSvcService registers service.
func RegisterPositionSvcService(s server.Service, svr PositionSvcService) {
	if err := s.Register(&PositionSvcServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("PositionSvc register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAccountSvc struct{}

func (s *UnimplementedAccountSvc) CreateAccount(ctx context.Context, req *CreateAccountReq) (*CreateAccountRsp, error) {
	return nil, errors.New("rpc CreateAccount of service AccountSvc is not implemented")
}
func (s *UnimplementedAccountSvc) UpdateAccount(ctx context.Context, req *UpdateAccountReq) (*UpdateAccountRsp, error) {
	return nil, errors.New("rpc UpdateAccount of service AccountSvc is not implemented")
}
func (s *UnimplementedAccountSvc) DeleteAccount(ctx context.Context, req *DeleteAccountReq) (*DeleteAccountRsp, error) {
	return nil, errors.New("rpc DeleteAccount of service AccountSvc is not implemented")
}
func (s *UnimplementedAccountSvc) GetAccount(ctx context.Context, req *GetAccountReq) (*GetAccountRsp, error) {
	return nil, errors.New("rpc GetAccount of service AccountSvc is not implemented")
}
func (s *UnimplementedAccountSvc) ListAccounts(ctx context.Context, req *ListAccountsReq) (*ListAccountsRsp, error) {
	return nil, errors.New("rpc ListAccounts of service AccountSvc is not implemented")
}

type UnimplementedBalanceSvc struct{}

func (s *UnimplementedBalanceSvc) GetBalances(ctx context.Context, req *GetBalancesReq) (*GetBalancesRsp, error) {
	return nil, errors.New("rpc GetBalances of service BalanceSvc is not implemented")
}
func (s *UnimplementedBalanceSvc) SyncBalances(ctx context.Context, req *SyncBalancesReq) (*SyncBalancesRsp, error) {
	return nil, errors.New("rpc SyncBalances of service BalanceSvc is not implemented")
}

type UnimplementedFundSvc struct{}

func (s *UnimplementedFundSvc) ListFundFlows(ctx context.Context, req *ListFundFlowsReq) (*ListFundFlowsRsp, error) {
	return nil, errors.New("rpc ListFundFlows of service FundSvc is not implemented")
}
func (s *UnimplementedFundSvc) Transfer(ctx context.Context, req *TransferReq) (*TransferRsp, error) {
	return nil, errors.New("rpc Transfer of service FundSvc is not implemented")
}

type UnimplementedApiKeySvc struct{}

func (s *UnimplementedApiKeySvc) CreateApiKey(ctx context.Context, req *CreateApiKeyReq) (*CreateApiKeyRsp, error) {
	return nil, errors.New("rpc CreateApiKey of service ApiKeySvc is not implemented")
}
func (s *UnimplementedApiKeySvc) DeleteApiKey(ctx context.Context, req *DeleteApiKeyReq) (*DeleteApiKeyRsp, error) {
	return nil, errors.New("rpc DeleteApiKey of service ApiKeySvc is not implemented")
}
func (s *UnimplementedApiKeySvc) ListApiKeys(ctx context.Context, req *ListApiKeysReq) (*ListApiKeysRsp, error) {
	return nil, errors.New("rpc ListApiKeys of service ApiKeySvc is not implemented")
}

type UnimplementedChannelSvc struct{}

func (s *UnimplementedChannelSvc) CreateChannel(ctx context.Context, req *CreateChannelReq) (*CreateChannelRsp, error) {
	return nil, errors.New("rpc CreateChannel of service ChannelSvc is not implemented")
}
func (s *UnimplementedChannelSvc) UpdateChannel(ctx context.Context, req *UpdateChannelReq) (*UpdateChannelRsp, error) {
	return nil, errors.New("rpc UpdateChannel of service ChannelSvc is not implemented")
}
func (s *UnimplementedChannelSvc) DeleteChannel(ctx context.Context, req *DeleteChannelReq) (*DeleteChannelRsp, error) {
	return nil, errors.New("rpc DeleteChannel of service ChannelSvc is not implemented")
}
func (s *UnimplementedChannelSvc) ListChannels(ctx context.Context, req *ListChannelsReq) (*ListChannelsRsp, error) {
	return nil, errors.New("rpc ListChannels of service ChannelSvc is not implemented")
}
func (s *UnimplementedChannelSvc) TestChannel(ctx context.Context, req *TestChannelReq) (*TestChannelRsp, error) {
	return nil, errors.New("rpc TestChannel of service ChannelSvc is not implemented")
}

type UnimplementedTradeOpSvc struct{}

func (s *UnimplementedTradeOpSvc) PlaceOrder(ctx context.Context, req *PlaceOrderReq) (*PlaceOrderRsp, error) {
	return nil, errors.New("rpc PlaceOrder of service TradeOpSvc is not implemented")
}
func (s *UnimplementedTradeOpSvc) CancelOrder(ctx context.Context, req *CancelOrderReq) (*CancelOrderRsp, error) {
	return nil, errors.New("rpc CancelOrder of service TradeOpSvc is not implemented")
}
func (s *UnimplementedTradeOpSvc) CancelAllOrders(ctx context.Context, req *CancelAllOrdersReq) (*CancelAllOrdersRsp, error) {
	return nil, errors.New("rpc CancelAllOrders of service TradeOpSvc is not implemented")
}
func (s *UnimplementedTradeOpSvc) AmendOrder(ctx context.Context, req *AmendOrderReq) (*AmendOrderRsp, error) {
	return nil, errors.New("rpc AmendOrder of service TradeOpSvc is not implemented")
}
func (s *UnimplementedTradeOpSvc) SetLeverage(ctx context.Context, req *SetLeverageReq) (*SetLeverageRsp, error) {
	return nil, errors.New("rpc SetLeverage of service TradeOpSvc is not implemented")
}

type UnimplementedOrderSvc struct{}

func (s *UnimplementedOrderSvc) GetOrder(ctx context.Context, req *GetOrderReq) (*GetOrderRsp, error) {
	return nil, errors.New("rpc GetOrder of service OrderSvc is not implemented")
}
func (s *UnimplementedOrderSvc) ListOrders(ctx context.Context, req *ListOrdersReq) (*ListOrdersRsp, error) {
	return nil, errors.New("rpc ListOrders of service OrderSvc is not implemented")
}

type UnimplementedTradeQuerySvc struct{}

func (s *UnimplementedTradeQuerySvc) ListTrades(ctx context.Context, req *ListTradesReq) (*ListTradesRsp, error) {
	return nil, errors.New("rpc ListTrades of service TradeQuerySvc is not implemented")
}

type UnimplementedPositionSvc struct{}

func (s *UnimplementedPositionSvc) ListPositions(ctx context.Context, req *ListPositionsReq) (*ListPositionsRsp, error) {
	return nil, errors.New("rpc ListPositions of service PositionSvc is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AccountSvcClientProxy defines service client proxy
type AccountSvcClientProxy interface {
	CreateAccount(ctx context.Context, req *CreateAccountReq, opts ...client.Option) (rsp *CreateAccountRsp, err error)

	UpdateAccount(ctx context.Context, req *UpdateAccountReq, opts ...client.Option) (rsp *UpdateAccountRsp, err error)

	DeleteAccount(ctx context.Context, req *DeleteAccountReq, opts ...client.Option) (rsp *DeleteAccountRsp, err error)

	GetAccount(ctx context.Context, req *GetAccountReq, opts ...client.Option) (rsp *GetAccountRsp, err error)

	ListAccounts(ctx context.Context, req *ListAccountsReq, opts ...client.Option) (rsp *ListAccountsRsp, err error)
}

type AccountSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAccountSvcClientProxy = func(opts ...client.Option) AccountSvcClientProxy {
	return &AccountSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AccountSvcClientProxyImpl) CreateAccount(ctx context.Context, req *CreateAccountReq, opts ...client.Option) (*CreateAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.AccountSvc/CreateAccount")
	msg.WithCalleeServiceName(AccountSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("AccountSvc")
	msg.WithCalleeMethod("CreateAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AccountSvcClientProxyImpl) UpdateAccount(ctx context.Context, req *UpdateAccountReq, opts ...client.Option) (*UpdateAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.AccountSvc/UpdateAccount")
	msg.WithCalleeServiceName(AccountSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("AccountSvc")
	msg.WithCalleeMethod("UpdateAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AccountSvcClientProxyImpl) DeleteAccount(ctx context.Context, req *DeleteAccountReq, opts ...client.Option) (*DeleteAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.AccountSvc/DeleteAccount")
	msg.WithCalleeServiceName(AccountSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("AccountSvc")
	msg.WithCalleeMethod("DeleteAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AccountSvcClientProxyImpl) GetAccount(ctx context.Context, req *GetAccountReq, opts ...client.Option) (*GetAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.AccountSvc/GetAccount")
	msg.WithCalleeServiceName(AccountSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("AccountSvc")
	msg.WithCalleeMethod("GetAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AccountSvcClientProxyImpl) ListAccounts(ctx context.Context, req *ListAccountsReq, opts ...client.Option) (*ListAccountsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.AccountSvc/ListAccounts")
	msg.WithCalleeServiceName(AccountSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("AccountSvc")
	msg.WithCalleeMethod("ListAccounts")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListAccountsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// BalanceSvcClientProxy defines service client proxy
type BalanceSvcClientProxy interface {
	GetBalances(ctx context.Context, req *GetBalancesReq, opts ...client.Option) (rsp *GetBalancesRsp, err error)

	SyncBalances(ctx context.Context, req *SyncBalancesReq, opts ...client.Option) (rsp *SyncBalancesRsp, err error)
}

type BalanceSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewBalanceSvcClientProxy = func(opts ...client.Option) BalanceSvcClientProxy {
	return &BalanceSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *BalanceSvcClientProxyImpl) GetBalances(ctx context.Context, req *GetBalancesReq, opts ...client.Option) (*GetBalancesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.BalanceSvc/GetBalances")
	msg.WithCalleeServiceName(BalanceSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("BalanceSvc")
	msg.WithCalleeMethod("GetBalances")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetBalancesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *BalanceSvcClientProxyImpl) SyncBalances(ctx context.Context, req *SyncBalancesReq, opts ...client.Option) (*SyncBalancesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.BalanceSvc/SyncBalances")
	msg.WithCalleeServiceName(BalanceSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("BalanceSvc")
	msg.WithCalleeMethod("SyncBalances")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SyncBalancesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// FundSvcClientProxy defines service client proxy
type FundSvcClientProxy interface {
	ListFundFlows(ctx context.Context, req *ListFundFlowsReq, opts ...client.Option) (rsp *ListFundFlowsRsp, err error)

	Transfer(ctx context.Context, req *TransferReq, opts ...client.Option) (rsp *TransferRsp, err error)
}

type FundSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewFundSvcClientProxy = func(opts ...client.Option) FundSvcClientProxy {
	return &FundSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *FundSvcClientProxyImpl) ListFundFlows(ctx context.Context, req *ListFundFlowsReq, opts ...client.Option) (*ListFundFlowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.FundSvc/ListFundFlows")
	msg.WithCalleeServiceName(FundSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("FundSvc")
	msg.WithCalleeMethod("ListFundFlows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListFundFlowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FundSvcClientProxyImpl) Transfer(ctx context.Context, req *TransferReq, opts ...client.Option) (*TransferRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.FundSvc/Transfer")
	msg.WithCalleeServiceName(FundSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("FundSvc")
	msg.WithCalleeMethod("Transfer")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TransferRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// ApiKeySvcClientProxy defines service client proxy
type ApiKeySvcClientProxy interface {
	CreateApiKey(ctx context.Context, req *CreateApiKeyReq, opts ...client.Option) (rsp *CreateApiKeyRsp, err error)

	DeleteApiKey(ctx context.Context, req *DeleteApiKeyReq, opts ...client.Option) (rsp *DeleteApiKeyRsp, err error)

	ListApiKeys(ctx context.Context, req *ListApiKeysReq, opts ...client.Option) (rsp *ListApiKeysRsp, err error)
}

type ApiKeySvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewApiKeySvcClientProxy = func(opts ...client.Option) ApiKeySvcClientProxy {
	return &ApiKeySvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ApiKeySvcClientProxyImpl) CreateApiKey(ctx context.Context, req *CreateApiKeyReq, opts ...client.Option) (*CreateApiKeyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ApiKeySvc/CreateApiKey")
	msg.WithCalleeServiceName(ApiKeySvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ApiKeySvc")
	msg.WithCalleeMethod("CreateApiKey")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateApiKeyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ApiKeySvcClientProxyImpl) DeleteApiKey(ctx context.Context, req *DeleteApiKeyReq, opts ...client.Option) (*DeleteApiKeyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ApiKeySvc/DeleteApiKey")
	msg.WithCalleeServiceName(ApiKeySvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ApiKeySvc")
	msg.WithCalleeMethod("DeleteApiKey")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteApiKeyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ApiKeySvcClientProxyImpl) ListApiKeys(ctx context.Context, req *ListApiKeysReq, opts ...client.Option) (*ListApiKeysRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ApiKeySvc/ListApiKeys")
	msg.WithCalleeServiceName(ApiKeySvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ApiKeySvc")
	msg.WithCalleeMethod("ListApiKeys")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListApiKeysRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// ChannelSvcClientProxy defines service client proxy
type ChannelSvcClientProxy interface {
	CreateChannel(ctx context.Context, req *CreateChannelReq, opts ...client.Option) (rsp *CreateChannelRsp, err error)

	UpdateChannel(ctx context.Context, req *UpdateChannelReq, opts ...client.Option) (rsp *UpdateChannelRsp, err error)

	DeleteChannel(ctx context.Context, req *DeleteChannelReq, opts ...client.Option) (rsp *DeleteChannelRsp, err error)

	ListChannels(ctx context.Context, req *ListChannelsReq, opts ...client.Option) (rsp *ListChannelsRsp, err error)

	TestChannel(ctx context.Context, req *TestChannelReq, opts ...client.Option) (rsp *TestChannelRsp, err error)
}

type ChannelSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewChannelSvcClientProxy = func(opts ...client.Option) ChannelSvcClientProxy {
	return &ChannelSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ChannelSvcClientProxyImpl) CreateChannel(ctx context.Context, req *CreateChannelReq, opts ...client.Option) (*CreateChannelRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ChannelSvc/CreateChannel")
	msg.WithCalleeServiceName(ChannelSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ChannelSvc")
	msg.WithCalleeMethod("CreateChannel")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateChannelRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ChannelSvcClientProxyImpl) UpdateChannel(ctx context.Context, req *UpdateChannelReq, opts ...client.Option) (*UpdateChannelRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ChannelSvc/UpdateChannel")
	msg.WithCalleeServiceName(ChannelSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ChannelSvc")
	msg.WithCalleeMethod("UpdateChannel")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateChannelRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ChannelSvcClientProxyImpl) DeleteChannel(ctx context.Context, req *DeleteChannelReq, opts ...client.Option) (*DeleteChannelRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ChannelSvc/DeleteChannel")
	msg.WithCalleeServiceName(ChannelSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ChannelSvc")
	msg.WithCalleeMethod("DeleteChannel")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteChannelRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ChannelSvcClientProxyImpl) ListChannels(ctx context.Context, req *ListChannelsReq, opts ...client.Option) (*ListChannelsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ChannelSvc/ListChannels")
	msg.WithCalleeServiceName(ChannelSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ChannelSvc")
	msg.WithCalleeMethod("ListChannels")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListChannelsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ChannelSvcClientProxyImpl) TestChannel(ctx context.Context, req *TestChannelReq, opts ...client.Option) (*TestChannelRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.ChannelSvc/TestChannel")
	msg.WithCalleeServiceName(ChannelSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("ChannelSvc")
	msg.WithCalleeMethod("TestChannel")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TestChannelRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// TradeOpSvcClientProxy defines service client proxy
type TradeOpSvcClientProxy interface {
	PlaceOrder(ctx context.Context, req *PlaceOrderReq, opts ...client.Option) (rsp *PlaceOrderRsp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq, opts ...client.Option) (rsp *CancelOrderRsp, err error)

	CancelAllOrders(ctx context.Context, req *CancelAllOrdersReq, opts ...client.Option) (rsp *CancelAllOrdersRsp, err error)

	AmendOrder(ctx context.Context, req *AmendOrderReq, opts ...client.Option) (rsp *AmendOrderRsp, err error)

	SetLeverage(ctx context.Context, req *SetLeverageReq, opts ...client.Option) (rsp *SetLeverageRsp, err error)
}

type TradeOpSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewTradeOpSvcClientProxy = func(opts ...client.Option) TradeOpSvcClientProxy {
	return &TradeOpSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *TradeOpSvcClientProxyImpl) PlaceOrder(ctx context.Context, req *PlaceOrderReq, opts ...client.Option) (*PlaceOrderRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.TradeOpSvc/PlaceOrder")
	msg.WithCalleeServiceName(TradeOpSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("TradeOpSvc")
	msg.WithCalleeMethod("PlaceOrder")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PlaceOrderRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *TradeOpSvcClientProxyImpl) CancelOrder(ctx context.Context, req *CancelOrderReq, opts ...client.Option) (*CancelOrderRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.TradeOpSvc/CancelOrder")
	msg.WithCalleeServiceName(TradeOpSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("TradeOpSvc")
	msg.WithCalleeMethod("CancelOrder")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CancelOrderRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *TradeOpSvcClientProxyImpl) CancelAllOrders(ctx context.Context, req *CancelAllOrdersReq, opts ...client.Option) (*CancelAllOrdersRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.TradeOpSvc/CancelAllOrders")
	msg.WithCalleeServiceName(TradeOpSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("TradeOpSvc")
	msg.WithCalleeMethod("CancelAllOrders")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CancelAllOrdersRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *TradeOpSvcClientProxyImpl) AmendOrder(ctx context.Context, req *AmendOrderReq, opts ...client.Option) (*AmendOrderRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.TradeOpSvc/AmendOrder")
	msg.WithCalleeServiceName(TradeOpSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("TradeOpSvc")
	msg.WithCalleeMethod("AmendOrder")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AmendOrderRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *TradeOpSvcClientProxyImpl) SetLeverage(ctx context.Context, req *SetLeverageReq, opts ...client.Option) (*SetLeverageRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.TradeOpSvc/SetLeverage")
	msg.WithCalleeServiceName(TradeOpSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("TradeOpSvc")
	msg.WithCalleeMethod("SetLeverage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SetLeverageRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// OrderSvcClientProxy defines service client proxy
type OrderSvcClientProxy interface {
	GetOrder(ctx context.Context, req *GetOrderReq, opts ...client.Option) (rsp *GetOrderRsp, err error)

	ListOrders(ctx context.Context, req *ListOrdersReq, opts ...client.Option) (rsp *ListOrdersRsp, err error)
}

type OrderSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewOrderSvcClientProxy = func(opts ...client.Option) OrderSvcClientProxy {
	return &OrderSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *OrderSvcClientProxyImpl) GetOrder(ctx context.Context, req *GetOrderReq, opts ...client.Option) (*GetOrderRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.OrderSvc/GetOrder")
	msg.WithCalleeServiceName(OrderSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("OrderSvc")
	msg.WithCalleeMethod("GetOrder")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetOrderRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *OrderSvcClientProxyImpl) ListOrders(ctx context.Context, req *ListOrdersReq, opts ...client.Option) (*ListOrdersRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.OrderSvc/ListOrders")
	msg.WithCalleeServiceName(OrderSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("OrderSvc")
	msg.WithCalleeMethod("ListOrders")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListOrdersRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// TradeQuerySvcClientProxy defines service client proxy
type TradeQuerySvcClientProxy interface {
	ListTrades(ctx context.Context, req *ListTradesReq, opts ...client.Option) (rsp *ListTradesRsp, err error)
}

type TradeQuerySvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewTradeQuerySvcClientProxy = func(opts ...client.Option) TradeQuerySvcClientProxy {
	return &TradeQuerySvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *TradeQuerySvcClientProxyImpl) ListTrades(ctx context.Context, req *ListTradesReq, opts ...client.Option) (*ListTradesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.TradeQuerySvc/ListTrades")
	msg.WithCalleeServiceName(TradeQuerySvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("TradeQuerySvc")
	msg.WithCalleeMethod("ListTrades")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListTradesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// PositionSvcClientProxy defines service client proxy
type PositionSvcClientProxy interface {
	ListPositions(ctx context.Context, req *ListPositionsReq, opts ...client.Option) (rsp *ListPositionsRsp, err error)
}

type PositionSvcClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewPositionSvcClientProxy = func(opts ...client.Option) PositionSvcClientProxy {
	return &PositionSvcClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *PositionSvcClientProxyImpl) ListPositions(ctx context.Context, req *ListPositionsReq, opts ...client.Option) (*ListPositionsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.trade.PositionSvc/ListPositions")
	msg.WithCalleeServiceName(PositionSvcServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("trade")
	msg.WithCalleeService("PositionSvc")
	msg.WithCalleeMethod("ListPositions")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListPositionsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
