global:
  namespace: Development
  env_name: dev

server:
  filter:
    - validation
    - prometheus
  timeout: 5000
  admin:
    ip: 127.0.0.1
    port: 11942
    read_timeout: 3000
    write_timeout: 60000
  service:
    - name: trpc.moox.collector.CollectMgr
      port: 11402
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.collector.schedule.timer
      port: 11403
      network: "0 */1 * * * *?scheduler=collectorSchedule&disable=1&params="
      protocol: timer
      timeout: 60000
    - name: trpc.moox.collector.metrics.timer
      port: 11412
      network: "*/30 * * * * *?params="
      protocol: timer
      timeout: 10000
    - name: trpc.moox.collector.outbox.timer
      port: 11413
      network: "*/5 * * * * *?params="
      protocol: timer
      timeout: 10000

plugins:
  prometheus:
    ip: 127.0.0.1
    port: 12942
    path: /metrics
    enablepush: false
  auth:
    validation:
      enable_error_log: true
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  log:
    default:
      - writer: console
        level: info
