// Package ruleseed loads and safely applies the built-in Collector task bundle.
package ruleseed

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/mooyang-code/moox/modules/collector/internal/domain"
	"github.com/mooyang-code/moox/modules/collector/internal/planner/taskresult"
	"github.com/mooyang-code/moox/modules/collector/internal/store"
	"gopkg.in/yaml.v3"
	"gorm.io/gorm"
)

type taskSeed struct {
	Tasks []taskSeedItem `yaml:"tasks"`
}

type taskSeedItem struct {
	SpaceID       string         `yaml:"space_id"`
	TaskID        string         `yaml:"task_id"`
	TaskName      string         `yaml:"task_name"`
	Description   string         `yaml:"description"`
	DataType      string         `yaml:"data_type"`
	TagIDs        []string       `yaml:"tag_ids"`
	Enabled       bool           `yaml:"enabled"`
	Creator       string         `yaml:"creator"`
	CollectParams map[string]any `yaml:"collect_params"`
}

// SeedSummary reports missing-only task application results.
type SeedSummary struct {
	TasksCreated   int `json:"tasks_created"`
	TasksUnchanged int `json:"tasks_unchanged"`
}

// Load reads and validates a Collector task bundle.
func Load(r io.Reader) ([]domain.CollectionTask, error) {
	return loadTaskSeed(r)
}

// LoadFile reads and validates a Collector task bundle from disk.
func LoadFile(path string) ([]domain.CollectionTask, error) {
	if strings.TrimSpace(path) == "" {
		return nil, fmt.Errorf("seed file path is required")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open seed file: %w", err)
	}
	defer file.Close()
	return Load(file)
}

func loadTaskSeed(r io.Reader) ([]domain.CollectionTask, error) {
	if r == nil {
		return nil, fmt.Errorf("seed reader is required")
	}
	decoder := yaml.NewDecoder(r)
	decoder.KnownFields(true)
	var seed taskSeed
	if err := decoder.Decode(&seed); err != nil {
		return nil, fmt.Errorf("decode task seed: %w", err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("decode task seed: multiple YAML documents are not supported")
		}
		return nil, fmt.Errorf("decode task seed: %w", err)
	}
	if len(seed.Tasks) == 0 {
		return nil, fmt.Errorf("task seed must contain at least one task")
	}

	tasks := make([]domain.CollectionTask, 0, len(seed.Tasks))
	seen := make(map[string]struct{}, len(seed.Tasks))
	for index, item := range seed.Tasks {
		task, err := validateTaskSeedItem(item)
		if err != nil {
			return nil, fmt.Errorf("tasks[%d]: %w", index, err)
		}
		key := task.SpaceID + "\x00" + task.TaskID
		if _, exists := seen[key]; exists {
			return nil, fmt.Errorf("tasks[%d]: duplicate task %s/%s", index, task.SpaceID, task.TaskID)
		}
		seen[key] = struct{}{}
		tasks = append(tasks, task)
	}
	return tasks, nil
}

func validateTaskSeedItem(item taskSeedItem) (domain.CollectionTask, error) {
	spaceID := strings.TrimSpace(item.SpaceID)
	taskID := strings.TrimSpace(item.TaskID)
	taskName := domain.NormalizeCollectionTaskName(item.TaskName)
	dataType := strings.ToLower(strings.TrimSpace(item.DataType))
	tagIDs := normalizeSeedTagIDs(item.TagIDs)
	if err := domain.ValidateCollectionTaskName(taskName); err != nil {
		return domain.CollectionTask{}, fmt.Errorf("task_name: %w", err)
	}
	if spaceID == "" || taskID == "" || dataType == "" {
		return domain.CollectionTask{}, fmt.Errorf("space_id, task_id and data_type are required")
	}
	if dataType != "kline_resample" && len(tagIDs) == 0 {
		return domain.CollectionTask{}, fmt.Errorf("tag_ids are required for direct collection tasks")
	}
	if item.CollectParams == nil {
		return domain.CollectionTask{}, fmt.Errorf("collect_params is required")
	}
	if _, exists := item.CollectParams["target_dataset_id"]; exists {
		return domain.CollectionTask{}, fmt.Errorf("collect_params.target_dataset_id is generated by the task and must not be specified")
	}
	collectParams := make(map[string]any, len(item.CollectParams))
	for key, value := range item.CollectParams {
		collectParams[key] = value
	}
	rawParams, err := json.Marshal(collectParams)
	if err != nil {
		return domain.CollectionTask{}, fmt.Errorf("marshal collect_params: %w", err)
	}
	params, err := domain.ParseCollectParams(string(rawParams), "", "", dataType)
	if err != nil {
		return domain.CollectionTask{}, fmt.Errorf("collect_params: %w", err)
	}
	frequency := params.Frequency
	if strings.EqualFold(dataType, "kline_resample") {
		frequency = params.TargetFrequency
	}
	resultIDs := taskresult.ResultIDsForTask(spaceID, taskID, "", dataType, frequency)
	collectParams["target_dataset_id"] = resultIDs.DatasetID
	rawParams, err = json.Marshal(collectParams)
	if err != nil {
		return domain.CollectionTask{}, fmt.Errorf("marshal collect_params with result target: %w", err)
	}
	params, err = domain.ParseCollectParams(string(rawParams), "", "", dataType)
	if err != nil {
		return domain.CollectionTask{}, fmt.Errorf("collect_params: %w", err)
	}
	if dataType == "kline_resample" {
		if err := params.Validate(); err != nil {
			return domain.CollectionTask{}, fmt.Errorf("collect_params: %w", err)
		}
	} else {
		if params.SourceID != "" || params.InstrumentType != "" || params.SeriesTag != "" || len(params.SubjectTags) > 0 ||
			params.Provider != "" || params.MarketType != "" {
			return domain.CollectionTask{}, fmt.Errorf("direct collection routing and subject scope must come from tag_ids")
		}
		if err := params.ValidateTaskDefinition(); err != nil {
			return domain.CollectionTask{}, fmt.Errorf("collect_params: %w", err)
		}
	}
	canonical, err := json.Marshal(params)
	if err != nil {
		return domain.CollectionTask{}, fmt.Errorf("marshal canonical collect_params: %w", err)
	}
	return domain.CollectionTask{
		SpaceID:         spaceID,
		TaskID:          taskID,
		TaskName:        taskName,
		Description:     strings.TrimSpace(item.Description),
		DataType:        dataType,
		TagIDs:          tagIDs,
		CollectParams:   string(canonical),
		Enabled:         item.Enabled,
		Creator:         strings.TrimSpace(item.Creator),
		ResultDatasetID: resultIDs.DatasetID,
		ResultViewID:    resultIDs.ViewID,
	}, nil
}

func normalizeSeedTagIDs(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

// SeedMissing inserts only absent (space_id, task_id) pairs. Existing rows are
// deliberately left untouched so a user disable or edit survives redeploy.
func SeedMissing(ctx context.Context, repo *store.TaskRepository, tasks []domain.CollectionTask) (SeedSummary, error) {
	if repo == nil {
		return SeedSummary{}, fmt.Errorf("task repository is required")
	}
	var summary SeedSummary
	for _, task := range tasks {
		_, err := repo.GetByTaskID(ctx, task.SpaceID, task.TaskID)
		switch {
		case err == nil:
			summary.TasksUnchanged++
		case errors.Is(err, gorm.ErrRecordNotFound):
			if err := repo.Create(ctx, task); err != nil {
				return summary, fmt.Errorf("create task %s/%s: %w", task.SpaceID, task.TaskID, err)
			}
			summary.TasksCreated++
		default:
			return summary, fmt.Errorf("check task %s/%s: %w", task.SpaceID, task.TaskID, err)
		}
	}
	return summary, nil
}
