global: #全局配置
  namespace: Development            #环境类型，分正式production和非正式development两种类型
  env_name: test                    #环境名称，非正式环境下多环境的名称

server:
  filter:
    - validation
    - cors
  timeout: 5000
  admin:
    port: 20000
    read_timeout: 5000   #ms. 请求被接受到请求信息被完全读取的超时时间设置，防止慢客户端
    write_timeout: 60000 #ms. 处理的超时时间
  service:
    - name: trpc.moox.storage.Access
      #ip: 0.0.0.0
      port: 20102
      network: tcp
      protocol: trpc
    - name: trpc.moox.storage.DataView
      #ip: 0.0.0.0
      port: 20103
      network: tcp
      protocol: trpc
    - name: trpc.moox.storage.PrimaryStore
      #ip: 0.0.0.0
      port: 20101
      network: tcp # 注意：若是多机分布式部署，此处应改为tcp（单机也可设置tcp，只是unix域套接字本机通信效率更高）
      protocol: trpc
    - name: trpc.moox.storage.Metadata
      #ip: 0.0.0.0
      port: 20100
      network: tcp
      protocol: trpc
    - name: trpc.moox.storage.view.timer
      port: 20300
      network: "*/30 * * * * *?scheduler=viewBuilderSchedule&startAtOnce=1&params="
      protocol: timer
      timeout: 60000
    - name: trpc.moox.storage.view.cleanup.timer
      port: 20301
      network: "0 0 * * * *?scheduler=viewBuilderSchedule&params=op=cleanup"
      protocol: timer
      timeout: 60000
    - name: trpc.moox.storage.view.retry_failed.timer
      port: 20303
      network: "0 */10 * * * *?disable=1&scheduler=viewBuilderSchedule&params=op=retry_failed"
      protocol: timer
      timeout: 60000
    - name: trpc.moox.storage.archive.timer
      port: 20302
      network: "0 0 * * * *?disable=1&scheduler=archiveSchedule&params=space_id=crypto;dataset_id=*"
      protocol: timer
      timeout: 60000

    - name: trpc.moox.storage.Access
      #ip: 0.0.0.0
      port: 20201
      network: tcp
      protocol: http
    - name: trpc.moox.storage.Metadata
      #ip: 0.0.0.0
      port: 20200
      network: tcp
      protocol: http
    - name: trpc.moox.storage.DataView
      #ip: 0.0.0.0
      port: 20202
      network: tcp
      protocol: http

client:
  filter:
    - validation
  service:
    - name: trpc.moox.storage.PrimaryStore
      target: ip://127.0.0.1:20101
      network: tcp
      protocol: trpc
      timeout: 3000
    - name: trpc.moox.storage.Access
      target: ip://127.0.0.1:20201
      network: tcp
      protocol: http
      timeout: 3000
    - name: trpc.moox.storage.Metadata
      target: ip://127.0.0.1:20200
      network: tcp
      protocol: http
      timeout: 3000
    - name: trpc.moox.storage.DataView
      target: ip://127.0.0.1:20202
      network: tcp
      protocol: http
      timeout: 3000

plugins:
  auth:
    cors:
      apply_to_all_path:
        - insecure_allow_all
    validation:
      enable_error_log: true
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  log:
    default:
      - writer: file                              #本地文件日志
        level: debug                               #本地文件滚动日志的级别
        writer_config:                            #本地文件输出具体配置
          log_path: ./logs                        #本地文件日志路径
          filename: trpc.log                      #本地文件日志文件名
          roll_type: size                         #文件滚动类型,size为按大小滚动
          max_age: 7                              #最大日志保留天数
          max_size: 10                            #本地文件滚动日志的大小 单位 MB
          max_backups: 5                         #最大日志文件数
          compress:  false                        #日志文件是否压缩
