global:
  namespace: Development
  env_name: dev

server:
  filter:
    - validation
    - prometheus
  timeout: 5000
  admin:
    ip: 127.0.0.1
    port: 11941
    read_timeout: 3000
    write_timeout: 60000
  service:
    - name: trpc.moox.cloudnode.CloudNodeMgr
      port: 11401
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.cloudnode.Health
      ip: 127.0.0.1
      port: 11411
      network: tcp
      protocol: http_no_protocol
      timeout: 3000
    - name: trpc.moox.cloudnode.jobhistory.timer
      port: 11406
      network: "0 5 0 * * *?scheduler=cloudnodeJobHistorySchedule&disable=0&location=Asia/Shanghai&params="
      protocol: timer
      timeout: 60000
    - name: trpc.moox.cloudnode.metrics.timer
      port: 11413
      network: "*/30 * * * * *?params="
      protocol: timer
      timeout: 10000

plugins:
  prometheus:
    ip: 127.0.0.1
    port: 12941
    path: /metrics
    enablepush: false
  auth:
    validation:
      enable_error_log: true
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  log:
    default:
      - writer: console
        level: info
