global: #全局配置
  namespace: Development            #环境类型，分正式production和非正式development两种类型
  env_name: test                    #环境名称，非正式环境下多环境的名称

server:
  filter:
    - validation
    - cors
  timeout: 5000
  service:
      ######## Moox http网关接口 ########
    - name: trpc.moox.gateway.stdhttp
      #ip: 0.0.0.0
      port: 20103
      network: tcp  # 网络监听类型，tcp 或 udp
      protocol: http  # 应用层协议
      timeout: 5000  # 请求最长处理时间，单位毫秒
      filter:
        - ratelimit
        - authorize

      ######## 认证服务 ########
    - name: trpc.moox.server.AuthAPIhttp
      #ip: 0.0.0.0
      port: 20102
      network: tcp  # 网络监听类型，tcp 或 udp
      protocol: http  # 应用层协议 
      timeout: 1000  # 请求最长处理时间，单位毫秒
    - name: trpc.moox.server.AuthAPI
      #ip: 0.0.0.0
      port: 20001
      network: tcp
      protocol: trpc

      ######## API服务 ########
    - name: trpc.moox.api.stdhttp
      #ip: 0.0.0.0
      port: 20101
      network: tcp  # 网络监听类型，tcp 或 udp
      protocol: http  # 应用层协议
      timeout: 1000  # 请求最长处理时间，单位毫秒

      ######## DNS代理定时任务 ########
    - name: trpc.dnsproxy.timer
      port: 8001
      network: "*/10 * * * * *?scheduler=dnsproxySchedule&startAtOnce=1&params="
      protocol: timer
      timeout: 5000  #请求最长处理时间 单位 毫秒

client:
  filter:
    - validation
  service:
    - name: trpc.storage.metadata.MetaAdmin
      target: ip://127.0.0.1:18002
      network: tcp
      protocol: trpc
      timeout: 3000
    - name: trpc.storage.dbmanager.DBTableManager
      target: ip://127.0.0.1:18301
      network: tcp
      protocol: trpc
      timeout: 3000
    - name: trpc.storage.access.Access
      target: ip://127.0.0.1:18201
      network: tcp
      protocol: trpc
      timeout: 3000

      # 网关层转发的底层服务：trpc.storage.access.accesshttp
    - name: storage
      network: tcp
      protocol: http
      target: ip://127.0.0.1:19104
      timeout: 3000 #请求最长处理时间 
      disable_servicerouter: true

      # 网关层转发的底层服务：trpc.moox.server.AuthAPIhttp
    - name: auth
      network: tcp
      protocol: http
      target: ip://127.0.0.1:20102
      timeout: 3000 #请求最长处理时间 
      disable_servicerouter: true

      # 网关层转发的底层服务：trpc.storage.metadata.adminhttp
    - name: metadata
      network: tcp
      protocol: http
      target: ip://127.0.0.1:19102
      timeout: 3000 #请求最长处理时间 
      disable_servicerouter: true

      # 网关层转发的底层服务：trpc.storage.metadata.fieldhttp
    - name: field
      network: tcp
      protocol: http
      target: ip://127.0.0.1:19103
      timeout: 3000 #请求最长处理时间
      disable_servicerouter: true

    # 网关层转发的底层服务：trpc.storage.access.accesshttp
    - name: collector
      network: tcp
      protocol: http
      target: ip://127.0.0.1:20101
      timeout: 3000 #请求最长处理时间
      disable_servicerouter: true

plugins:
  auth:
    cors:
      apply_to_all_path:
        - insecure_allow_all
    validation:
      enable_error_log: true
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  log:
    default: 
      - writer: file                              #本地文件日志
        level: info                               #本地文件滚动日志的级别
        writer_config:                            #本地文件输出具体配置
          log_path: ./log                        #本地文件日志路径
          filename: trpc.log                      #本地文件日志文件名
          roll_type: size                         #文件滚动类型,size为按大小滚动
          max_age: 7                              #最大日志保留天数
          max_size: 10                            #本地文件滚动日志的大小 单位 MB
          max_backups: 10                         #最大日志文件数
          compress:  false                        #日志文件是否压缩
