global:
  namespace: Development
  env_name: development
server:
  service:
    - name: trpc.moox.gateway.route_refresh.timer
      ip: 127.0.0.1
      port: 11013
      network: "*/15 * * * * *"
      protocol: timer
      timeout: 10000
    - name: trpc.moox.gateway.metrics.timer
      ip: 127.0.0.1
      port: 11014
      network: "*/30 * * * * *"
      protocol: timer
      timeout: 10000
