global:
  namespace: Production
  env_name: prod

server:
  filter:
    - recovery
    - prometheus
  timeout: 5000
  service:
    - name: trpc.moox.archive.Health
      ip: 127.0.0.1
      port: 11416
      network: tcp
      protocol: http_no_protocol
      timeout: 3000
    - name: trpc.moox.archive.materialize.timer
      port: 11510
      network: "0 */10 * * * *?startAtOnce=1"
      protocol: timer
      timeout: 120000
    - name: trpc.moox.archive.cos_sync.timer
      port: 11511
      network: "0 0 * * * *?startAtOnce=1"
      protocol: timer
      timeout: 300000

plugins:
  metrics:
    prometheus:
      ip: 127.0.0.1
      port: 12916
      path: /metrics
      enablepush: false
