// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: data_node.proto

package storagepb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// DataNodeService defines service.
type DataNodeService interface {
	WriteFields(ctx context.Context, req *WriteFieldsReq) (*WriteFieldsRsp, error)

	ReadFields(ctx context.Context, req *ReadFieldsReq) (*ReadFieldsRsp, error)

	GetNodeState(ctx context.Context, req *GetNodeStateReq) (*GetNodeStateRsp, error)

	CleanupExpiredBuckets(ctx context.Context, req *CleanupExpiredBucketsReq) (*CleanupExpiredBucketsRsp, error)
}

func DataNodeService_WriteFields_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &WriteFieldsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataNodeService).WriteFields(ctx, reqbody.(*WriteFieldsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataNodeService_ReadFields_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReadFieldsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataNodeService).ReadFields(ctx, reqbody.(*ReadFieldsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataNodeService_GetNodeState_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetNodeStateReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataNodeService).GetNodeState(ctx, reqbody.(*GetNodeStateReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataNodeService_CleanupExpiredBuckets_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CleanupExpiredBucketsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataNodeService).CleanupExpiredBuckets(ctx, reqbody.(*CleanupExpiredBucketsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataNodeServer_ServiceDesc descriptor for server.RegisterService.
var DataNodeServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.storage.DataNode",
	HandlerType: ((*DataNodeService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.storage.DataNode/WriteFields",
			Func: DataNodeService_WriteFields_Handler,
		},
		{
			Name: "/trpc.moox.storage.DataNode/ReadFields",
			Func: DataNodeService_ReadFields_Handler,
		},
		{
			Name: "/trpc.moox.storage.DataNode/GetNodeState",
			Func: DataNodeService_GetNodeState_Handler,
		},
		{
			Name: "/trpc.moox.storage.DataNode/CleanupExpiredBuckets",
			Func: DataNodeService_CleanupExpiredBuckets_Handler,
		},
	},
}

// RegisterDataNodeService registers service.
func RegisterDataNodeService(s server.Service, svr DataNodeService) {
	if err := s.Register(&DataNodeServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("DataNode register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedDataNode struct{}

func (s *UnimplementedDataNode) WriteFields(ctx context.Context, req *WriteFieldsReq) (*WriteFieldsRsp, error) {
	return nil, errors.New("rpc WriteFields of service DataNode is not implemented")
}
func (s *UnimplementedDataNode) ReadFields(ctx context.Context, req *ReadFieldsReq) (*ReadFieldsRsp, error) {
	return nil, errors.New("rpc ReadFields of service DataNode is not implemented")
}
func (s *UnimplementedDataNode) GetNodeState(ctx context.Context, req *GetNodeStateReq) (*GetNodeStateRsp, error) {
	return nil, errors.New("rpc GetNodeState of service DataNode is not implemented")
}
func (s *UnimplementedDataNode) CleanupExpiredBuckets(ctx context.Context, req *CleanupExpiredBucketsReq) (*CleanupExpiredBucketsRsp, error) {
	return nil, errors.New("rpc CleanupExpiredBuckets of service DataNode is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// DataNodeClientProxy defines service client proxy
type DataNodeClientProxy interface {
	WriteFields(ctx context.Context, req *WriteFieldsReq, opts ...client.Option) (rsp *WriteFieldsRsp, err error)

	ReadFields(ctx context.Context, req *ReadFieldsReq, opts ...client.Option) (rsp *ReadFieldsRsp, err error)

	GetNodeState(ctx context.Context, req *GetNodeStateReq, opts ...client.Option) (rsp *GetNodeStateRsp, err error)

	CleanupExpiredBuckets(ctx context.Context, req *CleanupExpiredBucketsReq, opts ...client.Option) (rsp *CleanupExpiredBucketsRsp, err error)
}

type DataNodeClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDataNodeClientProxy = func(opts ...client.Option) DataNodeClientProxy {
	return &DataNodeClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DataNodeClientProxyImpl) WriteFields(ctx context.Context, req *WriteFieldsReq, opts ...client.Option) (*WriteFieldsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataNode/WriteFields")
	msg.WithCalleeServiceName(DataNodeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataNode")
	msg.WithCalleeMethod("WriteFields")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &WriteFieldsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataNodeClientProxyImpl) ReadFields(ctx context.Context, req *ReadFieldsReq, opts ...client.Option) (*ReadFieldsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataNode/ReadFields")
	msg.WithCalleeServiceName(DataNodeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataNode")
	msg.WithCalleeMethod("ReadFields")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReadFieldsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataNodeClientProxyImpl) GetNodeState(ctx context.Context, req *GetNodeStateReq, opts ...client.Option) (*GetNodeStateRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataNode/GetNodeState")
	msg.WithCalleeServiceName(DataNodeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataNode")
	msg.WithCalleeMethod("GetNodeState")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetNodeStateRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataNodeClientProxyImpl) CleanupExpiredBuckets(ctx context.Context, req *CleanupExpiredBucketsReq, opts ...client.Option) (*CleanupExpiredBucketsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataNode/CleanupExpiredBuckets")
	msg.WithCalleeServiceName(DataNodeServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataNode")
	msg.WithCalleeMethod("CleanupExpiredBuckets")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CleanupExpiredBucketsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
