// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: primary_store.proto

package storagepb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// PrimaryStoreService defines service.
type PrimaryStoreService interface {
	WriteFields(ctx context.Context, req *PrimaryWriteFieldsReq) (*PrimaryWriteFieldsRsp, error)

	ReadFields(ctx context.Context, req *PrimaryReadFieldsReq) (*PrimaryReadFieldsRsp, error)

	DeleteFields(ctx context.Context, req *PrimaryDeleteFieldsReq) (*PrimaryDeleteFieldsRsp, error)

	MergeTimeSeriesRows(ctx context.Context, req *MergeTimeSeriesRowsReq) (*MergeTimeSeriesRowsRsp, error)

	ReadTimeSeriesRows(ctx context.Context, req *ReadTimeSeriesRowsReq) (*ReadTimeSeriesRowsRsp, error)

	MergeRecordRows(ctx context.Context, req *MergeRecordRowsReq) (*MergeRecordRowsRsp, error)

	ReadRecordRows(ctx context.Context, req *ReadRecordRowsReq) (*ReadRecordRowsRsp, error)
}

func PrimaryStoreService_WriteFields_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PrimaryWriteFieldsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).WriteFields(ctx, reqbody.(*PrimaryWriteFieldsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PrimaryStoreService_ReadFields_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PrimaryReadFieldsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).ReadFields(ctx, reqbody.(*PrimaryReadFieldsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PrimaryStoreService_DeleteFields_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &PrimaryDeleteFieldsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).DeleteFields(ctx, reqbody.(*PrimaryDeleteFieldsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PrimaryStoreService_MergeTimeSeriesRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &MergeTimeSeriesRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).MergeTimeSeriesRows(ctx, reqbody.(*MergeTimeSeriesRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PrimaryStoreService_ReadTimeSeriesRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReadTimeSeriesRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).ReadTimeSeriesRows(ctx, reqbody.(*ReadTimeSeriesRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PrimaryStoreService_MergeRecordRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &MergeRecordRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).MergeRecordRows(ctx, reqbody.(*MergeRecordRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PrimaryStoreService_ReadRecordRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReadRecordRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PrimaryStoreService).ReadRecordRows(ctx, reqbody.(*ReadRecordRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// PrimaryStoreServer_ServiceDesc descriptor for server.RegisterService.
var PrimaryStoreServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.storage.PrimaryStore",
	HandlerType: ((*PrimaryStoreService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.storage.PrimaryStore/WriteFields",
			Func: PrimaryStoreService_WriteFields_Handler,
		},
		{
			Name: "/trpc.moox.storage.PrimaryStore/ReadFields",
			Func: PrimaryStoreService_ReadFields_Handler,
		},
		{
			Name: "/trpc.moox.storage.PrimaryStore/DeleteFields",
			Func: PrimaryStoreService_DeleteFields_Handler,
		},
		{
			Name: "/trpc.moox.storage.PrimaryStore/MergeTimeSeriesRows",
			Func: PrimaryStoreService_MergeTimeSeriesRows_Handler,
		},
		{
			Name: "/trpc.moox.storage.PrimaryStore/ReadTimeSeriesRows",
			Func: PrimaryStoreService_ReadTimeSeriesRows_Handler,
		},
		{
			Name: "/trpc.moox.storage.PrimaryStore/MergeRecordRows",
			Func: PrimaryStoreService_MergeRecordRows_Handler,
		},
		{
			Name: "/trpc.moox.storage.PrimaryStore/ReadRecordRows",
			Func: PrimaryStoreService_ReadRecordRows_Handler,
		},
	},
}

// RegisterPrimaryStoreService registers service.
func RegisterPrimaryStoreService(s server.Service, svr PrimaryStoreService) {
	if err := s.Register(&PrimaryStoreServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("PrimaryStore register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedPrimaryStore struct{}

func (s *UnimplementedPrimaryStore) WriteFields(ctx context.Context, req *PrimaryWriteFieldsReq) (*PrimaryWriteFieldsRsp, error) {
	return nil, errors.New("rpc WriteFields of service PrimaryStore is not implemented")
}
func (s *UnimplementedPrimaryStore) ReadFields(ctx context.Context, req *PrimaryReadFieldsReq) (*PrimaryReadFieldsRsp, error) {
	return nil, errors.New("rpc ReadFields of service PrimaryStore is not implemented")
}
func (s *UnimplementedPrimaryStore) DeleteFields(ctx context.Context, req *PrimaryDeleteFieldsReq) (*PrimaryDeleteFieldsRsp, error) {
	return nil, errors.New("rpc DeleteFields of service PrimaryStore is not implemented")
}
func (s *UnimplementedPrimaryStore) MergeTimeSeriesRows(ctx context.Context, req *MergeTimeSeriesRowsReq) (*MergeTimeSeriesRowsRsp, error) {
	return nil, errors.New("rpc MergeTimeSeriesRows of service PrimaryStore is not implemented")
}
func (s *UnimplementedPrimaryStore) ReadTimeSeriesRows(ctx context.Context, req *ReadTimeSeriesRowsReq) (*ReadTimeSeriesRowsRsp, error) {
	return nil, errors.New("rpc ReadTimeSeriesRows of service PrimaryStore is not implemented")
}
func (s *UnimplementedPrimaryStore) MergeRecordRows(ctx context.Context, req *MergeRecordRowsReq) (*MergeRecordRowsRsp, error) {
	return nil, errors.New("rpc MergeRecordRows of service PrimaryStore is not implemented")
}
func (s *UnimplementedPrimaryStore) ReadRecordRows(ctx context.Context, req *ReadRecordRowsReq) (*ReadRecordRowsRsp, error) {
	return nil, errors.New("rpc ReadRecordRows of service PrimaryStore is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// PrimaryStoreClientProxy defines service client proxy
type PrimaryStoreClientProxy interface {
	WriteFields(ctx context.Context, req *PrimaryWriteFieldsReq, opts ...client.Option) (rsp *PrimaryWriteFieldsRsp, err error)

	ReadFields(ctx context.Context, req *PrimaryReadFieldsReq, opts ...client.Option) (rsp *PrimaryReadFieldsRsp, err error)

	DeleteFields(ctx context.Context, req *PrimaryDeleteFieldsReq, opts ...client.Option) (rsp *PrimaryDeleteFieldsRsp, err error)

	MergeTimeSeriesRows(ctx context.Context, req *MergeTimeSeriesRowsReq, opts ...client.Option) (rsp *MergeTimeSeriesRowsRsp, err error)

	ReadTimeSeriesRows(ctx context.Context, req *ReadTimeSeriesRowsReq, opts ...client.Option) (rsp *ReadTimeSeriesRowsRsp, err error)

	MergeRecordRows(ctx context.Context, req *MergeRecordRowsReq, opts ...client.Option) (rsp *MergeRecordRowsRsp, err error)

	ReadRecordRows(ctx context.Context, req *ReadRecordRowsReq, opts ...client.Option) (rsp *ReadRecordRowsRsp, err error)
}

type PrimaryStoreClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewPrimaryStoreClientProxy = func(opts ...client.Option) PrimaryStoreClientProxy {
	return &PrimaryStoreClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *PrimaryStoreClientProxyImpl) WriteFields(ctx context.Context, req *PrimaryWriteFieldsReq, opts ...client.Option) (*PrimaryWriteFieldsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/WriteFields")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("WriteFields")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PrimaryWriteFieldsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PrimaryStoreClientProxyImpl) ReadFields(ctx context.Context, req *PrimaryReadFieldsReq, opts ...client.Option) (*PrimaryReadFieldsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/ReadFields")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("ReadFields")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PrimaryReadFieldsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PrimaryStoreClientProxyImpl) DeleteFields(ctx context.Context, req *PrimaryDeleteFieldsReq, opts ...client.Option) (*PrimaryDeleteFieldsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/DeleteFields")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("DeleteFields")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &PrimaryDeleteFieldsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PrimaryStoreClientProxyImpl) MergeTimeSeriesRows(ctx context.Context, req *MergeTimeSeriesRowsReq, opts ...client.Option) (*MergeTimeSeriesRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/MergeTimeSeriesRows")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("MergeTimeSeriesRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &MergeTimeSeriesRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PrimaryStoreClientProxyImpl) ReadTimeSeriesRows(ctx context.Context, req *ReadTimeSeriesRowsReq, opts ...client.Option) (*ReadTimeSeriesRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/ReadTimeSeriesRows")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("ReadTimeSeriesRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReadTimeSeriesRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PrimaryStoreClientProxyImpl) MergeRecordRows(ctx context.Context, req *MergeRecordRowsReq, opts ...client.Option) (*MergeRecordRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/MergeRecordRows")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("MergeRecordRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &MergeRecordRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PrimaryStoreClientProxyImpl) ReadRecordRows(ctx context.Context, req *ReadRecordRowsReq, opts ...client.Option) (*ReadRecordRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.PrimaryStore/ReadRecordRows")
	msg.WithCalleeServiceName(PrimaryStoreServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("PrimaryStore")
	msg.WithCalleeMethod("ReadRecordRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReadRecordRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
