// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: store.proto

package storagepb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// DataShardService defines service.
type DataShardService interface {
	// MergePrimaryRows MergePrimaryRows 将已完成路由的数据行写入在线主存。
	MergePrimaryRows(ctx context.Context, req *MergePrimaryRowsReq) (*MergePrimaryRowsRsp, error)
	// ReadPrimaryRows ReadPrimaryRows 从在线主存读取数据行。
	ReadPrimaryRows(ctx context.Context, req *ReadPrimaryRowsReq) (*ReadPrimaryRowsRsp, error)
	// ScanPrimaryRows ScanPrimaryRows 按目标数据集扫描在线主存，供内部 View rebuild 使用。
	ScanPrimaryRows(ctx context.Context, req *ScanPrimaryRowsReq) (*ScanPrimaryRowsRsp, error)

	DeletePrimaryRows(ctx context.Context, req *DeletePrimaryRowsReq) (*DeletePrimaryRowsRsp, error)
}

func DataShardService_MergePrimaryRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &MergePrimaryRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataShardService).MergePrimaryRows(ctx, reqbody.(*MergePrimaryRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataShardService_ReadPrimaryRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReadPrimaryRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataShardService).ReadPrimaryRows(ctx, reqbody.(*ReadPrimaryRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataShardService_ScanPrimaryRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ScanPrimaryRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataShardService).ScanPrimaryRows(ctx, reqbody.(*ScanPrimaryRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataShardService_DeletePrimaryRows_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeletePrimaryRowsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataShardService).DeletePrimaryRows(ctx, reqbody.(*DeletePrimaryRowsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataShardServer_ServiceDesc descriptor for server.RegisterService.
var DataShardServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.storage.DataShard",
	HandlerType: ((*DataShardService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.storage.DataShard/MergePrimaryRows",
			Func: DataShardService_MergePrimaryRows_Handler,
		},
		{
			Name: "/trpc.moox.storage.DataShard/ReadPrimaryRows",
			Func: DataShardService_ReadPrimaryRows_Handler,
		},
		{
			Name: "/trpc.moox.storage.DataShard/ScanPrimaryRows",
			Func: DataShardService_ScanPrimaryRows_Handler,
		},
		{
			Name: "/trpc.moox.storage.DataShard/DeletePrimaryRows",
			Func: DataShardService_DeletePrimaryRows_Handler,
		},
	},
}

// RegisterDataShardService registers service.
func RegisterDataShardService(s server.Service, svr DataShardService) {
	if err := s.Register(&DataShardServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("DataShard register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedDataShard struct{}

// MergePrimaryRows MergePrimaryRows 将已完成路由的数据行写入在线主存。
func (s *UnimplementedDataShard) MergePrimaryRows(ctx context.Context, req *MergePrimaryRowsReq) (*MergePrimaryRowsRsp, error) {
	return nil, errors.New("rpc MergePrimaryRows of service DataShard is not implemented")
}

// ReadPrimaryRows ReadPrimaryRows 从在线主存读取数据行。
func (s *UnimplementedDataShard) ReadPrimaryRows(ctx context.Context, req *ReadPrimaryRowsReq) (*ReadPrimaryRowsRsp, error) {
	return nil, errors.New("rpc ReadPrimaryRows of service DataShard is not implemented")
}

// ScanPrimaryRows ScanPrimaryRows 按目标数据集扫描在线主存，供内部 View rebuild 使用。
func (s *UnimplementedDataShard) ScanPrimaryRows(ctx context.Context, req *ScanPrimaryRowsReq) (*ScanPrimaryRowsRsp, error) {
	return nil, errors.New("rpc ScanPrimaryRows of service DataShard is not implemented")
}
func (s *UnimplementedDataShard) DeletePrimaryRows(ctx context.Context, req *DeletePrimaryRowsReq) (*DeletePrimaryRowsRsp, error) {
	return nil, errors.New("rpc DeletePrimaryRows of service DataShard is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// DataShardClientProxy defines service client proxy
type DataShardClientProxy interface {
	// MergePrimaryRows MergePrimaryRows 将已完成路由的数据行写入在线主存。
	MergePrimaryRows(ctx context.Context, req *MergePrimaryRowsReq, opts ...client.Option) (rsp *MergePrimaryRowsRsp, err error)
	// ReadPrimaryRows ReadPrimaryRows 从在线主存读取数据行。
	ReadPrimaryRows(ctx context.Context, req *ReadPrimaryRowsReq, opts ...client.Option) (rsp *ReadPrimaryRowsRsp, err error)
	// ScanPrimaryRows ScanPrimaryRows 按目标数据集扫描在线主存，供内部 View rebuild 使用。
	ScanPrimaryRows(ctx context.Context, req *ScanPrimaryRowsReq, opts ...client.Option) (rsp *ScanPrimaryRowsRsp, err error)

	DeletePrimaryRows(ctx context.Context, req *DeletePrimaryRowsReq, opts ...client.Option) (rsp *DeletePrimaryRowsRsp, err error)
}

type DataShardClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDataShardClientProxy = func(opts ...client.Option) DataShardClientProxy {
	return &DataShardClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DataShardClientProxyImpl) MergePrimaryRows(ctx context.Context, req *MergePrimaryRowsReq, opts ...client.Option) (*MergePrimaryRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataShard/MergePrimaryRows")
	msg.WithCalleeServiceName(DataShardServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataShard")
	msg.WithCalleeMethod("MergePrimaryRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &MergePrimaryRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataShardClientProxyImpl) ReadPrimaryRows(ctx context.Context, req *ReadPrimaryRowsReq, opts ...client.Option) (*ReadPrimaryRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataShard/ReadPrimaryRows")
	msg.WithCalleeServiceName(DataShardServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataShard")
	msg.WithCalleeMethod("ReadPrimaryRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReadPrimaryRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataShardClientProxyImpl) ScanPrimaryRows(ctx context.Context, req *ScanPrimaryRowsReq, opts ...client.Option) (*ScanPrimaryRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataShard/ScanPrimaryRows")
	msg.WithCalleeServiceName(DataShardServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataShard")
	msg.WithCalleeMethod("ScanPrimaryRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ScanPrimaryRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataShardClientProxyImpl) DeletePrimaryRows(ctx context.Context, req *DeletePrimaryRowsReq, opts ...client.Option) (*DeletePrimaryRowsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.storage.DataShard/DeletePrimaryRows")
	msg.WithCalleeServiceName(DataShardServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("storage")
	msg.WithCalleeService("DataShard")
	msg.WithCalleeMethod("DeletePrimaryRows")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeletePrimaryRowsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
