// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.28.3
// source: storagepb/storage_payloads.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RowsUpserted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DatasetId string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	SubjectId string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Frequency string                 `protobuf:"bytes,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	DataTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=data_time,json=dataTime,proto3" json:"data_time,omitempty"`
	Revision  uint64                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Rows      []byte                 `protobuf:"bytes,6,opt,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RowsUpserted) Reset() {
	*x = RowsUpserted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storagepb_storage_payloads_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowsUpserted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowsUpserted) ProtoMessage() {}

func (x *RowsUpserted) ProtoReflect() protoreflect.Message {
	mi := &file_storagepb_storage_payloads_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowsUpserted.ProtoReflect.Descriptor instead.
func (*RowsUpserted) Descriptor() ([]byte, []int) {
	return file_storagepb_storage_payloads_proto_rawDescGZIP(), []int{0}
}

func (x *RowsUpserted) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *RowsUpserted) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RowsUpserted) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *RowsUpserted) GetDataTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DataTime
	}
	return nil
}

func (x *RowsUpserted) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RowsUpserted) GetRows() []byte {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_storagepb_storage_payloads_proto protoreflect.FileDescriptor

var file_storagepb_storage_payloads_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x74, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x6f, 0x6f, 0x78, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x01, 0x0a,
	0x0c, 0x52, 0x6f, 0x77, 0x73, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f,
	0x77, 0x73, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x6f, 0x6f, 0x79, 0x61, 0x6e, 0x67, 0x2d, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x6d, 0x6f,
	0x6f, 0x78, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x70, 0x62, 0x3b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storagepb_storage_payloads_proto_rawDescOnce sync.Once
	file_storagepb_storage_payloads_proto_rawDescData = file_storagepb_storage_payloads_proto_rawDesc
)

func file_storagepb_storage_payloads_proto_rawDescGZIP() []byte {
	file_storagepb_storage_payloads_proto_rawDescOnce.Do(func() {
		file_storagepb_storage_payloads_proto_rawDescData = protoimpl.X.CompressGZIP(file_storagepb_storage_payloads_proto_rawDescData)
	})
	return file_storagepb_storage_payloads_proto_rawDescData
}

var file_storagepb_storage_payloads_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storagepb_storage_payloads_proto_goTypes = []interface{}{
	(*RowsUpserted)(nil),          // 0: trpc.moox.event.storage.RowsUpserted
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_storagepb_storage_payloads_proto_depIdxs = []int32{
	1, // 0: trpc.moox.event.storage.RowsUpserted.data_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_storagepb_storage_payloads_proto_init() }
func file_storagepb_storage_payloads_proto_init() {
	if File_storagepb_storage_payloads_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storagepb_storage_payloads_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowsUpserted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storagepb_storage_payloads_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storagepb_storage_payloads_proto_goTypes,
		DependencyIndexes: file_storagepb_storage_payloads_proto_depIdxs,
		MessageInfos:      file_storagepb_storage_payloads_proto_msgTypes,
	}.Build()
	File_storagepb_storage_payloads_proto = out.File
	file_storagepb_storage_payloads_proto_rawDesc = nil
	file_storagepb_storage_payloads_proto_goTypes = nil
	file_storagepb_storage_payloads_proto_depIdxs = nil
}
