// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: data.proto

package storagepb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// DataServiceService defines service.
type DataServiceService interface {
	UpsertRecords(ctx context.Context, req *UpsertRecordsReq) (*UpsertRecordsRsp, error)

	QueryRecords(ctx context.Context, req *QueryRecordsReq) (*QueryRecordsRsp, error)

	SetTimeSeries(ctx context.Context, req *SetTimeSeriesReq) (*SetTimeSeriesRsp, error)

	ScanTimeSeries(ctx context.Context, req *ScanTimeSeriesReq) (*ScanTimeSeriesRsp, error)

	SetFactorValues(ctx context.Context, req *SetFactorValuesReq) (*SetFactorValuesRsp, error)

	ScanFactorValues(ctx context.Context, req *ScanFactorValuesReq) (*ScanFactorValuesRsp, error)

	GetLatestSnapshot(ctx context.Context, req *GetLatestSnapshotReq) (*GetLatestSnapshotRsp, error)
}

func DataServiceService_UpsertRecords_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpsertRecordsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).UpsertRecords(ctx, reqbody.(*UpsertRecordsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataServiceService_QueryRecords_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryRecordsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).QueryRecords(ctx, reqbody.(*QueryRecordsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataServiceService_SetTimeSeries_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SetTimeSeriesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).SetTimeSeries(ctx, reqbody.(*SetTimeSeriesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataServiceService_ScanTimeSeries_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ScanTimeSeriesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).ScanTimeSeries(ctx, reqbody.(*ScanTimeSeriesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataServiceService_SetFactorValues_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SetFactorValuesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).SetFactorValues(ctx, reqbody.(*SetFactorValuesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataServiceService_ScanFactorValues_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ScanFactorValuesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).ScanFactorValues(ctx, reqbody.(*ScanFactorValuesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DataServiceService_GetLatestSnapshot_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetLatestSnapshotReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DataServiceService).GetLatestSnapshot(ctx, reqbody.(*GetLatestSnapshotReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DataServiceServer_ServiceDesc descriptor for server.RegisterService.
var DataServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.storage.data.DataService",
	HandlerType: ((*DataServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.storage.data.DataService/UpsertRecords",
			Func: DataServiceService_UpsertRecords_Handler,
		},
		{
			Name: "/trpc.storage.data.DataService/QueryRecords",
			Func: DataServiceService_QueryRecords_Handler,
		},
		{
			Name: "/trpc.storage.data.DataService/SetTimeSeries",
			Func: DataServiceService_SetTimeSeries_Handler,
		},
		{
			Name: "/trpc.storage.data.DataService/ScanTimeSeries",
			Func: DataServiceService_ScanTimeSeries_Handler,
		},
		{
			Name: "/trpc.storage.data.DataService/SetFactorValues",
			Func: DataServiceService_SetFactorValues_Handler,
		},
		{
			Name: "/trpc.storage.data.DataService/ScanFactorValues",
			Func: DataServiceService_ScanFactorValues_Handler,
		},
		{
			Name: "/trpc.storage.data.DataService/GetLatestSnapshot",
			Func: DataServiceService_GetLatestSnapshot_Handler,
		},
	},
}

// RegisterDataServiceService registers service.
func RegisterDataServiceService(s server.Service, svr DataServiceService) {
	if err := s.Register(&DataServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("DataService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedDataService struct{}

func (s *UnimplementedDataService) UpsertRecords(ctx context.Context, req *UpsertRecordsReq) (*UpsertRecordsRsp, error) {
	return nil, errors.New("rpc UpsertRecords of service DataService is not implemented")
}
func (s *UnimplementedDataService) QueryRecords(ctx context.Context, req *QueryRecordsReq) (*QueryRecordsRsp, error) {
	return nil, errors.New("rpc QueryRecords of service DataService is not implemented")
}
func (s *UnimplementedDataService) SetTimeSeries(ctx context.Context, req *SetTimeSeriesReq) (*SetTimeSeriesRsp, error) {
	return nil, errors.New("rpc SetTimeSeries of service DataService is not implemented")
}
func (s *UnimplementedDataService) ScanTimeSeries(ctx context.Context, req *ScanTimeSeriesReq) (*ScanTimeSeriesRsp, error) {
	return nil, errors.New("rpc ScanTimeSeries of service DataService is not implemented")
}
func (s *UnimplementedDataService) SetFactorValues(ctx context.Context, req *SetFactorValuesReq) (*SetFactorValuesRsp, error) {
	return nil, errors.New("rpc SetFactorValues of service DataService is not implemented")
}
func (s *UnimplementedDataService) ScanFactorValues(ctx context.Context, req *ScanFactorValuesReq) (*ScanFactorValuesRsp, error) {
	return nil, errors.New("rpc ScanFactorValues of service DataService is not implemented")
}
func (s *UnimplementedDataService) GetLatestSnapshot(ctx context.Context, req *GetLatestSnapshotReq) (*GetLatestSnapshotRsp, error) {
	return nil, errors.New("rpc GetLatestSnapshot of service DataService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// DataServiceClientProxy defines service client proxy
type DataServiceClientProxy interface {
	UpsertRecords(ctx context.Context, req *UpsertRecordsReq, opts ...client.Option) (rsp *UpsertRecordsRsp, err error)

	QueryRecords(ctx context.Context, req *QueryRecordsReq, opts ...client.Option) (rsp *QueryRecordsRsp, err error)

	SetTimeSeries(ctx context.Context, req *SetTimeSeriesReq, opts ...client.Option) (rsp *SetTimeSeriesRsp, err error)

	ScanTimeSeries(ctx context.Context, req *ScanTimeSeriesReq, opts ...client.Option) (rsp *ScanTimeSeriesRsp, err error)

	SetFactorValues(ctx context.Context, req *SetFactorValuesReq, opts ...client.Option) (rsp *SetFactorValuesRsp, err error)

	ScanFactorValues(ctx context.Context, req *ScanFactorValuesReq, opts ...client.Option) (rsp *ScanFactorValuesRsp, err error)

	GetLatestSnapshot(ctx context.Context, req *GetLatestSnapshotReq, opts ...client.Option) (rsp *GetLatestSnapshotRsp, err error)
}

type DataServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDataServiceClientProxy = func(opts ...client.Option) DataServiceClientProxy {
	return &DataServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DataServiceClientProxyImpl) UpsertRecords(ctx context.Context, req *UpsertRecordsReq, opts ...client.Option) (*UpsertRecordsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/UpsertRecords")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("UpsertRecords")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpsertRecordsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataServiceClientProxyImpl) QueryRecords(ctx context.Context, req *QueryRecordsReq, opts ...client.Option) (*QueryRecordsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/QueryRecords")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("QueryRecords")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryRecordsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataServiceClientProxyImpl) SetTimeSeries(ctx context.Context, req *SetTimeSeriesReq, opts ...client.Option) (*SetTimeSeriesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/SetTimeSeries")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("SetTimeSeries")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SetTimeSeriesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataServiceClientProxyImpl) ScanTimeSeries(ctx context.Context, req *ScanTimeSeriesReq, opts ...client.Option) (*ScanTimeSeriesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/ScanTimeSeries")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("ScanTimeSeries")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ScanTimeSeriesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataServiceClientProxyImpl) SetFactorValues(ctx context.Context, req *SetFactorValuesReq, opts ...client.Option) (*SetFactorValuesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/SetFactorValues")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("SetFactorValues")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SetFactorValuesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataServiceClientProxyImpl) ScanFactorValues(ctx context.Context, req *ScanFactorValuesReq, opts ...client.Option) (*ScanFactorValuesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/ScanFactorValues")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("ScanFactorValues")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ScanFactorValuesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DataServiceClientProxyImpl) GetLatestSnapshot(ctx context.Context, req *GetLatestSnapshotReq, opts ...client.Option) (*GetLatestSnapshotRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.storage.data.DataService/GetLatestSnapshot")
	msg.WithCalleeServiceName(DataServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("storage")
	msg.WithCalleeServer("data")
	msg.WithCalleeService("DataService")
	msg.WithCalleeMethod("GetLatestSnapshot")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetLatestSnapshotRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
