global:
  namespace: Development
  env_name: dev

server:
  filter:
    - validation
    - prometheus
  timeout: 5000
  admin:
    ip: 127.0.0.1
    port: 11944
    read_timeout: 3000
    write_timeout: 60000
  service:
    - name: trpc.moox.factor.FactorMgr
      port: 11404
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.factor.Health
      port: 11414
      network: tcp
      protocol: http_no_protocol
      timeout: 3000
    - name: trpc.moox.factor.reconcile.timer
      port: 11405
      network: "0 */10 * * * *?scheduler=factorReconcileSchedule&disable=1&params="
      protocol: timer
      timeout: 60000
    - name: trpc.moox.factor.metrics.timer
      port: 11414
      network: "*/30 * * * * *?params="
      protocol: timer
      timeout: 10000

plugins:
  metrics:
    prometheus:
      ip: 127.0.0.1
      port: 12944
      path: /metrics
      enablepush: false
  auth:
    validation:
      enable_error_log: true
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  log:
    default:
      - writer: console
        level: info
