// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: collect_service.proto

package mooxpb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// CollectMgrService defines service.
type CollectMgrService interface {
	// GetTaskRuleList ----- 任务规则 -----
	GetTaskRuleList(ctx context.Context, req *GetTaskRuleListReq) (*GetTaskRuleListRsp, error)

	GetTaskRuleDetail(ctx context.Context, req *GetTaskRuleDetailReq) (*GetTaskRuleDetailRsp, error)

	CreateTaskRule(ctx context.Context, req *CreateTaskRuleReq) (*CreateTaskRuleRsp, error)

	UpdateTaskRule(ctx context.Context, req *UpdateTaskRuleReq) (*UpdateTaskRuleRsp, error)

	DisableTaskRule(ctx context.Context, req *DisableTaskRuleReq) (*DisableTaskRuleRsp, error)
	// GetTaskInstanceList ----- 任务实例 -----
	GetTaskInstanceList(ctx context.Context, req *GetTaskInstanceListReq) (*GetTaskInstanceListRsp, error)

	GetTaskInstanceListCache(ctx context.Context, req *GetTaskInstanceListCacheReq) (*GetTaskInstanceListCacheRsp, error)

	GetTaskInstanceDetail(ctx context.Context, req *GetTaskInstanceDetailReq) (*GetTaskInstanceDetailRsp, error)

	CreateTaskInstance(ctx context.Context, req *CreateTaskInstanceReq) (*CreateTaskInstanceRsp, error)

	UpdateTaskInstance(ctx context.Context, req *UpdateTaskInstanceReq) (*UpdateTaskInstanceRsp, error)

	DeleteTaskInstance(ctx context.Context, req *DeleteTaskInstanceReq) (*DeleteTaskInstanceRsp, error)

	StartTaskInstance(ctx context.Context, req *StartTaskInstanceReq) (*StartTaskInstanceRsp, error)

	StopTaskInstance(ctx context.Context, req *StopTaskInstanceReq) (*StopTaskInstanceRsp, error)

	ReportTaskStatus(ctx context.Context, req *ReportInstanceStatusReq) (*ReportInstanceStatusRsp, error)

	InvalidateTaskInstance(ctx context.Context, req *InvalidateTaskInstanceReq) (*InvalidateTaskInstanceRsp, error)
	// GetDataTypeConfigs ----- 数据类型配置 -----
	GetDataTypeConfigs(ctx context.Context, req *GetDataTypeConfigsReq) (*GetDataTypeConfigsRsp, error)

	GetDataTypeConfigWithFields(ctx context.Context, req *GetDataTypeConfigWithFieldsReq) (*GetDataTypeConfigWithFieldsRsp, error)
	// RecalculateAllTaskInstances ----- 任务规划器 -----
	RecalculateAllTaskInstances(ctx context.Context, req *RecalculateAllTaskInstancesReq) (*RecalculateAllTaskInstancesRsp, error)
}

func CollectMgrService_GetTaskRuleList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetTaskRuleListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetTaskRuleList(ctx, reqbody.(*GetTaskRuleListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_GetTaskRuleDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetTaskRuleDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetTaskRuleDetail(ctx, reqbody.(*GetTaskRuleDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_CreateTaskRule_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateTaskRuleReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).CreateTaskRule(ctx, reqbody.(*CreateTaskRuleReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_UpdateTaskRule_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateTaskRuleReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).UpdateTaskRule(ctx, reqbody.(*UpdateTaskRuleReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_DisableTaskRule_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DisableTaskRuleReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).DisableTaskRule(ctx, reqbody.(*DisableTaskRuleReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_GetTaskInstanceList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetTaskInstanceListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetTaskInstanceList(ctx, reqbody.(*GetTaskInstanceListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_GetTaskInstanceListCache_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetTaskInstanceListCacheReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetTaskInstanceListCache(ctx, reqbody.(*GetTaskInstanceListCacheReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_GetTaskInstanceDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetTaskInstanceDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetTaskInstanceDetail(ctx, reqbody.(*GetTaskInstanceDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_CreateTaskInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateTaskInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).CreateTaskInstance(ctx, reqbody.(*CreateTaskInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_UpdateTaskInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateTaskInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).UpdateTaskInstance(ctx, reqbody.(*UpdateTaskInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_DeleteTaskInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteTaskInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).DeleteTaskInstance(ctx, reqbody.(*DeleteTaskInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_StartTaskInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &StartTaskInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).StartTaskInstance(ctx, reqbody.(*StartTaskInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_StopTaskInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &StopTaskInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).StopTaskInstance(ctx, reqbody.(*StopTaskInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_ReportTaskStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReportInstanceStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).ReportTaskStatus(ctx, reqbody.(*ReportInstanceStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_InvalidateTaskInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &InvalidateTaskInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).InvalidateTaskInstance(ctx, reqbody.(*InvalidateTaskInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_GetDataTypeConfigs_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetDataTypeConfigsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetDataTypeConfigs(ctx, reqbody.(*GetDataTypeConfigsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_GetDataTypeConfigWithFields_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetDataTypeConfigWithFieldsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).GetDataTypeConfigWithFields(ctx, reqbody.(*GetDataTypeConfigWithFieldsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CollectMgrService_RecalculateAllTaskInstances_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RecalculateAllTaskInstancesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CollectMgrService).RecalculateAllTaskInstances(ctx, reqbody.(*RecalculateAllTaskInstancesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CollectMgrServer_ServiceDesc descriptor for server.RegisterService.
var CollectMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.collect.CollectMgr",
	HandlerType: ((*CollectMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.collect.CollectMgr/GetTaskRuleList",
			Func: CollectMgrService_GetTaskRuleList_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/GetTaskRuleDetail",
			Func: CollectMgrService_GetTaskRuleDetail_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/CreateTaskRule",
			Func: CollectMgrService_CreateTaskRule_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/UpdateTaskRule",
			Func: CollectMgrService_UpdateTaskRule_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/DisableTaskRule",
			Func: CollectMgrService_DisableTaskRule_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/GetTaskInstanceList",
			Func: CollectMgrService_GetTaskInstanceList_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/GetTaskInstanceListCache",
			Func: CollectMgrService_GetTaskInstanceListCache_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/GetTaskInstanceDetail",
			Func: CollectMgrService_GetTaskInstanceDetail_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/CreateTaskInstance",
			Func: CollectMgrService_CreateTaskInstance_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/UpdateTaskInstance",
			Func: CollectMgrService_UpdateTaskInstance_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/DeleteTaskInstance",
			Func: CollectMgrService_DeleteTaskInstance_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/StartTaskInstance",
			Func: CollectMgrService_StartTaskInstance_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/StopTaskInstance",
			Func: CollectMgrService_StopTaskInstance_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/ReportTaskStatus",
			Func: CollectMgrService_ReportTaskStatus_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/InvalidateTaskInstance",
			Func: CollectMgrService_InvalidateTaskInstance_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/GetDataTypeConfigs",
			Func: CollectMgrService_GetDataTypeConfigs_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/GetDataTypeConfigWithFields",
			Func: CollectMgrService_GetDataTypeConfigWithFields_Handler,
		},
		{
			Name: "/trpc.moox.collect.CollectMgr/RecalculateAllTaskInstances",
			Func: CollectMgrService_RecalculateAllTaskInstances_Handler,
		},
	},
}

// RegisterCollectMgrService registers service.
func RegisterCollectMgrService(s server.Service, svr CollectMgrService) {
	if err := s.Register(&CollectMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("CollectMgr register error:%v", err))
	}
}

// CloudNodeMgrService defines service.
type CloudNodeMgrService interface {
	// GetNodeList ----- 节点 -----
	GetNodeList(ctx context.Context, req *GetNodeListReq) (*GetNodeListRsp, error)

	GetNodeDetail(ctx context.Context, req *GetNodeDetailReq) (*GetNodeDetailRsp, error)

	GetSCFDeployInfo(ctx context.Context, req *GetSCFDeployInfoReq) (*GetSCFDeployInfoRsp, error)

	UpdateNode(ctx context.Context, req *UpdateNodeReq) (*UpdateNodeRsp, error)

	DeleteNode(ctx context.Context, req *DeleteNodeReq) (*DeleteNodeRsp, error)

	InvokeFunction(ctx context.Context, req *InvokeFunctionReq) (*InvokeFunctionRsp, error)

	UpdateNodeFunction(ctx context.Context, req *UpdateNodeFunctionReq) (*UpdateNodeFunctionRsp, error)
	// BatchCreateNodes ----- 批量操作 -----
	BatchCreateNodes(ctx context.Context, req *BatchCreateNodesReq) (*BatchOperationRsp, error)

	BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq) (*BatchOperationRsp, error)

	BatchDeployNodes(ctx context.Context, req *BatchDeployNodesReq) (*BatchOperationRsp, error)
	// ListCloudAccounts ----- 云账户 -----
	ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq) (*ListCloudAccountsRsp, error)

	GetCloudAccount(ctx context.Context, req *GetCloudAccountReq) (*GetCloudAccountRsp, error)

	CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq) (*CreateCloudAccountRsp, error)

	UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq) (*UpdateCloudAccountRsp, error)

	DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq) (*DeleteCloudAccountRsp, error)

	GetCOSAccountInfo(ctx context.Context, req *GetCOSAccountInfoReq) (*GetCOSAccountInfoRsp, error)
	// ListCloudRegions ----- 云地区 -----
	ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq) (*ListCloudRegionsRsp, error)
	// GetPackageList ----- 代码包 -----
	GetPackageList(ctx context.Context, req *GetPackageListReq) (*GetPackageListRsp, error)

	GetPackageDetail(ctx context.Context, req *GetPackageDetailReq) (*GetPackageDetailRsp, error)

	DeletePackage(ctx context.Context, req *DeletePackageReq) (*DeletePackageRsp, error)

	GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq) (*GetPackageDownloadURLRsp, error)

	GetPackageOptions(ctx context.Context, req *GetPackageOptionsReq) (*GetPackageOptionsRsp, error)
	// ReportHeartbeat ----- 心跳 -----
	ReportHeartbeat(ctx context.Context, req *ReportHeartbeatReq) (*ReportHeartbeatRsp, error)
}

func CloudNodeMgrService_GetNodeList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetNodeListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetNodeList(ctx, reqbody.(*GetNodeListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetNodeDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetNodeDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetNodeDetail(ctx, reqbody.(*GetNodeDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetSCFDeployInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetSCFDeployInfoReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetSCFDeployInfo(ctx, reqbody.(*GetSCFDeployInfoReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_UpdateNode_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateNodeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).UpdateNode(ctx, reqbody.(*UpdateNodeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_DeleteNode_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteNodeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).DeleteNode(ctx, reqbody.(*DeleteNodeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_InvokeFunction_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &InvokeFunctionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).InvokeFunction(ctx, reqbody.(*InvokeFunctionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_UpdateNodeFunction_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateNodeFunctionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).UpdateNodeFunction(ctx, reqbody.(*UpdateNodeFunctionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_BatchCreateNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchCreateNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).BatchCreateNodes(ctx, reqbody.(*BatchCreateNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_BatchDeleteNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchDeleteNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).BatchDeleteNodes(ctx, reqbody.(*BatchDeleteNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_BatchDeployNodes_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &BatchDeployNodesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).BatchDeployNodes(ctx, reqbody.(*BatchDeployNodesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ListCloudAccounts_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListCloudAccountsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ListCloudAccounts(ctx, reqbody.(*ListCloudAccountsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetCloudAccount(ctx, reqbody.(*GetCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_CreateCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).CreateCloudAccount(ctx, reqbody.(*CreateCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_UpdateCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).UpdateCloudAccount(ctx, reqbody.(*UpdateCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_DeleteCloudAccount_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteCloudAccountReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).DeleteCloudAccount(ctx, reqbody.(*DeleteCloudAccountReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetCOSAccountInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetCOSAccountInfoReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetCOSAccountInfo(ctx, reqbody.(*GetCOSAccountInfoReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ListCloudRegions_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListCloudRegionsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ListCloudRegions(ctx, reqbody.(*ListCloudRegionsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageList(ctx, reqbody.(*GetPackageListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageDetail(ctx, reqbody.(*GetPackageDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_DeletePackage_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeletePackageReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).DeletePackage(ctx, reqbody.(*DeletePackageReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageDownloadURL_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageDownloadURLReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageDownloadURL(ctx, reqbody.(*GetPackageDownloadURLReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_GetPackageOptions_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPackageOptionsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).GetPackageOptions(ctx, reqbody.(*GetPackageOptionsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CloudNodeMgrService_ReportHeartbeat_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ReportHeartbeatReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CloudNodeMgrService).ReportHeartbeat(ctx, reqbody.(*ReportHeartbeatReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CloudNodeMgrServer_ServiceDesc descriptor for server.RegisterService.
var CloudNodeMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.collect.CloudNodeMgr",
	HandlerType: ((*CloudNodeMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetNodeList",
			Func: CloudNodeMgrService_GetNodeList_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetNodeDetail",
			Func: CloudNodeMgrService_GetNodeDetail_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetSCFDeployInfo",
			Func: CloudNodeMgrService_GetSCFDeployInfo_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/UpdateNode",
			Func: CloudNodeMgrService_UpdateNode_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/DeleteNode",
			Func: CloudNodeMgrService_DeleteNode_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/InvokeFunction",
			Func: CloudNodeMgrService_InvokeFunction_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/UpdateNodeFunction",
			Func: CloudNodeMgrService_UpdateNodeFunction_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/BatchCreateNodes",
			Func: CloudNodeMgrService_BatchCreateNodes_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/BatchDeleteNodes",
			Func: CloudNodeMgrService_BatchDeleteNodes_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/BatchDeployNodes",
			Func: CloudNodeMgrService_BatchDeployNodes_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/ListCloudAccounts",
			Func: CloudNodeMgrService_ListCloudAccounts_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetCloudAccount",
			Func: CloudNodeMgrService_GetCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/CreateCloudAccount",
			Func: CloudNodeMgrService_CreateCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/UpdateCloudAccount",
			Func: CloudNodeMgrService_UpdateCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/DeleteCloudAccount",
			Func: CloudNodeMgrService_DeleteCloudAccount_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetCOSAccountInfo",
			Func: CloudNodeMgrService_GetCOSAccountInfo_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/ListCloudRegions",
			Func: CloudNodeMgrService_ListCloudRegions_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetPackageList",
			Func: CloudNodeMgrService_GetPackageList_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetPackageDetail",
			Func: CloudNodeMgrService_GetPackageDetail_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/DeletePackage",
			Func: CloudNodeMgrService_DeletePackage_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetPackageDownloadURL",
			Func: CloudNodeMgrService_GetPackageDownloadURL_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/GetPackageOptions",
			Func: CloudNodeMgrService_GetPackageOptions_Handler,
		},
		{
			Name: "/trpc.moox.collect.CloudNodeMgr/ReportHeartbeat",
			Func: CloudNodeMgrService_ReportHeartbeat_Handler,
		},
	},
}

// RegisterCloudNodeMgrService registers service.
func RegisterCloudNodeMgrService(s server.Service, svr CloudNodeMgrService) {
	if err := s.Register(&CloudNodeMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("CloudNodeMgr register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedCollectMgr struct{}

// GetTaskRuleList ----- 任务规则 -----
func (s *UnimplementedCollectMgr) GetTaskRuleList(ctx context.Context, req *GetTaskRuleListReq) (*GetTaskRuleListRsp, error) {
	return nil, errors.New("rpc GetTaskRuleList of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) GetTaskRuleDetail(ctx context.Context, req *GetTaskRuleDetailReq) (*GetTaskRuleDetailRsp, error) {
	return nil, errors.New("rpc GetTaskRuleDetail of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) CreateTaskRule(ctx context.Context, req *CreateTaskRuleReq) (*CreateTaskRuleRsp, error) {
	return nil, errors.New("rpc CreateTaskRule of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) UpdateTaskRule(ctx context.Context, req *UpdateTaskRuleReq) (*UpdateTaskRuleRsp, error) {
	return nil, errors.New("rpc UpdateTaskRule of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) DisableTaskRule(ctx context.Context, req *DisableTaskRuleReq) (*DisableTaskRuleRsp, error) {
	return nil, errors.New("rpc DisableTaskRule of service CollectMgr is not implemented")
}

// GetTaskInstanceList ----- 任务实例 -----
func (s *UnimplementedCollectMgr) GetTaskInstanceList(ctx context.Context, req *GetTaskInstanceListReq) (*GetTaskInstanceListRsp, error) {
	return nil, errors.New("rpc GetTaskInstanceList of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) GetTaskInstanceListCache(ctx context.Context, req *GetTaskInstanceListCacheReq) (*GetTaskInstanceListCacheRsp, error) {
	return nil, errors.New("rpc GetTaskInstanceListCache of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) GetTaskInstanceDetail(ctx context.Context, req *GetTaskInstanceDetailReq) (*GetTaskInstanceDetailRsp, error) {
	return nil, errors.New("rpc GetTaskInstanceDetail of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) CreateTaskInstance(ctx context.Context, req *CreateTaskInstanceReq) (*CreateTaskInstanceRsp, error) {
	return nil, errors.New("rpc CreateTaskInstance of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) UpdateTaskInstance(ctx context.Context, req *UpdateTaskInstanceReq) (*UpdateTaskInstanceRsp, error) {
	return nil, errors.New("rpc UpdateTaskInstance of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) DeleteTaskInstance(ctx context.Context, req *DeleteTaskInstanceReq) (*DeleteTaskInstanceRsp, error) {
	return nil, errors.New("rpc DeleteTaskInstance of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) StartTaskInstance(ctx context.Context, req *StartTaskInstanceReq) (*StartTaskInstanceRsp, error) {
	return nil, errors.New("rpc StartTaskInstance of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) StopTaskInstance(ctx context.Context, req *StopTaskInstanceReq) (*StopTaskInstanceRsp, error) {
	return nil, errors.New("rpc StopTaskInstance of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) ReportTaskStatus(ctx context.Context, req *ReportInstanceStatusReq) (*ReportInstanceStatusRsp, error) {
	return nil, errors.New("rpc ReportTaskStatus of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) InvalidateTaskInstance(ctx context.Context, req *InvalidateTaskInstanceReq) (*InvalidateTaskInstanceRsp, error) {
	return nil, errors.New("rpc InvalidateTaskInstance of service CollectMgr is not implemented")
}

// GetDataTypeConfigs ----- 数据类型配置 -----
func (s *UnimplementedCollectMgr) GetDataTypeConfigs(ctx context.Context, req *GetDataTypeConfigsReq) (*GetDataTypeConfigsRsp, error) {
	return nil, errors.New("rpc GetDataTypeConfigs of service CollectMgr is not implemented")
}
func (s *UnimplementedCollectMgr) GetDataTypeConfigWithFields(ctx context.Context, req *GetDataTypeConfigWithFieldsReq) (*GetDataTypeConfigWithFieldsRsp, error) {
	return nil, errors.New("rpc GetDataTypeConfigWithFields of service CollectMgr is not implemented")
}

// RecalculateAllTaskInstances ----- 任务规划器 -----
func (s *UnimplementedCollectMgr) RecalculateAllTaskInstances(ctx context.Context, req *RecalculateAllTaskInstancesReq) (*RecalculateAllTaskInstancesRsp, error) {
	return nil, errors.New("rpc RecalculateAllTaskInstances of service CollectMgr is not implemented")
}

type UnimplementedCloudNodeMgr struct{}

// GetNodeList ----- 节点 -----
func (s *UnimplementedCloudNodeMgr) GetNodeList(ctx context.Context, req *GetNodeListReq) (*GetNodeListRsp, error) {
	return nil, errors.New("rpc GetNodeList of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetNodeDetail(ctx context.Context, req *GetNodeDetailReq) (*GetNodeDetailRsp, error) {
	return nil, errors.New("rpc GetNodeDetail of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetSCFDeployInfo(ctx context.Context, req *GetSCFDeployInfoReq) (*GetSCFDeployInfoRsp, error) {
	return nil, errors.New("rpc GetSCFDeployInfo of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) UpdateNode(ctx context.Context, req *UpdateNodeReq) (*UpdateNodeRsp, error) {
	return nil, errors.New("rpc UpdateNode of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) DeleteNode(ctx context.Context, req *DeleteNodeReq) (*DeleteNodeRsp, error) {
	return nil, errors.New("rpc DeleteNode of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) InvokeFunction(ctx context.Context, req *InvokeFunctionReq) (*InvokeFunctionRsp, error) {
	return nil, errors.New("rpc InvokeFunction of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) UpdateNodeFunction(ctx context.Context, req *UpdateNodeFunctionReq) (*UpdateNodeFunctionRsp, error) {
	return nil, errors.New("rpc UpdateNodeFunction of service CloudNodeMgr is not implemented")
}

// BatchCreateNodes ----- 批量操作 -----
func (s *UnimplementedCloudNodeMgr) BatchCreateNodes(ctx context.Context, req *BatchCreateNodesReq) (*BatchOperationRsp, error) {
	return nil, errors.New("rpc BatchCreateNodes of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq) (*BatchOperationRsp, error) {
	return nil, errors.New("rpc BatchDeleteNodes of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) BatchDeployNodes(ctx context.Context, req *BatchDeployNodesReq) (*BatchOperationRsp, error) {
	return nil, errors.New("rpc BatchDeployNodes of service CloudNodeMgr is not implemented")
}

// ListCloudAccounts ----- 云账户 -----
func (s *UnimplementedCloudNodeMgr) ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq) (*ListCloudAccountsRsp, error) {
	return nil, errors.New("rpc ListCloudAccounts of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetCloudAccount(ctx context.Context, req *GetCloudAccountReq) (*GetCloudAccountRsp, error) {
	return nil, errors.New("rpc GetCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq) (*CreateCloudAccountRsp, error) {
	return nil, errors.New("rpc CreateCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq) (*UpdateCloudAccountRsp, error) {
	return nil, errors.New("rpc UpdateCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq) (*DeleteCloudAccountRsp, error) {
	return nil, errors.New("rpc DeleteCloudAccount of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetCOSAccountInfo(ctx context.Context, req *GetCOSAccountInfoReq) (*GetCOSAccountInfoRsp, error) {
	return nil, errors.New("rpc GetCOSAccountInfo of service CloudNodeMgr is not implemented")
}

// ListCloudRegions ----- 云地区 -----
func (s *UnimplementedCloudNodeMgr) ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq) (*ListCloudRegionsRsp, error) {
	return nil, errors.New("rpc ListCloudRegions of service CloudNodeMgr is not implemented")
}

// GetPackageList ----- 代码包 -----
func (s *UnimplementedCloudNodeMgr) GetPackageList(ctx context.Context, req *GetPackageListReq) (*GetPackageListRsp, error) {
	return nil, errors.New("rpc GetPackageList of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetPackageDetail(ctx context.Context, req *GetPackageDetailReq) (*GetPackageDetailRsp, error) {
	return nil, errors.New("rpc GetPackageDetail of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) DeletePackage(ctx context.Context, req *DeletePackageReq) (*DeletePackageRsp, error) {
	return nil, errors.New("rpc DeletePackage of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq) (*GetPackageDownloadURLRsp, error) {
	return nil, errors.New("rpc GetPackageDownloadURL of service CloudNodeMgr is not implemented")
}
func (s *UnimplementedCloudNodeMgr) GetPackageOptions(ctx context.Context, req *GetPackageOptionsReq) (*GetPackageOptionsRsp, error) {
	return nil, errors.New("rpc GetPackageOptions of service CloudNodeMgr is not implemented")
}

// ReportHeartbeat ----- 心跳 -----
func (s *UnimplementedCloudNodeMgr) ReportHeartbeat(ctx context.Context, req *ReportHeartbeatReq) (*ReportHeartbeatRsp, error) {
	return nil, errors.New("rpc ReportHeartbeat of service CloudNodeMgr is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// CollectMgrClientProxy defines service client proxy
type CollectMgrClientProxy interface {
	// GetTaskRuleList ----- 任务规则 -----
	GetTaskRuleList(ctx context.Context, req *GetTaskRuleListReq, opts ...client.Option) (rsp *GetTaskRuleListRsp, err error)

	GetTaskRuleDetail(ctx context.Context, req *GetTaskRuleDetailReq, opts ...client.Option) (rsp *GetTaskRuleDetailRsp, err error)

	CreateTaskRule(ctx context.Context, req *CreateTaskRuleReq, opts ...client.Option) (rsp *CreateTaskRuleRsp, err error)

	UpdateTaskRule(ctx context.Context, req *UpdateTaskRuleReq, opts ...client.Option) (rsp *UpdateTaskRuleRsp, err error)

	DisableTaskRule(ctx context.Context, req *DisableTaskRuleReq, opts ...client.Option) (rsp *DisableTaskRuleRsp, err error)
	// GetTaskInstanceList ----- 任务实例 -----
	GetTaskInstanceList(ctx context.Context, req *GetTaskInstanceListReq, opts ...client.Option) (rsp *GetTaskInstanceListRsp, err error)

	GetTaskInstanceListCache(ctx context.Context, req *GetTaskInstanceListCacheReq, opts ...client.Option) (rsp *GetTaskInstanceListCacheRsp, err error)

	GetTaskInstanceDetail(ctx context.Context, req *GetTaskInstanceDetailReq, opts ...client.Option) (rsp *GetTaskInstanceDetailRsp, err error)

	CreateTaskInstance(ctx context.Context, req *CreateTaskInstanceReq, opts ...client.Option) (rsp *CreateTaskInstanceRsp, err error)

	UpdateTaskInstance(ctx context.Context, req *UpdateTaskInstanceReq, opts ...client.Option) (rsp *UpdateTaskInstanceRsp, err error)

	DeleteTaskInstance(ctx context.Context, req *DeleteTaskInstanceReq, opts ...client.Option) (rsp *DeleteTaskInstanceRsp, err error)

	StartTaskInstance(ctx context.Context, req *StartTaskInstanceReq, opts ...client.Option) (rsp *StartTaskInstanceRsp, err error)

	StopTaskInstance(ctx context.Context, req *StopTaskInstanceReq, opts ...client.Option) (rsp *StopTaskInstanceRsp, err error)

	ReportTaskStatus(ctx context.Context, req *ReportInstanceStatusReq, opts ...client.Option) (rsp *ReportInstanceStatusRsp, err error)

	InvalidateTaskInstance(ctx context.Context, req *InvalidateTaskInstanceReq, opts ...client.Option) (rsp *InvalidateTaskInstanceRsp, err error)
	// GetDataTypeConfigs ----- 数据类型配置 -----
	GetDataTypeConfigs(ctx context.Context, req *GetDataTypeConfigsReq, opts ...client.Option) (rsp *GetDataTypeConfigsRsp, err error)

	GetDataTypeConfigWithFields(ctx context.Context, req *GetDataTypeConfigWithFieldsReq, opts ...client.Option) (rsp *GetDataTypeConfigWithFieldsRsp, err error)
	// RecalculateAllTaskInstances ----- 任务规划器 -----
	RecalculateAllTaskInstances(ctx context.Context, req *RecalculateAllTaskInstancesReq, opts ...client.Option) (rsp *RecalculateAllTaskInstancesRsp, err error)
}

type CollectMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCollectMgrClientProxy = func(opts ...client.Option) CollectMgrClientProxy {
	return &CollectMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CollectMgrClientProxyImpl) GetTaskRuleList(ctx context.Context, req *GetTaskRuleListReq, opts ...client.Option) (*GetTaskRuleListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetTaskRuleList")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetTaskRuleList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetTaskRuleListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) GetTaskRuleDetail(ctx context.Context, req *GetTaskRuleDetailReq, opts ...client.Option) (*GetTaskRuleDetailRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetTaskRuleDetail")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetTaskRuleDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetTaskRuleDetailRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) CreateTaskRule(ctx context.Context, req *CreateTaskRuleReq, opts ...client.Option) (*CreateTaskRuleRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/CreateTaskRule")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("CreateTaskRule")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateTaskRuleRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) UpdateTaskRule(ctx context.Context, req *UpdateTaskRuleReq, opts ...client.Option) (*UpdateTaskRuleRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/UpdateTaskRule")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("UpdateTaskRule")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateTaskRuleRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) DisableTaskRule(ctx context.Context, req *DisableTaskRuleReq, opts ...client.Option) (*DisableTaskRuleRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/DisableTaskRule")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("DisableTaskRule")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DisableTaskRuleRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) GetTaskInstanceList(ctx context.Context, req *GetTaskInstanceListReq, opts ...client.Option) (*GetTaskInstanceListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetTaskInstanceList")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetTaskInstanceList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetTaskInstanceListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) GetTaskInstanceListCache(ctx context.Context, req *GetTaskInstanceListCacheReq, opts ...client.Option) (*GetTaskInstanceListCacheRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetTaskInstanceListCache")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetTaskInstanceListCache")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetTaskInstanceListCacheRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) GetTaskInstanceDetail(ctx context.Context, req *GetTaskInstanceDetailReq, opts ...client.Option) (*GetTaskInstanceDetailRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetTaskInstanceDetail")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetTaskInstanceDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetTaskInstanceDetailRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) CreateTaskInstance(ctx context.Context, req *CreateTaskInstanceReq, opts ...client.Option) (*CreateTaskInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/CreateTaskInstance")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("CreateTaskInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateTaskInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) UpdateTaskInstance(ctx context.Context, req *UpdateTaskInstanceReq, opts ...client.Option) (*UpdateTaskInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/UpdateTaskInstance")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("UpdateTaskInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateTaskInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) DeleteTaskInstance(ctx context.Context, req *DeleteTaskInstanceReq, opts ...client.Option) (*DeleteTaskInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/DeleteTaskInstance")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("DeleteTaskInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteTaskInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) StartTaskInstance(ctx context.Context, req *StartTaskInstanceReq, opts ...client.Option) (*StartTaskInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/StartTaskInstance")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("StartTaskInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &StartTaskInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) StopTaskInstance(ctx context.Context, req *StopTaskInstanceReq, opts ...client.Option) (*StopTaskInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/StopTaskInstance")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("StopTaskInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &StopTaskInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) ReportTaskStatus(ctx context.Context, req *ReportInstanceStatusReq, opts ...client.Option) (*ReportInstanceStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/ReportTaskStatus")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("ReportTaskStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReportInstanceStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) InvalidateTaskInstance(ctx context.Context, req *InvalidateTaskInstanceReq, opts ...client.Option) (*InvalidateTaskInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/InvalidateTaskInstance")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("InvalidateTaskInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &InvalidateTaskInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) GetDataTypeConfigs(ctx context.Context, req *GetDataTypeConfigsReq, opts ...client.Option) (*GetDataTypeConfigsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetDataTypeConfigs")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetDataTypeConfigs")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetDataTypeConfigsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) GetDataTypeConfigWithFields(ctx context.Context, req *GetDataTypeConfigWithFieldsReq, opts ...client.Option) (*GetDataTypeConfigWithFieldsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/GetDataTypeConfigWithFields")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("GetDataTypeConfigWithFields")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetDataTypeConfigWithFieldsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CollectMgrClientProxyImpl) RecalculateAllTaskInstances(ctx context.Context, req *RecalculateAllTaskInstancesReq, opts ...client.Option) (*RecalculateAllTaskInstancesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CollectMgr/RecalculateAllTaskInstances")
	msg.WithCalleeServiceName(CollectMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CollectMgr")
	msg.WithCalleeMethod("RecalculateAllTaskInstances")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RecalculateAllTaskInstancesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// CloudNodeMgrClientProxy defines service client proxy
type CloudNodeMgrClientProxy interface {
	// GetNodeList ----- 节点 -----
	GetNodeList(ctx context.Context, req *GetNodeListReq, opts ...client.Option) (rsp *GetNodeListRsp, err error)

	GetNodeDetail(ctx context.Context, req *GetNodeDetailReq, opts ...client.Option) (rsp *GetNodeDetailRsp, err error)

	GetSCFDeployInfo(ctx context.Context, req *GetSCFDeployInfoReq, opts ...client.Option) (rsp *GetSCFDeployInfoRsp, err error)

	UpdateNode(ctx context.Context, req *UpdateNodeReq, opts ...client.Option) (rsp *UpdateNodeRsp, err error)

	DeleteNode(ctx context.Context, req *DeleteNodeReq, opts ...client.Option) (rsp *DeleteNodeRsp, err error)

	InvokeFunction(ctx context.Context, req *InvokeFunctionReq, opts ...client.Option) (rsp *InvokeFunctionRsp, err error)

	UpdateNodeFunction(ctx context.Context, req *UpdateNodeFunctionReq, opts ...client.Option) (rsp *UpdateNodeFunctionRsp, err error)
	// BatchCreateNodes ----- 批量操作 -----
	BatchCreateNodes(ctx context.Context, req *BatchCreateNodesReq, opts ...client.Option) (rsp *BatchOperationRsp, err error)

	BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq, opts ...client.Option) (rsp *BatchOperationRsp, err error)

	BatchDeployNodes(ctx context.Context, req *BatchDeployNodesReq, opts ...client.Option) (rsp *BatchOperationRsp, err error)
	// ListCloudAccounts ----- 云账户 -----
	ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq, opts ...client.Option) (rsp *ListCloudAccountsRsp, err error)

	GetCloudAccount(ctx context.Context, req *GetCloudAccountReq, opts ...client.Option) (rsp *GetCloudAccountRsp, err error)

	CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq, opts ...client.Option) (rsp *CreateCloudAccountRsp, err error)

	UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq, opts ...client.Option) (rsp *UpdateCloudAccountRsp, err error)

	DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq, opts ...client.Option) (rsp *DeleteCloudAccountRsp, err error)

	GetCOSAccountInfo(ctx context.Context, req *GetCOSAccountInfoReq, opts ...client.Option) (rsp *GetCOSAccountInfoRsp, err error)
	// ListCloudRegions ----- 云地区 -----
	ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq, opts ...client.Option) (rsp *ListCloudRegionsRsp, err error)
	// GetPackageList ----- 代码包 -----
	GetPackageList(ctx context.Context, req *GetPackageListReq, opts ...client.Option) (rsp *GetPackageListRsp, err error)

	GetPackageDetail(ctx context.Context, req *GetPackageDetailReq, opts ...client.Option) (rsp *GetPackageDetailRsp, err error)

	DeletePackage(ctx context.Context, req *DeletePackageReq, opts ...client.Option) (rsp *DeletePackageRsp, err error)

	GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq, opts ...client.Option) (rsp *GetPackageDownloadURLRsp, err error)

	GetPackageOptions(ctx context.Context, req *GetPackageOptionsReq, opts ...client.Option) (rsp *GetPackageOptionsRsp, err error)
	// ReportHeartbeat ----- 心跳 -----
	ReportHeartbeat(ctx context.Context, req *ReportHeartbeatReq, opts ...client.Option) (rsp *ReportHeartbeatRsp, err error)
}

type CloudNodeMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCloudNodeMgrClientProxy = func(opts ...client.Option) CloudNodeMgrClientProxy {
	return &CloudNodeMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CloudNodeMgrClientProxyImpl) GetNodeList(ctx context.Context, req *GetNodeListReq, opts ...client.Option) (*GetNodeListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetNodeList")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetNodeList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetNodeListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetNodeDetail(ctx context.Context, req *GetNodeDetailReq, opts ...client.Option) (*GetNodeDetailRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetNodeDetail")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetNodeDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetNodeDetailRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetSCFDeployInfo(ctx context.Context, req *GetSCFDeployInfoReq, opts ...client.Option) (*GetSCFDeployInfoRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetSCFDeployInfo")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetSCFDeployInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetSCFDeployInfoRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) UpdateNode(ctx context.Context, req *UpdateNodeReq, opts ...client.Option) (*UpdateNodeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/UpdateNode")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("UpdateNode")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateNodeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) DeleteNode(ctx context.Context, req *DeleteNodeReq, opts ...client.Option) (*DeleteNodeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/DeleteNode")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("DeleteNode")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteNodeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) InvokeFunction(ctx context.Context, req *InvokeFunctionReq, opts ...client.Option) (*InvokeFunctionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/InvokeFunction")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("InvokeFunction")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &InvokeFunctionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) UpdateNodeFunction(ctx context.Context, req *UpdateNodeFunctionReq, opts ...client.Option) (*UpdateNodeFunctionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/UpdateNodeFunction")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("UpdateNodeFunction")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateNodeFunctionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) BatchCreateNodes(ctx context.Context, req *BatchCreateNodesReq, opts ...client.Option) (*BatchOperationRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/BatchCreateNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("BatchCreateNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &BatchOperationRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) BatchDeleteNodes(ctx context.Context, req *BatchDeleteNodesReq, opts ...client.Option) (*BatchOperationRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/BatchDeleteNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("BatchDeleteNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &BatchOperationRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) BatchDeployNodes(ctx context.Context, req *BatchDeployNodesReq, opts ...client.Option) (*BatchOperationRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/BatchDeployNodes")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("BatchDeployNodes")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &BatchOperationRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ListCloudAccounts(ctx context.Context, req *ListCloudAccountsReq, opts ...client.Option) (*ListCloudAccountsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/ListCloudAccounts")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ListCloudAccounts")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListCloudAccountsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetCloudAccount(ctx context.Context, req *GetCloudAccountReq, opts ...client.Option) (*GetCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) CreateCloudAccount(ctx context.Context, req *CreateCloudAccountReq, opts ...client.Option) (*CreateCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/CreateCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("CreateCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) UpdateCloudAccount(ctx context.Context, req *UpdateCloudAccountReq, opts ...client.Option) (*UpdateCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/UpdateCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("UpdateCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) DeleteCloudAccount(ctx context.Context, req *DeleteCloudAccountReq, opts ...client.Option) (*DeleteCloudAccountRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/DeleteCloudAccount")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("DeleteCloudAccount")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteCloudAccountRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetCOSAccountInfo(ctx context.Context, req *GetCOSAccountInfoReq, opts ...client.Option) (*GetCOSAccountInfoRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetCOSAccountInfo")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetCOSAccountInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetCOSAccountInfoRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ListCloudRegions(ctx context.Context, req *ListCloudRegionsReq, opts ...client.Option) (*ListCloudRegionsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/ListCloudRegions")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ListCloudRegions")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListCloudRegionsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageList(ctx context.Context, req *GetPackageListReq, opts ...client.Option) (*GetPackageListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetPackageList")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageDetail(ctx context.Context, req *GetPackageDetailReq, opts ...client.Option) (*GetPackageDetailRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetPackageDetail")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageDetailRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) DeletePackage(ctx context.Context, req *DeletePackageReq, opts ...client.Option) (*DeletePackageRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/DeletePackage")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("DeletePackage")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeletePackageRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageDownloadURL(ctx context.Context, req *GetPackageDownloadURLReq, opts ...client.Option) (*GetPackageDownloadURLRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetPackageDownloadURL")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageDownloadURL")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageDownloadURLRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) GetPackageOptions(ctx context.Context, req *GetPackageOptionsReq, opts ...client.Option) (*GetPackageOptionsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/GetPackageOptions")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("GetPackageOptions")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPackageOptionsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CloudNodeMgrClientProxyImpl) ReportHeartbeat(ctx context.Context, req *ReportHeartbeatReq, opts ...client.Option) (*ReportHeartbeatRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.collect.CloudNodeMgr/ReportHeartbeat")
	msg.WithCalleeServiceName(CloudNodeMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("collect")
	msg.WithCalleeService("CloudNodeMgr")
	msg.WithCalleeMethod("ReportHeartbeat")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ReportHeartbeatRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
