// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: infra_service.proto

package mooxpb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AuthService defines service.
type AuthService interface {
	// Register 用户注册
	Register(ctx context.Context, req *RegisterReq) (*RegisterRsp, error)
	// GetLoginSalt 获取登录盐值
	GetLoginSalt(ctx context.Context, req *GetLoginSaltReq) (*GetLoginSaltRsp, error)
	// Login 用户登录
	Login(ctx context.Context, req *LoginReq) (*LoginRsp, error)
	// GetChangePasswordSalt 获取修改密码盐值
	GetChangePasswordSalt(ctx context.Context, req *GetChangePasswordSaltReq) (*GetChangePasswordSaltRsp, error)
	// ChangePassword 修改密码
	ChangePassword(ctx context.Context, req *ChangePasswordReq) (*ChangePasswordRsp, error)
	// GetUserInfo 获取用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoRsp, error)
	// UpdateUserInfo 更新用户信息
	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (*UpdateUserInfoRsp, error)
}

func AuthService_Register_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RegisterReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).Register(ctx, reqbody.(*RegisterReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthService_GetLoginSalt_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetLoginSaltReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).GetLoginSalt(ctx, reqbody.(*GetLoginSaltReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthService_Login_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &LoginReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).Login(ctx, reqbody.(*LoginReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthService_GetChangePasswordSalt_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetChangePasswordSaltReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).GetChangePasswordSalt(ctx, reqbody.(*GetChangePasswordSaltReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthService_ChangePassword_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ChangePasswordReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).ChangePassword(ctx, reqbody.(*ChangePasswordReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthService_GetUserInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserInfoReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).GetUserInfo(ctx, reqbody.(*GetUserInfoReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AuthService_UpdateUserInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateUserInfoReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AuthService).UpdateUserInfo(ctx, reqbody.(*UpdateUserInfoReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AuthServer_ServiceDesc descriptor for server.RegisterService.
var AuthServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.infra.Auth",
	HandlerType: ((*AuthService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.infra.Auth/Register",
			Func: AuthService_Register_Handler,
		},
		{
			Name: "/trpc.moox.infra.Auth/GetLoginSalt",
			Func: AuthService_GetLoginSalt_Handler,
		},
		{
			Name: "/trpc.moox.infra.Auth/Login",
			Func: AuthService_Login_Handler,
		},
		{
			Name: "/trpc.moox.infra.Auth/GetChangePasswordSalt",
			Func: AuthService_GetChangePasswordSalt_Handler,
		},
		{
			Name: "/trpc.moox.infra.Auth/ChangePassword",
			Func: AuthService_ChangePassword_Handler,
		},
		{
			Name: "/trpc.moox.infra.Auth/GetUserInfo",
			Func: AuthService_GetUserInfo_Handler,
		},
		{
			Name: "/trpc.moox.infra.Auth/UpdateUserInfo",
			Func: AuthService_UpdateUserInfo_Handler,
		},
	},
}

// RegisterAuthService registers service.
func RegisterAuthService(s server.Service, svr AuthService) {
	if err := s.Register(&AuthServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Auth register error:%v", err))
	}
}

// AsyncTaskService defines service.
type AsyncTaskService interface {
	// CreateAsyncJob 创建异步 Job
	CreateAsyncJob(ctx context.Context, req *CreateAsyncJobReq) (*CreateAsyncJobRsp, error)
	// QueryAsyncJob 查询 Job 状态
	QueryAsyncJob(ctx context.Context, req *QueryAsyncJobReq) (*QueryAsyncJobRsp, error)
}

func AsyncTaskService_CreateAsyncJob_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateAsyncJobReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AsyncTaskService).CreateAsyncJob(ctx, reqbody.(*CreateAsyncJobReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AsyncTaskService_QueryAsyncJob_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryAsyncJobReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AsyncTaskService).QueryAsyncJob(ctx, reqbody.(*QueryAsyncJobReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AsyncTaskServer_ServiceDesc descriptor for server.RegisterService.
var AsyncTaskServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.infra.AsyncTask",
	HandlerType: ((*AsyncTaskService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.infra.AsyncTask/CreateAsyncJob",
			Func: AsyncTaskService_CreateAsyncJob_Handler,
		},
		{
			Name: "/trpc.moox.infra.AsyncTask/QueryAsyncJob",
			Func: AsyncTaskService_QueryAsyncJob_Handler,
		},
	},
}

// RegisterAsyncTaskService registers service.
func RegisterAsyncTaskService(s server.Service, svr AsyncTaskService) {
	if err := s.Register(&AsyncTaskServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AsyncTask register error:%v", err))
	}
}

// DnsService defines service.
type DnsService interface {
	// ListDNSRecords 列出所有 DNS 解析记录
	ListDNSRecords(ctx context.Context, req *ListDNSRecordsReq) (*ListDNSRecordsRsp, error)
	// GetDNSRecord 获取指定域名的 DNS 解析记录详情
	GetDNSRecord(ctx context.Context, req *GetDNSRecordReq) (*GetDNSRecordRsp, error)
}

func DnsService_ListDNSRecords_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListDNSRecordsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DnsService).ListDNSRecords(ctx, reqbody.(*ListDNSRecordsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func DnsService_GetDNSRecord_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetDNSRecordReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(DnsService).GetDNSRecord(ctx, reqbody.(*GetDNSRecordReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// DnsServer_ServiceDesc descriptor for server.RegisterService.
var DnsServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.infra.Dns",
	HandlerType: ((*DnsService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.infra.Dns/ListDNSRecords",
			Func: DnsService_ListDNSRecords_Handler,
		},
		{
			Name: "/trpc.moox.infra.Dns/GetDNSRecord",
			Func: DnsService_GetDNSRecord_Handler,
		},
	},
}

// RegisterDnsService registers service.
func RegisterDnsService(s server.Service, svr DnsService) {
	if err := s.Register(&DnsServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Dns register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAuth struct{}

// Register 用户注册
func (s *UnimplementedAuth) Register(ctx context.Context, req *RegisterReq) (*RegisterRsp, error) {
	return nil, errors.New("rpc Register of service Auth is not implemented")
}

// GetLoginSalt 获取登录盐值
func (s *UnimplementedAuth) GetLoginSalt(ctx context.Context, req *GetLoginSaltReq) (*GetLoginSaltRsp, error) {
	return nil, errors.New("rpc GetLoginSalt of service Auth is not implemented")
}

// Login 用户登录
func (s *UnimplementedAuth) Login(ctx context.Context, req *LoginReq) (*LoginRsp, error) {
	return nil, errors.New("rpc Login of service Auth is not implemented")
}

// GetChangePasswordSalt 获取修改密码盐值
func (s *UnimplementedAuth) GetChangePasswordSalt(ctx context.Context, req *GetChangePasswordSaltReq) (*GetChangePasswordSaltRsp, error) {
	return nil, errors.New("rpc GetChangePasswordSalt of service Auth is not implemented")
}

// ChangePassword 修改密码
func (s *UnimplementedAuth) ChangePassword(ctx context.Context, req *ChangePasswordReq) (*ChangePasswordRsp, error) {
	return nil, errors.New("rpc ChangePassword of service Auth is not implemented")
}

// GetUserInfo 获取用户信息
func (s *UnimplementedAuth) GetUserInfo(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoRsp, error) {
	return nil, errors.New("rpc GetUserInfo of service Auth is not implemented")
}

// UpdateUserInfo 更新用户信息
func (s *UnimplementedAuth) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq) (*UpdateUserInfoRsp, error) {
	return nil, errors.New("rpc UpdateUserInfo of service Auth is not implemented")
}

type UnimplementedAsyncTask struct{}

// CreateAsyncJob 创建异步 Job
func (s *UnimplementedAsyncTask) CreateAsyncJob(ctx context.Context, req *CreateAsyncJobReq) (*CreateAsyncJobRsp, error) {
	return nil, errors.New("rpc CreateAsyncJob of service AsyncTask is not implemented")
}

// QueryAsyncJob 查询 Job 状态
func (s *UnimplementedAsyncTask) QueryAsyncJob(ctx context.Context, req *QueryAsyncJobReq) (*QueryAsyncJobRsp, error) {
	return nil, errors.New("rpc QueryAsyncJob of service AsyncTask is not implemented")
}

type UnimplementedDns struct{}

// ListDNSRecords 列出所有 DNS 解析记录
func (s *UnimplementedDns) ListDNSRecords(ctx context.Context, req *ListDNSRecordsReq) (*ListDNSRecordsRsp, error) {
	return nil, errors.New("rpc ListDNSRecords of service Dns is not implemented")
}

// GetDNSRecord 获取指定域名的 DNS 解析记录详情
func (s *UnimplementedDns) GetDNSRecord(ctx context.Context, req *GetDNSRecordReq) (*GetDNSRecordRsp, error) {
	return nil, errors.New("rpc GetDNSRecord of service Dns is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AuthClientProxy defines service client proxy
type AuthClientProxy interface {
	// Register 用户注册
	Register(ctx context.Context, req *RegisterReq, opts ...client.Option) (rsp *RegisterRsp, err error)
	// GetLoginSalt 获取登录盐值
	GetLoginSalt(ctx context.Context, req *GetLoginSaltReq, opts ...client.Option) (rsp *GetLoginSaltRsp, err error)
	// Login 用户登录
	Login(ctx context.Context, req *LoginReq, opts ...client.Option) (rsp *LoginRsp, err error)
	// GetChangePasswordSalt 获取修改密码盐值
	GetChangePasswordSalt(ctx context.Context, req *GetChangePasswordSaltReq, opts ...client.Option) (rsp *GetChangePasswordSaltRsp, err error)
	// ChangePassword 修改密码
	ChangePassword(ctx context.Context, req *ChangePasswordReq, opts ...client.Option) (rsp *ChangePasswordRsp, err error)
	// GetUserInfo 获取用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoReq, opts ...client.Option) (rsp *GetUserInfoRsp, err error)
	// UpdateUserInfo 更新用户信息
	UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq, opts ...client.Option) (rsp *UpdateUserInfoRsp, err error)
}

type AuthClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAuthClientProxy = func(opts ...client.Option) AuthClientProxy {
	return &AuthClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AuthClientProxyImpl) Register(ctx context.Context, req *RegisterReq, opts ...client.Option) (*RegisterRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/Register")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("Register")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RegisterRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthClientProxyImpl) GetLoginSalt(ctx context.Context, req *GetLoginSaltReq, opts ...client.Option) (*GetLoginSaltRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/GetLoginSalt")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("GetLoginSalt")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetLoginSaltRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthClientProxyImpl) Login(ctx context.Context, req *LoginReq, opts ...client.Option) (*LoginRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/Login")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("Login")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &LoginRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthClientProxyImpl) GetChangePasswordSalt(ctx context.Context, req *GetChangePasswordSaltReq, opts ...client.Option) (*GetChangePasswordSaltRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/GetChangePasswordSalt")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("GetChangePasswordSalt")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetChangePasswordSaltRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthClientProxyImpl) ChangePassword(ctx context.Context, req *ChangePasswordReq, opts ...client.Option) (*ChangePasswordRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/ChangePassword")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("ChangePassword")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ChangePasswordRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthClientProxyImpl) GetUserInfo(ctx context.Context, req *GetUserInfoReq, opts ...client.Option) (*GetUserInfoRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/GetUserInfo")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("GetUserInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserInfoRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AuthClientProxyImpl) UpdateUserInfo(ctx context.Context, req *UpdateUserInfoReq, opts ...client.Option) (*UpdateUserInfoRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Auth/UpdateUserInfo")
	msg.WithCalleeServiceName(AuthServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Auth")
	msg.WithCalleeMethod("UpdateUserInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateUserInfoRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// AsyncTaskClientProxy defines service client proxy
type AsyncTaskClientProxy interface {
	// CreateAsyncJob 创建异步 Job
	CreateAsyncJob(ctx context.Context, req *CreateAsyncJobReq, opts ...client.Option) (rsp *CreateAsyncJobRsp, err error)
	// QueryAsyncJob 查询 Job 状态
	QueryAsyncJob(ctx context.Context, req *QueryAsyncJobReq, opts ...client.Option) (rsp *QueryAsyncJobRsp, err error)
}

type AsyncTaskClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAsyncTaskClientProxy = func(opts ...client.Option) AsyncTaskClientProxy {
	return &AsyncTaskClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AsyncTaskClientProxyImpl) CreateAsyncJob(ctx context.Context, req *CreateAsyncJobReq, opts ...client.Option) (*CreateAsyncJobRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.AsyncTask/CreateAsyncJob")
	msg.WithCalleeServiceName(AsyncTaskServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("AsyncTask")
	msg.WithCalleeMethod("CreateAsyncJob")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateAsyncJobRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AsyncTaskClientProxyImpl) QueryAsyncJob(ctx context.Context, req *QueryAsyncJobReq, opts ...client.Option) (*QueryAsyncJobRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.AsyncTask/QueryAsyncJob")
	msg.WithCalleeServiceName(AsyncTaskServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("AsyncTask")
	msg.WithCalleeMethod("QueryAsyncJob")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryAsyncJobRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// DnsClientProxy defines service client proxy
type DnsClientProxy interface {
	// ListDNSRecords 列出所有 DNS 解析记录
	ListDNSRecords(ctx context.Context, req *ListDNSRecordsReq, opts ...client.Option) (rsp *ListDNSRecordsRsp, err error)
	// GetDNSRecord 获取指定域名的 DNS 解析记录详情
	GetDNSRecord(ctx context.Context, req *GetDNSRecordReq, opts ...client.Option) (rsp *GetDNSRecordRsp, err error)
}

type DnsClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewDnsClientProxy = func(opts ...client.Option) DnsClientProxy {
	return &DnsClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *DnsClientProxyImpl) ListDNSRecords(ctx context.Context, req *ListDNSRecordsReq, opts ...client.Option) (*ListDNSRecordsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Dns/ListDNSRecords")
	msg.WithCalleeServiceName(DnsServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Dns")
	msg.WithCalleeMethod("ListDNSRecords")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListDNSRecordsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *DnsClientProxyImpl) GetDNSRecord(ctx context.Context, req *GetDNSRecordReq, opts ...client.Option) (*GetDNSRecordRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.infra.Dns/GetDNSRecord")
	msg.WithCalleeServiceName(DnsServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("infra")
	msg.WithCalleeService("Dns")
	msg.WithCalleeMethod("GetDNSRecord")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetDNSRecordRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
