// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: secret_service.proto

package mooxpb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// SecretMgrService defines service.
type SecretMgrService interface {
	ListSecrets(ctx context.Context, req *ListSecretsReq) (*ListSecretsRsp, error)

	GetSecret(ctx context.Context, req *GetSecretReq) (*GetSecretRsp, error)

	CreateSecret(ctx context.Context, req *CreateSecretReq) (*CreateSecretRsp, error)

	UpdateSecret(ctx context.Context, req *UpdateSecretReq) (*UpdateSecretRsp, error)

	DeleteSecret(ctx context.Context, req *DeleteSecretReq) (*DeleteSecretRsp, error)

	ToggleSecretStatus(ctx context.Context, req *ToggleSecretStatusReq) (*ToggleSecretStatusRsp, error)
}

func SecretMgrService_ListSecrets_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListSecretsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SecretMgrService).ListSecrets(ctx, reqbody.(*ListSecretsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SecretMgrService_GetSecret_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetSecretReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SecretMgrService).GetSecret(ctx, reqbody.(*GetSecretReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SecretMgrService_CreateSecret_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateSecretReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SecretMgrService).CreateSecret(ctx, reqbody.(*CreateSecretReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SecretMgrService_UpdateSecret_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateSecretReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SecretMgrService).UpdateSecret(ctx, reqbody.(*UpdateSecretReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SecretMgrService_DeleteSecret_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteSecretReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SecretMgrService).DeleteSecret(ctx, reqbody.(*DeleteSecretReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SecretMgrService_ToggleSecretStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ToggleSecretStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SecretMgrService).ToggleSecretStatus(ctx, reqbody.(*ToggleSecretStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// SecretMgrServer_ServiceDesc descriptor for server.RegisterService.
var SecretMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.ops.SecretMgr",
	HandlerType: ((*SecretMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.ops.SecretMgr/ListSecrets",
			Func: SecretMgrService_ListSecrets_Handler,
		},
		{
			Name: "/trpc.moox.ops.SecretMgr/GetSecret",
			Func: SecretMgrService_GetSecret_Handler,
		},
		{
			Name: "/trpc.moox.ops.SecretMgr/CreateSecret",
			Func: SecretMgrService_CreateSecret_Handler,
		},
		{
			Name: "/trpc.moox.ops.SecretMgr/UpdateSecret",
			Func: SecretMgrService_UpdateSecret_Handler,
		},
		{
			Name: "/trpc.moox.ops.SecretMgr/DeleteSecret",
			Func: SecretMgrService_DeleteSecret_Handler,
		},
		{
			Name: "/trpc.moox.ops.SecretMgr/ToggleSecretStatus",
			Func: SecretMgrService_ToggleSecretStatus_Handler,
		},
	},
}

// RegisterSecretMgrService registers service.
func RegisterSecretMgrService(s server.Service, svr SecretMgrService) {
	if err := s.Register(&SecretMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("SecretMgr register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedSecretMgr struct{}

func (s *UnimplementedSecretMgr) ListSecrets(ctx context.Context, req *ListSecretsReq) (*ListSecretsRsp, error) {
	return nil, errors.New("rpc ListSecrets of service SecretMgr is not implemented")
}
func (s *UnimplementedSecretMgr) GetSecret(ctx context.Context, req *GetSecretReq) (*GetSecretRsp, error) {
	return nil, errors.New("rpc GetSecret of service SecretMgr is not implemented")
}
func (s *UnimplementedSecretMgr) CreateSecret(ctx context.Context, req *CreateSecretReq) (*CreateSecretRsp, error) {
	return nil, errors.New("rpc CreateSecret of service SecretMgr is not implemented")
}
func (s *UnimplementedSecretMgr) UpdateSecret(ctx context.Context, req *UpdateSecretReq) (*UpdateSecretRsp, error) {
	return nil, errors.New("rpc UpdateSecret of service SecretMgr is not implemented")
}
func (s *UnimplementedSecretMgr) DeleteSecret(ctx context.Context, req *DeleteSecretReq) (*DeleteSecretRsp, error) {
	return nil, errors.New("rpc DeleteSecret of service SecretMgr is not implemented")
}
func (s *UnimplementedSecretMgr) ToggleSecretStatus(ctx context.Context, req *ToggleSecretStatusReq) (*ToggleSecretStatusRsp, error) {
	return nil, errors.New("rpc ToggleSecretStatus of service SecretMgr is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// SecretMgrClientProxy defines service client proxy
type SecretMgrClientProxy interface {
	ListSecrets(ctx context.Context, req *ListSecretsReq, opts ...client.Option) (rsp *ListSecretsRsp, err error)

	GetSecret(ctx context.Context, req *GetSecretReq, opts ...client.Option) (rsp *GetSecretRsp, err error)

	CreateSecret(ctx context.Context, req *CreateSecretReq, opts ...client.Option) (rsp *CreateSecretRsp, err error)

	UpdateSecret(ctx context.Context, req *UpdateSecretReq, opts ...client.Option) (rsp *UpdateSecretRsp, err error)

	DeleteSecret(ctx context.Context, req *DeleteSecretReq, opts ...client.Option) (rsp *DeleteSecretRsp, err error)

	ToggleSecretStatus(ctx context.Context, req *ToggleSecretStatusReq, opts ...client.Option) (rsp *ToggleSecretStatusRsp, err error)
}

type SecretMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewSecretMgrClientProxy = func(opts ...client.Option) SecretMgrClientProxy {
	return &SecretMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *SecretMgrClientProxyImpl) ListSecrets(ctx context.Context, req *ListSecretsReq, opts ...client.Option) (*ListSecretsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.ops.SecretMgr/ListSecrets")
	msg.WithCalleeServiceName(SecretMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("ops")
	msg.WithCalleeService("SecretMgr")
	msg.WithCalleeMethod("ListSecrets")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListSecretsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SecretMgrClientProxyImpl) GetSecret(ctx context.Context, req *GetSecretReq, opts ...client.Option) (*GetSecretRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.ops.SecretMgr/GetSecret")
	msg.WithCalleeServiceName(SecretMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("ops")
	msg.WithCalleeService("SecretMgr")
	msg.WithCalleeMethod("GetSecret")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetSecretRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SecretMgrClientProxyImpl) CreateSecret(ctx context.Context, req *CreateSecretReq, opts ...client.Option) (*CreateSecretRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.ops.SecretMgr/CreateSecret")
	msg.WithCalleeServiceName(SecretMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("ops")
	msg.WithCalleeService("SecretMgr")
	msg.WithCalleeMethod("CreateSecret")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateSecretRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SecretMgrClientProxyImpl) UpdateSecret(ctx context.Context, req *UpdateSecretReq, opts ...client.Option) (*UpdateSecretRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.ops.SecretMgr/UpdateSecret")
	msg.WithCalleeServiceName(SecretMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("ops")
	msg.WithCalleeService("SecretMgr")
	msg.WithCalleeMethod("UpdateSecret")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateSecretRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SecretMgrClientProxyImpl) DeleteSecret(ctx context.Context, req *DeleteSecretReq, opts ...client.Option) (*DeleteSecretRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.ops.SecretMgr/DeleteSecret")
	msg.WithCalleeServiceName(SecretMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("ops")
	msg.WithCalleeService("SecretMgr")
	msg.WithCalleeMethod("DeleteSecret")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteSecretRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SecretMgrClientProxyImpl) ToggleSecretStatus(ctx context.Context, req *ToggleSecretStatusReq, opts ...client.Option) (*ToggleSecretStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.ops.SecretMgr/ToggleSecretStatus")
	msg.WithCalleeServiceName(SecretMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("ops")
	msg.WithCalleeService("SecretMgr")
	msg.WithCalleeMethod("ToggleSecretStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ToggleSecretStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
