global:
  namespace: Development
  env_name: dev

server:
  filter:
    - recovery
    - validation
    - prometheus
  timeout: 5000
  admin:
    ip: 127.0.0.1
    port: 11950
    read_timeout: 3000
    write_timeout: 60000
  service:
    - name: trpc.moox.monitor.MonitorMgr
      ip: 127.0.0.1
      port: 11410
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.monitor.Health
      ip: 127.0.0.1
      port: 11409
      network: tcp
      protocol: http_no_protocol
      timeout: 3000
    - name: trpc.moox.monitor.metrics.timer
      port: 11415
      network: "*/30 * * * * *"
      protocol: timer
      timeout: 10000
    - name: trpc.moox.monitor.sysdeploy.timer
      port: 11416
      network: "0 * * * * *"
      protocol: timer
      timeout: 30000
    - name: trpc.moox.monitor.data_cleanup.timer
      port: 11500
      network: "0 0 */6 * * *?startAtOnce=1"
      protocol: timer
      timeout: 120000
    - name: trpc.moox.monitor.check_schedule.timer
      port: 11501
      network: "*/30 * * * * *?startAtOnce=1"
      protocol: timer
      timeout: 30000
    - name: trpc.moox.monitor.metric_rule.timer
      port: 11502
      network: "0 * * * * *?startAtOnce=1"
      protocol: timer
      timeout: 30000
plugins:
  auth:
    validation:
      enable_error_log: false
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  metrics:
    prometheus:
      ip: 127.0.0.1
      port: 12950
      path: /metrics
      enablepush: false
  log:
    default:
      - writer: console
        level: info
