// Package crypto contains MooX's shared security primitives.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/crypto/bcrypt"
)

var (
	ErrEmptyPlaintext  = errors.New("plaintext cannot be empty")
	ErrEmptyCiphertext = errors.New("ciphertext cannot be empty")
	ErrCiphertextShort = errors.New("ciphertext too short")
	ErrEmptySecret     = errors.New("secret cannot be empty")
)

// Encrypt encrypts plaintext with AES-256-GCM. The key is derived from secret
// with SHA-256, so callers do not need to coordinate AES key lengths. Secret
// must already contain high-entropy key material; this function is not a
// password-based key derivation function.
func Encrypt(plaintext, secret string) (string, error) {
	if plaintext == "" {
		return "", ErrEmptyPlaintext
	}
	if secret == "" {
		return "", ErrEmptySecret
	}

	block, err := aes.NewCipher(deriveKey(secret))
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create AES-GCM: %w", err)
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", fmt.Errorf("generate nonce: %w", err)
	}
	payload := gcm.Seal(nonce, nonce, []byte(plaintext), nil)
	return base64.StdEncoding.EncodeToString(payload), nil
}

// Decrypt decrypts an AES-256-GCM payload generated by Encrypt.
func Decrypt(ciphertext, secret string) (string, error) {
	if ciphertext == "" {
		return "", ErrEmptyCiphertext
	}
	if secret == "" {
		return "", ErrEmptySecret
	}

	data, err := base64.StdEncoding.DecodeString(ciphertext)
	if err != nil {
		return "", fmt.Errorf("decode ciphertext: %w", err)
	}
	plaintext, err := decryptWithKey(data, deriveKey(secret))
	if err == nil {
		return plaintext, nil
	}

	// Secrets written before the shared crypto package was introduced used the
	// legacy key normalization. Keep reads backward-compatible so a deployment
	// can migrate an existing admin database without re-encrypting it blindly.
	legacyPlaintext, legacyErr := decryptWithKey(data, legacyKey(secret))
	if legacyErr == nil {
		return legacyPlaintext, nil
	}
	return "", fmt.Errorf("decrypt ciphertext: %w", err)
}

func deriveKey(secret string) []byte {
	hash := sha256.Sum256([]byte(secret))
	return hash[:]
}

func legacyKey(secret string) []byte {
	switch len(secret) {
	case 16, 24, 32:
		return []byte(secret)
	}
	if len(secret) > 32 {
		return []byte(secret[:32])
	}
	hash := sha256.Sum256([]byte(secret))
	return []byte(hex.EncodeToString(hash[:])[:32])
}

func decryptWithKey(data, key []byte) (string, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", fmt.Errorf("create AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", fmt.Errorf("create AES-GCM: %w", err)
	}
	if len(data) < gcm.NonceSize()+gcm.Overhead() {
		return "", ErrCiphertextShort
	}
	plaintext, err := gcm.Open(nil, data[:gcm.NonceSize()], data[gcm.NonceSize():], nil)
	if err != nil {
		return "", err
	}
	return string(plaintext), nil
}

// SHA256Hex returns the lowercase hexadecimal SHA-256 digest of data.
func SHA256Hex(data []byte) string {
	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:])
}

// HMACSHA256Hex returns the lowercase hexadecimal HMAC-SHA256 of data.
func HMACSHA256Hex(secret string, data []byte) string {
	mac := hmac.New(sha256.New, []byte(secret))
	_, _ = mac.Write(data)
	return hex.EncodeToString(mac.Sum(nil))
}

// RandomHex returns size cryptographically random bytes as lowercase hex.
func RandomHex(size int) (string, error) {
	if size <= 0 {
		return "", errors.New("random byte size must be positive")
	}
	buf := make([]byte, size)
	if _, err := io.ReadFull(rand.Reader, buf); err != nil {
		return "", fmt.Errorf("generate random bytes: %w", err)
	}
	return hex.EncodeToString(buf), nil
}

// HashPassword hashes a password with bcrypt. The encoded result contains the
// randomly generated salt and cost, so callers do not store a second salt.
func HashPassword(password string) (string, error) {
	if password == "" {
		return "", errors.New("password cannot be empty")
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}
	return string(hash), nil
}

// VerifyPassword reports whether password matches a bcrypt encoded hash.
func VerifyPassword(password, encodedHash string) bool {
	if password == "" || encodedHash == "" {
		return false
	}
	return bcrypt.CompareHashAndPassword([]byte(encodedHash), []byte(password)) == nil
}

// SignToken signs generic claims with HS256. Business-specific claim
// validation belongs to the caller, not this package.
func SignToken(claims map[string]any, secret, issuer string, ttl time.Duration) (string, error) {
	if secret == "" {
		return "", ErrEmptySecret
	}
	if ttl <= 0 {
		return "", errors.New("token ttl must be positive")
	}
	now := time.Now()
	jwtClaims := jwt.MapClaims{}
	for key, value := range claims {
		jwtClaims[key] = value
	}
	jwtClaims["iat"] = now.Unix()
	jwtClaims["nbf"] = now.Unix()
	jwtClaims["exp"] = now.Add(ttl).Unix()
	if issuer != "" {
		jwtClaims["iss"] = issuer
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwtClaims)
	signed, err := token.SignedString([]byte(secret))
	if err != nil {
		return "", fmt.Errorf("sign token: %w", err)
	}
	return signed, nil
}

// ParseToken verifies an HS256 token and returns its generic claims.
func ParseToken(raw, secret string) (map[string]any, error) {
	if raw == "" {
		return nil, errors.New("token cannot be empty")
	}
	if secret == "" {
		return nil, ErrEmptySecret
	}
	token, err := jwt.ParseWithClaims(raw, jwt.MapClaims{}, func(token *jwt.Token) (any, error) {
		if token.Method == nil {
			return nil, errors.New("token signing method is missing")
		}
		method, ok := token.Method.(*jwt.SigningMethodHMAC)
		if !ok || method.Alg() != jwt.SigningMethodHS256.Alg() {
			return nil, fmt.Errorf("unexpected signing method: %s", token.Method.Alg())
		}
		return []byte(secret), nil
	})
	if err != nil {
		return nil, fmt.Errorf("parse token: %w", err)
	}
	if !token.Valid {
		return nil, errors.New("token is invalid")
	}
	claims, ok := token.Claims.(jwt.MapClaims)
	if !ok {
		return nil, errors.New("token claims have unexpected type")
	}
	result := make(map[string]any, len(claims))
	for key, value := range claims {
		result[key] = value
	}
	return result, nil
}

// NewSalt returns a random 16-byte salt encoded as lowercase hexadecimal.
func NewSalt() (string, error) {
	buf := make([]byte, 16)
	if _, err := io.ReadFull(rand.Reader, buf); err != nil {
		return "", fmt.Errorf("generate salt: %w", err)
	}
	return hex.EncodeToString(buf), nil
}

// MaskSecret keeps a secret's outer characters and replaces its middle with
// four asterisks. Short values are fully masked.
func MaskSecret(value string, prefix, suffix int) string {
	if prefix < 0 {
		prefix = 0
	}
	if suffix < 0 {
		suffix = 0
	}
	if len(value) <= prefix+suffix {
		return "****"
	}
	return value[:prefix] + "****" + value[len(value)-suffix:]
}
