package api

import (
	"encoding/json"

	"github.com/mooyang-code/moox/modules/control/internal/common"
	"github.com/mooyang-code/moox/modules/control/internal/errors"
	"github.com/mooyang-code/moox/modules/control/internal/service/asynctask"

	"github.com/gin-gonic/gin"
	"trpc.group/trpc-go/trpc-go/log"
)

// BatchOperationHandler 批量操作处理器
type BatchOperationHandler struct {
	asyncService asynctask.Service
}

// NewBatchOperationHandler 创建批量操作处理器
func NewBatchOperationHandler(asyncService asynctask.Service) *BatchOperationHandler {
	return &BatchOperationHandler{
		asyncService: asyncService,
	}
}

// BatchCreateNodeRequest 批量创建节点请求
type BatchCreateNodeRequest struct {
	Nodes []NodeCreateItem `json:"nodes" binding:"required,min=1"`
}

// NodeCreateItem 创建节点项
type NodeCreateItem struct {
	CloudAccountID string                 `json:"cloud_account_id" binding:"required"`
	NodeType       string                 `json:"node_type" binding:"required"`
	Runtime        string                 `json:"runtime"`
	Handler        string                 `json:"handler"`
	Config         map[string]string      `json:"config"`
	Environment    map[string]string      `json:"environment"`
	Region         string                 `json:"region" binding:"required"`
	Namespace      string                 `json:"namespace"`
	PackageID      string                 `json:"package_id"`
	Metadata       map[string]interface{} `json:"metadata"`
}

// BatchDeleteNodeRequest 批量删除节点请求
type BatchDeleteNodeRequest struct {
	NodeIDs []string `json:"node_ids" binding:"required,min=1"`
}

// BatchDeployNodeRequest 批量部署节点请求
type BatchDeployNodeRequest struct {
	Deployments []NodeDeployItem `json:"deployments" binding:"required,min=1"`
}

// NodeDeployItem 部署节点项
type NodeDeployItem struct {
	NodeID    string `json:"node_id" binding:"required"`
	PackageID string `json:"package_id" binding:"required"`
}

// BatchOperationResponse 批量操作响应
type BatchOperationResponse struct {
	JobID        string `json:"job_id"`
	TotalTaskCnt int    `json:"total_task_cnt"`
	Message      string `json:"message"`
}

// BatchCreateNodes 批量创建节点
// POST /api/v1/cloud_node/batch/create
func (h *BatchOperationHandler) BatchCreateNodes(c *gin.Context) {
	ctx := c.Request.Context()
	var req BatchCreateNodeRequest

	if err := c.ShouldBindJSON(&req); err != nil {
		common.HandleAppError(c, errors.InvalidParam("request_body", err.Error()))
		return
	}

	if len(req.Nodes) == 0 {
		common.HandleAppError(c, errors.InvalidParam("nodes", "nodes cannot be empty"))
		return
	}

	// 生成JobID
	// jobID will be auto-generated by service
	log.InfoContextf(ctx, "[BatchCreateNodes] Creating batch job: NodeCount=%d", len(req.Nodes))

	// 构建任务列表
	tasks := make([]asynctask.TaskRequest, len(req.Nodes))
	for i, node := range req.Nodes {
		// 将节点参数转为JSON字符串
		paramsJSON, err := json.Marshal(node)
		if err != nil {
			common.HandleAppError(c, errors.InvalidParam("nodes", "invalid node parameters"))
			return
		}

		tasks[i] = asynctask.TaskRequest{
			TaskType:      asynctask.TaskTypeCreateNode,
			RequestParams: string(paramsJSON),
		}
	}

	// 创建Job
	createdJobID, err := h.asyncService.AsyncJobCreate(ctx, tasks)
	if err != nil {
		log.ErrorContextf(ctx, "[BatchCreateNodes] Failed to create job: %v", err)
		common.HandleAppError(c, errors.Internal("failed to create batch job", err))
		return
	}

	log.InfoContextf(ctx, "[BatchCreateNodes] Batch job created successfully: JobID=%s", createdJobID)

	response := BatchOperationResponse{
		JobID:        createdJobID,
		TotalTaskCnt: len(tasks),
		Message:      "批量创建任务已提交，请通过job_id查询任务状态",
	}
	common.SuccessResponse(c, "批量创建任务提交成功", []BatchOperationResponse{response})
}

// BatchDeleteNodes 批量删除节点
// POST /api/v1/cloud_node/batch/delete
func (h *BatchOperationHandler) BatchDeleteNodes(c *gin.Context) {
	ctx := c.Request.Context()
	var req BatchDeleteNodeRequest

	if err := c.ShouldBindJSON(&req); err != nil {
		common.HandleAppError(c, errors.InvalidParam("request_body", err.Error()))
		return
	}

	if len(req.NodeIDs) == 0 {
		common.HandleAppError(c, errors.InvalidParam("node_ids", "node_ids cannot be empty"))
		return
	}

	// 生成JobID
	// jobID will be auto-generated by service
	log.InfoContextf(ctx, "[BatchDeleteNodes] Creating batch job: NodeCount=%d", len(req.NodeIDs))

	// 构建任务列表
	tasks := make([]asynctask.TaskRequest, len(req.NodeIDs))
	for i, nodeID := range req.NodeIDs {
		deleteItem := map[string]string{
			"node_id": nodeID,
		}
		paramsJSON, err := json.Marshal(deleteItem)
		if err != nil {
			common.HandleAppError(c, errors.InvalidParam("node_ids", "invalid node_id"))
			return
		}

		tasks[i] = asynctask.TaskRequest{
			TaskType:      asynctask.TaskTypeDeleteNode,
			RequestParams: string(paramsJSON),
		}
	}

	// 创建Job
	createdJobID, err := h.asyncService.AsyncJobCreate(ctx, tasks)
	if err != nil {
		log.ErrorContextf(ctx, "[BatchDeleteNodes] Failed to create job: %v", err)
		common.HandleAppError(c, errors.Internal("failed to create batch job", err))
		return
	}

	log.InfoContextf(ctx, "[BatchDeleteNodes] Batch job created successfully: JobID=%s", createdJobID)

	response := BatchOperationResponse{
		JobID:        createdJobID,
		TotalTaskCnt: len(tasks),
		Message:      "批量删除任务已提交，请通过job_id查询任务状态",
	}
	common.SuccessResponse(c, "批量删除任务提交成功", []BatchOperationResponse{response})
}

// BatchDeployNodes 批量部署节点
// POST /api/v1/cloud_node/batch/deploy
func (h *BatchOperationHandler) BatchDeployNodes(c *gin.Context) {
	ctx := c.Request.Context()
	var req BatchDeployNodeRequest

	if err := c.ShouldBindJSON(&req); err != nil {
		common.HandleAppError(c, errors.InvalidParam("request_body", err.Error()))
		return
	}

	if len(req.Deployments) == 0 {
		common.HandleAppError(c, errors.InvalidParam("deployments", "deployments cannot be empty"))
		return
	}

	// 生成JobID
	// jobID will be auto-generated by service
	log.InfoContextf(ctx, "[BatchDeployNodes] Creating batch job: DeploymentCount=%d", len(req.Deployments))

	// 构建任务列表
	tasks := make([]asynctask.TaskRequest, len(req.Deployments))
	for i, deployment := range req.Deployments {
		// 将部署参数转为JSON字符串
		paramsJSON, err := json.Marshal(deployment)
		if err != nil {
			common.HandleAppError(c, errors.InvalidParam("deployments", "invalid deployment parameters"))
			return
		}

		tasks[i] = asynctask.TaskRequest{
			TaskType:      asynctask.TaskTypeDeployNode,
			RequestParams: string(paramsJSON),
		}
	}

	// 创建Job
	createdJobID, err := h.asyncService.AsyncJobCreate(ctx, tasks)
	if err != nil {
		log.ErrorContextf(ctx, "[BatchDeployNodes] Failed to create job: %v", err)
		common.HandleAppError(c, errors.Internal("failed to create batch job", err))
		return
	}

	log.InfoContextf(ctx, "[BatchDeployNodes] Batch job created successfully: JobID=%s", createdJobID)

	response := BatchOperationResponse{
		JobID:        createdJobID,
		TotalTaskCnt: len(tasks),
		Message:      "批量部署任务已提交，请通过job_id查询任务状态",
	}
	common.SuccessResponse(c, "批量部署任务提交成功", []BatchOperationResponse{response})
}
