// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: factor.proto

package factorpb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// FactorMgrService defines service.
type FactorMgrService interface {
	CreateFactor(ctx context.Context, req *CreateFactorReq) (*CreateFactorRsp, error)

	UpdateFactor(ctx context.Context, req *UpdateFactorReq) (*UpdateFactorRsp, error)

	GetFactor(ctx context.Context, req *GetFactorReq) (*GetFactorRsp, error)

	ListFactors(ctx context.Context, req *ListFactorsReq) (*ListFactorsRsp, error)

	SetFactorStatus(ctx context.Context, req *SetFactorStatusReq) (*SetFactorStatusRsp, error)

	UpsertBinding(ctx context.Context, req *UpsertBindingReq) (*UpsertBindingRsp, error)

	ListBindings(ctx context.Context, req *ListBindingsReq) (*ListBindingsRsp, error)

	DeleteBinding(ctx context.Context, req *DeleteBindingReq) (*DeleteBindingRsp, error)

	RecalcFactor(ctx context.Context, req *RecalcFactorReq) (*RecalcFactorRsp, error)

	GetEngineStatus(ctx context.Context, req *GetEngineStatusReq) (*GetEngineStatusRsp, error)
}

func FactorMgrService_CreateFactor_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateFactorReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).CreateFactor(ctx, reqbody.(*CreateFactorReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_UpdateFactor_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateFactorReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).UpdateFactor(ctx, reqbody.(*UpdateFactorReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_GetFactor_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetFactorReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).GetFactor(ctx, reqbody.(*GetFactorReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_ListFactors_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListFactorsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).ListFactors(ctx, reqbody.(*ListFactorsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_SetFactorStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SetFactorStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).SetFactorStatus(ctx, reqbody.(*SetFactorStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_UpsertBinding_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpsertBindingReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).UpsertBinding(ctx, reqbody.(*UpsertBindingReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_ListBindings_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListBindingsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).ListBindings(ctx, reqbody.(*ListBindingsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_DeleteBinding_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteBindingReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).DeleteBinding(ctx, reqbody.(*DeleteBindingReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_RecalcFactor_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RecalcFactorReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).RecalcFactor(ctx, reqbody.(*RecalcFactorReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func FactorMgrService_GetEngineStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetEngineStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(FactorMgrService).GetEngineStatus(ctx, reqbody.(*GetEngineStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// FactorMgrServer_ServiceDesc descriptor for server.RegisterService.
var FactorMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.factor.FactorMgr",
	HandlerType: ((*FactorMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.factor.FactorMgr/CreateFactor",
			Func: FactorMgrService_CreateFactor_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/UpdateFactor",
			Func: FactorMgrService_UpdateFactor_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/GetFactor",
			Func: FactorMgrService_GetFactor_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/ListFactors",
			Func: FactorMgrService_ListFactors_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/SetFactorStatus",
			Func: FactorMgrService_SetFactorStatus_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/UpsertBinding",
			Func: FactorMgrService_UpsertBinding_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/ListBindings",
			Func: FactorMgrService_ListBindings_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/DeleteBinding",
			Func: FactorMgrService_DeleteBinding_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/RecalcFactor",
			Func: FactorMgrService_RecalcFactor_Handler,
		},
		{
			Name: "/trpc.moox.factor.FactorMgr/GetEngineStatus",
			Func: FactorMgrService_GetEngineStatus_Handler,
		},
	},
}

// RegisterFactorMgrService registers service.
func RegisterFactorMgrService(s server.Service, svr FactorMgrService) {
	if err := s.Register(&FactorMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("FactorMgr register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedFactorMgr struct{}

func (s *UnimplementedFactorMgr) CreateFactor(ctx context.Context, req *CreateFactorReq) (*CreateFactorRsp, error) {
	return nil, errors.New("rpc CreateFactor of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) UpdateFactor(ctx context.Context, req *UpdateFactorReq) (*UpdateFactorRsp, error) {
	return nil, errors.New("rpc UpdateFactor of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) GetFactor(ctx context.Context, req *GetFactorReq) (*GetFactorRsp, error) {
	return nil, errors.New("rpc GetFactor of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) ListFactors(ctx context.Context, req *ListFactorsReq) (*ListFactorsRsp, error) {
	return nil, errors.New("rpc ListFactors of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) SetFactorStatus(ctx context.Context, req *SetFactorStatusReq) (*SetFactorStatusRsp, error) {
	return nil, errors.New("rpc SetFactorStatus of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) UpsertBinding(ctx context.Context, req *UpsertBindingReq) (*UpsertBindingRsp, error) {
	return nil, errors.New("rpc UpsertBinding of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) ListBindings(ctx context.Context, req *ListBindingsReq) (*ListBindingsRsp, error) {
	return nil, errors.New("rpc ListBindings of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) DeleteBinding(ctx context.Context, req *DeleteBindingReq) (*DeleteBindingRsp, error) {
	return nil, errors.New("rpc DeleteBinding of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) RecalcFactor(ctx context.Context, req *RecalcFactorReq) (*RecalcFactorRsp, error) {
	return nil, errors.New("rpc RecalcFactor of service FactorMgr is not implemented")
}
func (s *UnimplementedFactorMgr) GetEngineStatus(ctx context.Context, req *GetEngineStatusReq) (*GetEngineStatusRsp, error) {
	return nil, errors.New("rpc GetEngineStatus of service FactorMgr is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// FactorMgrClientProxy defines service client proxy
type FactorMgrClientProxy interface {
	CreateFactor(ctx context.Context, req *CreateFactorReq, opts ...client.Option) (rsp *CreateFactorRsp, err error)

	UpdateFactor(ctx context.Context, req *UpdateFactorReq, opts ...client.Option) (rsp *UpdateFactorRsp, err error)

	GetFactor(ctx context.Context, req *GetFactorReq, opts ...client.Option) (rsp *GetFactorRsp, err error)

	ListFactors(ctx context.Context, req *ListFactorsReq, opts ...client.Option) (rsp *ListFactorsRsp, err error)

	SetFactorStatus(ctx context.Context, req *SetFactorStatusReq, opts ...client.Option) (rsp *SetFactorStatusRsp, err error)

	UpsertBinding(ctx context.Context, req *UpsertBindingReq, opts ...client.Option) (rsp *UpsertBindingRsp, err error)

	ListBindings(ctx context.Context, req *ListBindingsReq, opts ...client.Option) (rsp *ListBindingsRsp, err error)

	DeleteBinding(ctx context.Context, req *DeleteBindingReq, opts ...client.Option) (rsp *DeleteBindingRsp, err error)

	RecalcFactor(ctx context.Context, req *RecalcFactorReq, opts ...client.Option) (rsp *RecalcFactorRsp, err error)

	GetEngineStatus(ctx context.Context, req *GetEngineStatusReq, opts ...client.Option) (rsp *GetEngineStatusRsp, err error)
}

type FactorMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewFactorMgrClientProxy = func(opts ...client.Option) FactorMgrClientProxy {
	return &FactorMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *FactorMgrClientProxyImpl) CreateFactor(ctx context.Context, req *CreateFactorReq, opts ...client.Option) (*CreateFactorRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/CreateFactor")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("CreateFactor")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateFactorRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) UpdateFactor(ctx context.Context, req *UpdateFactorReq, opts ...client.Option) (*UpdateFactorRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/UpdateFactor")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("UpdateFactor")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateFactorRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) GetFactor(ctx context.Context, req *GetFactorReq, opts ...client.Option) (*GetFactorRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/GetFactor")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("GetFactor")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetFactorRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) ListFactors(ctx context.Context, req *ListFactorsReq, opts ...client.Option) (*ListFactorsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/ListFactors")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("ListFactors")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListFactorsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) SetFactorStatus(ctx context.Context, req *SetFactorStatusReq, opts ...client.Option) (*SetFactorStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/SetFactorStatus")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("SetFactorStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SetFactorStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) UpsertBinding(ctx context.Context, req *UpsertBindingReq, opts ...client.Option) (*UpsertBindingRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/UpsertBinding")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("UpsertBinding")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpsertBindingRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) ListBindings(ctx context.Context, req *ListBindingsReq, opts ...client.Option) (*ListBindingsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/ListBindings")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("ListBindings")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListBindingsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) DeleteBinding(ctx context.Context, req *DeleteBindingReq, opts ...client.Option) (*DeleteBindingRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/DeleteBinding")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("DeleteBinding")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteBindingRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) RecalcFactor(ctx context.Context, req *RecalcFactorReq, opts ...client.Option) (*RecalcFactorRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/RecalcFactor")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("RecalcFactor")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RecalcFactorRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *FactorMgrClientProxyImpl) GetEngineStatus(ctx context.Context, req *GetEngineStatusReq, opts ...client.Option) (*GetEngineStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.factor.FactorMgr/GetEngineStatus")
	msg.WithCalleeServiceName(FactorMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("factor")
	msg.WithCalleeService("FactorMgr")
	msg.WithCalleeMethod("GetEngineStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetEngineStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
