global:
  namespace: Development
  env_name: dev

server:
  timeout: 30000
  service:
    - name: trpc.moox.strategy.StrategyMgr
      port: 11430
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.strategy.Health
      port: 11431
      network: tcp
      protocol: http_no_protocol
      timeout: 3000
