global:
  namespace: Development
  env_name: dev

server:
  filter:
    - recovery
    - validation
    - prometheus
  timeout: 30000
  service:
    - name: trpc.moox.strategy.StrategyMgr
      ip: 127.0.0.1
      port: 11430
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.strategy.Health
      ip: 127.0.0.1
      port: 11431
      network: tcp
      protocol: http_no_protocol
      timeout: 3000

plugins:
  auth:
    validation:
      enable_error_log: false
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  metrics:
    prometheus:
      ip: 127.0.0.1
      port: 12930
      path: /metrics
      enablepush: false
