metadata_database: 
  storage_device: "sqlite:/Users/mooyang/Documents/go/src/github.com/mooyang-code/xData-mini/storage/release/data/sqlite/metadata.db"

storage: 
  target: "127.0.0.1:18201"

moox: 
  auth_target: "127.0.0.1:20001"

message:
  server: nats:localhost:4222   # NATS服务器地址
  consumer: MY_CONSUMER         # 消费者名称
  subject: storage.datadetail.change           # 订阅主题
