global:
  namespace: Development
  env_name: dev

server:
  filter:
    - recovery
    - validation
    - masking
    - opentelemetry
    - prometheus
  timeout: 5000
  admin:
    ip: 127.0.0.1
    port: 11900
    read_timeout: 3000
    write_timeout: 60000
  service:
    - name: trpc.moox.gateway.control
      ip: 127.0.0.1
      port: 11000
      network: tcp
      protocol: http_no_protocol
      timeout: 30000
    - name: trpc.moox.gateway.service
      ip: 127.0.0.1
      port: 11002
      network: tcp
      protocol: http_no_protocol
      timeout: 30000
    - name: trpc.moox.admin.Health
      ip: 127.0.0.1
      port: 11010
      network: tcp
      protocol: http_no_protocol
      timeout: 3000
    - name: trpc.moox.infra.Auth
      ip: 127.0.0.1
      port: 11100
      network: tcp
      protocol: http
      timeout: 10000
    - name: trpc.moox.infra.Dns
      ip: 127.0.0.1
      port: 11101
      network: tcp
      protocol: http
      timeout: 10000
    - name: trpc.moox.ops.Ssh
      ip: 127.0.0.1
      port: 11106
      network: tcp
      protocol: http
      timeout: 30000
    - name: trpc.moox.admin.SpaceMgr
      ip: 127.0.0.1
      port: 11107
      network: tcp
      protocol: http
      timeout: 10000
    - name: trpc.moox.ops.SecretMgr
      ip: 127.0.0.1
      port: 11108
      network: tcp
      protocol: http
      timeout: 10000
    - name: trpc.moox.ops.SysDeploy
      ip: 127.0.0.1
      port: 11109
      network: tcp
      protocol: http
      timeout: 10000
    - name: trpc.dnsproxy.timer
      port: 11301
      network: "0 */5 * * * *?scheduler=dnsproxySchedule"
      protocol: timer
      timeout: 60000
    - name: trpc.dnsprobe.timer
      port: 11302
      network: "0 */5 * * * *?scheduler=dnsProbeSchedule"
      protocol: timer
      timeout: 60000
    - name: trpc.moox.admin.metrics.timer
      port: 11305
      network: "*/30 * * * * *"
      protocol: timer
      timeout: 10000

client:
  filter:
    - opentelemetry

plugins:
  metrics:
    prometheus:
      ip: 127.0.0.1
      port: 12900
      path: /metrics
      enablepush: false
  auth:
    validation:
      enable_error_log: false
      server_validate_err_code: 100101
      client_validate_err_code: 100102
  log:
    default:
      - writer: console
        level: info
