// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: strategy.proto

package strategypb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// StrategyMgrService defines service.
type StrategyMgrService interface {
	CreateStrategy(ctx context.Context, req *CreateStrategyReq) (*CreateStrategyRsp, error)

	RunOnce(ctx context.Context, req *RunOnceReq) (*RunOnceRsp, error)

	GetEngineStatus(ctx context.Context, req *GetEngineStatusReq) (*GetEngineStatusRsp, error)
}

func StrategyMgrService_CreateStrategy_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateStrategyReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).CreateStrategy(ctx, reqbody.(*CreateStrategyReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_RunOnce_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &RunOnceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).RunOnce(ctx, reqbody.(*RunOnceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_GetEngineStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetEngineStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).GetEngineStatus(ctx, reqbody.(*GetEngineStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// StrategyMgrServer_ServiceDesc descriptor for server.RegisterService.
var StrategyMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.strategy.StrategyMgr",
	HandlerType: ((*StrategyMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.strategy.StrategyMgr/CreateStrategy",
			Func: StrategyMgrService_CreateStrategy_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/RunOnce",
			Func: StrategyMgrService_RunOnce_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/GetEngineStatus",
			Func: StrategyMgrService_GetEngineStatus_Handler,
		},
	},
}

// RegisterStrategyMgrService registers service.
func RegisterStrategyMgrService(s server.Service, svr StrategyMgrService) {
	if err := s.Register(&StrategyMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("StrategyMgr register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedStrategyMgr struct{}

func (s *UnimplementedStrategyMgr) CreateStrategy(ctx context.Context, req *CreateStrategyReq) (*CreateStrategyRsp, error) {
	return nil, errors.New("rpc CreateStrategy of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) RunOnce(ctx context.Context, req *RunOnceReq) (*RunOnceRsp, error) {
	return nil, errors.New("rpc RunOnce of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) GetEngineStatus(ctx context.Context, req *GetEngineStatusReq) (*GetEngineStatusRsp, error) {
	return nil, errors.New("rpc GetEngineStatus of service StrategyMgr is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// StrategyMgrClientProxy defines service client proxy
type StrategyMgrClientProxy interface {
	CreateStrategy(ctx context.Context, req *CreateStrategyReq, opts ...client.Option) (rsp *CreateStrategyRsp, err error)

	RunOnce(ctx context.Context, req *RunOnceReq, opts ...client.Option) (rsp *RunOnceRsp, err error)

	GetEngineStatus(ctx context.Context, req *GetEngineStatusReq, opts ...client.Option) (rsp *GetEngineStatusRsp, err error)
}

type StrategyMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewStrategyMgrClientProxy = func(opts ...client.Option) StrategyMgrClientProxy {
	return &StrategyMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *StrategyMgrClientProxyImpl) CreateStrategy(ctx context.Context, req *CreateStrategyReq, opts ...client.Option) (*CreateStrategyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/CreateStrategy")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("CreateStrategy")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateStrategyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) RunOnce(ctx context.Context, req *RunOnceReq, opts ...client.Option) (*RunOnceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/RunOnce")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("RunOnce")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &RunOnceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) GetEngineStatus(ctx context.Context, req *GetEngineStatusReq, opts ...client.Option) (*GetEngineStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/GetEngineStatus")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("GetEngineStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetEngineStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
