// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: strategy.proto

package strategypb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// StrategyMgrService defines service.
type StrategyMgrService interface {
	CreateStrategy(ctx context.Context, req *CreateStrategyReq) (*CreateStrategyRsp, error)

	UpdateStrategy(ctx context.Context, req *UpdateStrategyReq) (*UpdateStrategyRsp, error)

	GetStrategy(ctx context.Context, req *GetStrategyReq) (*GetStrategyRsp, error)

	ListStrategies(ctx context.Context, req *ListStrategiesReq) (*ListStrategiesRsp, error)

	CreateRunner(ctx context.Context, req *CreateRunnerReq) (*CreateRunnerRsp, error)

	GetRunner(ctx context.Context, req *GetRunnerReq) (*GetRunnerRsp, error)

	ListRunners(ctx context.Context, req *ListRunnersReq) (*ListRunnersRsp, error)

	UpdateRunner(ctx context.Context, req *UpdateRunnerReq) (*UpdateRunnerRsp, error)

	SetRunnerStatus(ctx context.Context, req *SetRunnerStatusReq) (*SetRunnerStatusRsp, error)

	ListStrategyResults(ctx context.Context, req *ListStrategyResultsReq) (*ListStrategyResultsRsp, error)

	GetStrategyResult(ctx context.Context, req *GetStrategyResultReq) (*GetStrategyResultRsp, error)

	ListStrategyTargets(ctx context.Context, req *ListStrategyTargetsReq) (*ListStrategyTargetsRsp, error)

	CreateStrategyInstance(ctx context.Context, req *CreateStrategyInstanceReq) (*CreateStrategyInstanceRsp, error)

	GetStrategyInstance(ctx context.Context, req *GetStrategyInstanceReq) (*GetStrategyInstanceRsp, error)

	ListStrategyInstances(ctx context.Context, req *ListStrategyInstancesReq) (*ListStrategyInstancesRsp, error)

	SetStrategyInstanceEnabled(ctx context.Context, req *SetStrategyInstanceEnabledReq) (*SetStrategyInstanceEnabledRsp, error)
}

func StrategyMgrService_CreateStrategy_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateStrategyReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).CreateStrategy(ctx, reqbody.(*CreateStrategyReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_UpdateStrategy_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateStrategyReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).UpdateStrategy(ctx, reqbody.(*UpdateStrategyReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_GetStrategy_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetStrategyReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).GetStrategy(ctx, reqbody.(*GetStrategyReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_ListStrategies_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListStrategiesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).ListStrategies(ctx, reqbody.(*ListStrategiesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_CreateRunner_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateRunnerReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).CreateRunner(ctx, reqbody.(*CreateRunnerReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_GetRunner_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetRunnerReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).GetRunner(ctx, reqbody.(*GetRunnerReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_ListRunners_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListRunnersReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).ListRunners(ctx, reqbody.(*ListRunnersReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_UpdateRunner_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateRunnerReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).UpdateRunner(ctx, reqbody.(*UpdateRunnerReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_SetRunnerStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SetRunnerStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).SetRunnerStatus(ctx, reqbody.(*SetRunnerStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_ListStrategyResults_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListStrategyResultsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).ListStrategyResults(ctx, reqbody.(*ListStrategyResultsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_GetStrategyResult_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetStrategyResultReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).GetStrategyResult(ctx, reqbody.(*GetStrategyResultReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_ListStrategyTargets_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListStrategyTargetsReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).ListStrategyTargets(ctx, reqbody.(*ListStrategyTargetsReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_CreateStrategyInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateStrategyInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).CreateStrategyInstance(ctx, reqbody.(*CreateStrategyInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_GetStrategyInstance_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetStrategyInstanceReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).GetStrategyInstance(ctx, reqbody.(*GetStrategyInstanceReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_ListStrategyInstances_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ListStrategyInstancesReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).ListStrategyInstances(ctx, reqbody.(*ListStrategyInstancesReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func StrategyMgrService_SetStrategyInstanceEnabled_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SetStrategyInstanceEnabledReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(StrategyMgrService).SetStrategyInstanceEnabled(ctx, reqbody.(*SetStrategyInstanceEnabledReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// StrategyMgrServer_ServiceDesc descriptor for server.RegisterService.
var StrategyMgrServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.moox.strategy.StrategyMgr",
	HandlerType: ((*StrategyMgrService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.moox.strategy.StrategyMgr/CreateStrategy",
			Func: StrategyMgrService_CreateStrategy_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/UpdateStrategy",
			Func: StrategyMgrService_UpdateStrategy_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/GetStrategy",
			Func: StrategyMgrService_GetStrategy_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/ListStrategies",
			Func: StrategyMgrService_ListStrategies_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/CreateRunner",
			Func: StrategyMgrService_CreateRunner_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/GetRunner",
			Func: StrategyMgrService_GetRunner_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/ListRunners",
			Func: StrategyMgrService_ListRunners_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/UpdateRunner",
			Func: StrategyMgrService_UpdateRunner_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/SetRunnerStatus",
			Func: StrategyMgrService_SetRunnerStatus_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/ListStrategyResults",
			Func: StrategyMgrService_ListStrategyResults_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/GetStrategyResult",
			Func: StrategyMgrService_GetStrategyResult_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/ListStrategyTargets",
			Func: StrategyMgrService_ListStrategyTargets_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/CreateStrategyInstance",
			Func: StrategyMgrService_CreateStrategyInstance_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/GetStrategyInstance",
			Func: StrategyMgrService_GetStrategyInstance_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/ListStrategyInstances",
			Func: StrategyMgrService_ListStrategyInstances_Handler,
		},
		{
			Name: "/trpc.moox.strategy.StrategyMgr/SetStrategyInstanceEnabled",
			Func: StrategyMgrService_SetStrategyInstanceEnabled_Handler,
		},
	},
}

// RegisterStrategyMgrService registers service.
func RegisterStrategyMgrService(s server.Service, svr StrategyMgrService) {
	if err := s.Register(&StrategyMgrServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("StrategyMgr register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedStrategyMgr struct{}

func (s *UnimplementedStrategyMgr) CreateStrategy(ctx context.Context, req *CreateStrategyReq) (*CreateStrategyRsp, error) {
	return nil, errors.New("rpc CreateStrategy of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) UpdateStrategy(ctx context.Context, req *UpdateStrategyReq) (*UpdateStrategyRsp, error) {
	return nil, errors.New("rpc UpdateStrategy of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) GetStrategy(ctx context.Context, req *GetStrategyReq) (*GetStrategyRsp, error) {
	return nil, errors.New("rpc GetStrategy of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) ListStrategies(ctx context.Context, req *ListStrategiesReq) (*ListStrategiesRsp, error) {
	return nil, errors.New("rpc ListStrategies of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) CreateRunner(ctx context.Context, req *CreateRunnerReq) (*CreateRunnerRsp, error) {
	return nil, errors.New("rpc CreateRunner of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) GetRunner(ctx context.Context, req *GetRunnerReq) (*GetRunnerRsp, error) {
	return nil, errors.New("rpc GetRunner of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) ListRunners(ctx context.Context, req *ListRunnersReq) (*ListRunnersRsp, error) {
	return nil, errors.New("rpc ListRunners of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) UpdateRunner(ctx context.Context, req *UpdateRunnerReq) (*UpdateRunnerRsp, error) {
	return nil, errors.New("rpc UpdateRunner of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) SetRunnerStatus(ctx context.Context, req *SetRunnerStatusReq) (*SetRunnerStatusRsp, error) {
	return nil, errors.New("rpc SetRunnerStatus of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) ListStrategyResults(ctx context.Context, req *ListStrategyResultsReq) (*ListStrategyResultsRsp, error) {
	return nil, errors.New("rpc ListStrategyResults of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) GetStrategyResult(ctx context.Context, req *GetStrategyResultReq) (*GetStrategyResultRsp, error) {
	return nil, errors.New("rpc GetStrategyResult of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) ListStrategyTargets(ctx context.Context, req *ListStrategyTargetsReq) (*ListStrategyTargetsRsp, error) {
	return nil, errors.New("rpc ListStrategyTargets of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) CreateStrategyInstance(ctx context.Context, req *CreateStrategyInstanceReq) (*CreateStrategyInstanceRsp, error) {
	return nil, errors.New("rpc CreateStrategyInstance of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) GetStrategyInstance(ctx context.Context, req *GetStrategyInstanceReq) (*GetStrategyInstanceRsp, error) {
	return nil, errors.New("rpc GetStrategyInstance of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) ListStrategyInstances(ctx context.Context, req *ListStrategyInstancesReq) (*ListStrategyInstancesRsp, error) {
	return nil, errors.New("rpc ListStrategyInstances of service StrategyMgr is not implemented")
}
func (s *UnimplementedStrategyMgr) SetStrategyInstanceEnabled(ctx context.Context, req *SetStrategyInstanceEnabledReq) (*SetStrategyInstanceEnabledRsp, error) {
	return nil, errors.New("rpc SetStrategyInstanceEnabled of service StrategyMgr is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// StrategyMgrClientProxy defines service client proxy
type StrategyMgrClientProxy interface {
	CreateStrategy(ctx context.Context, req *CreateStrategyReq, opts ...client.Option) (rsp *CreateStrategyRsp, err error)

	UpdateStrategy(ctx context.Context, req *UpdateStrategyReq, opts ...client.Option) (rsp *UpdateStrategyRsp, err error)

	GetStrategy(ctx context.Context, req *GetStrategyReq, opts ...client.Option) (rsp *GetStrategyRsp, err error)

	ListStrategies(ctx context.Context, req *ListStrategiesReq, opts ...client.Option) (rsp *ListStrategiesRsp, err error)

	CreateRunner(ctx context.Context, req *CreateRunnerReq, opts ...client.Option) (rsp *CreateRunnerRsp, err error)

	GetRunner(ctx context.Context, req *GetRunnerReq, opts ...client.Option) (rsp *GetRunnerRsp, err error)

	ListRunners(ctx context.Context, req *ListRunnersReq, opts ...client.Option) (rsp *ListRunnersRsp, err error)

	UpdateRunner(ctx context.Context, req *UpdateRunnerReq, opts ...client.Option) (rsp *UpdateRunnerRsp, err error)

	SetRunnerStatus(ctx context.Context, req *SetRunnerStatusReq, opts ...client.Option) (rsp *SetRunnerStatusRsp, err error)

	ListStrategyResults(ctx context.Context, req *ListStrategyResultsReq, opts ...client.Option) (rsp *ListStrategyResultsRsp, err error)

	GetStrategyResult(ctx context.Context, req *GetStrategyResultReq, opts ...client.Option) (rsp *GetStrategyResultRsp, err error)

	ListStrategyTargets(ctx context.Context, req *ListStrategyTargetsReq, opts ...client.Option) (rsp *ListStrategyTargetsRsp, err error)

	CreateStrategyInstance(ctx context.Context, req *CreateStrategyInstanceReq, opts ...client.Option) (rsp *CreateStrategyInstanceRsp, err error)

	GetStrategyInstance(ctx context.Context, req *GetStrategyInstanceReq, opts ...client.Option) (rsp *GetStrategyInstanceRsp, err error)

	ListStrategyInstances(ctx context.Context, req *ListStrategyInstancesReq, opts ...client.Option) (rsp *ListStrategyInstancesRsp, err error)

	SetStrategyInstanceEnabled(ctx context.Context, req *SetStrategyInstanceEnabledReq, opts ...client.Option) (rsp *SetStrategyInstanceEnabledRsp, err error)
}

type StrategyMgrClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewStrategyMgrClientProxy = func(opts ...client.Option) StrategyMgrClientProxy {
	return &StrategyMgrClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *StrategyMgrClientProxyImpl) CreateStrategy(ctx context.Context, req *CreateStrategyReq, opts ...client.Option) (*CreateStrategyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/CreateStrategy")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("CreateStrategy")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateStrategyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) UpdateStrategy(ctx context.Context, req *UpdateStrategyReq, opts ...client.Option) (*UpdateStrategyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/UpdateStrategy")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("UpdateStrategy")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateStrategyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) GetStrategy(ctx context.Context, req *GetStrategyReq, opts ...client.Option) (*GetStrategyRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/GetStrategy")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("GetStrategy")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetStrategyRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) ListStrategies(ctx context.Context, req *ListStrategiesReq, opts ...client.Option) (*ListStrategiesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/ListStrategies")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("ListStrategies")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListStrategiesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) CreateRunner(ctx context.Context, req *CreateRunnerReq, opts ...client.Option) (*CreateRunnerRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/CreateRunner")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("CreateRunner")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateRunnerRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) GetRunner(ctx context.Context, req *GetRunnerReq, opts ...client.Option) (*GetRunnerRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/GetRunner")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("GetRunner")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetRunnerRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) ListRunners(ctx context.Context, req *ListRunnersReq, opts ...client.Option) (*ListRunnersRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/ListRunners")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("ListRunners")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListRunnersRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) UpdateRunner(ctx context.Context, req *UpdateRunnerReq, opts ...client.Option) (*UpdateRunnerRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/UpdateRunner")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("UpdateRunner")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateRunnerRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) SetRunnerStatus(ctx context.Context, req *SetRunnerStatusReq, opts ...client.Option) (*SetRunnerStatusRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/SetRunnerStatus")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("SetRunnerStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SetRunnerStatusRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) ListStrategyResults(ctx context.Context, req *ListStrategyResultsReq, opts ...client.Option) (*ListStrategyResultsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/ListStrategyResults")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("ListStrategyResults")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListStrategyResultsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) GetStrategyResult(ctx context.Context, req *GetStrategyResultReq, opts ...client.Option) (*GetStrategyResultRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/GetStrategyResult")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("GetStrategyResult")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetStrategyResultRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) ListStrategyTargets(ctx context.Context, req *ListStrategyTargetsReq, opts ...client.Option) (*ListStrategyTargetsRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/ListStrategyTargets")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("ListStrategyTargets")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListStrategyTargetsRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) CreateStrategyInstance(ctx context.Context, req *CreateStrategyInstanceReq, opts ...client.Option) (*CreateStrategyInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/CreateStrategyInstance")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("CreateStrategyInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateStrategyInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) GetStrategyInstance(ctx context.Context, req *GetStrategyInstanceReq, opts ...client.Option) (*GetStrategyInstanceRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/GetStrategyInstance")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("GetStrategyInstance")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetStrategyInstanceRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) ListStrategyInstances(ctx context.Context, req *ListStrategyInstancesReq, opts ...client.Option) (*ListStrategyInstancesRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/ListStrategyInstances")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("ListStrategyInstances")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ListStrategyInstancesRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *StrategyMgrClientProxyImpl) SetStrategyInstanceEnabled(ctx context.Context, req *SetStrategyInstanceEnabledReq, opts ...client.Option) (*SetStrategyInstanceEnabledRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.moox.strategy.StrategyMgr/SetStrategyInstanceEnabled")
	msg.WithCalleeServiceName(StrategyMgrServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("moox")
	msg.WithCalleeServer("strategy")
	msg.WithCalleeService("StrategyMgr")
	msg.WithCalleeMethod("SetStrategyInstanceEnabled")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SetStrategyInstanceEnabledRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
